// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/ontology/concept-facts.md — DO NOT EDIT.
use std::collections::{BTreeMap, BTreeSet};

pub const X0K_NS: &str = "https://0k.computer/ontology#";
pub const CONCEPT_URI: &str = "https://0k.computer/ontology#Concept";
pub const MODULE_IRI_PREFIX: &str = "https://0k.computer/ontology/";
pub const STRUCTURAL_NODE_PREFIX: &str = "urn:x0k:ontology:blank:";

pub const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
pub const RDF_FIRST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#first";
pub const RDF_REST: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest";
pub const RDF_NIL: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil";
pub const RDFS_LABEL: &str = "http://www.w3.org/2000/01/rdf-schema#label";
pub const RDFS_COMMENT: &str = "http://www.w3.org/2000/01/rdf-schema#comment";
pub const RDFS_SUBCLASS_OF: &str = "http://www.w3.org/2000/01/rdf-schema#subClassOf";
pub const RDFS_DOMAIN: &str = "http://www.w3.org/2000/01/rdf-schema#domain";
pub const RDFS_RANGE: &str = "http://www.w3.org/2000/01/rdf-schema#range";
pub const RDFS_IS_DEFINED_BY: &str = "http://www.w3.org/2000/01/rdf-schema#isDefinedBy";
pub const OWL_CLASS: &str = "http://www.w3.org/2002/07/owl#Class";
pub const OWL_OBJECT_PROPERTY: &str = "http://www.w3.org/2002/07/owl#ObjectProperty";
pub const OWL_DATATYPE_PROPERTY: &str = "http://www.w3.org/2002/07/owl#DatatypeProperty";
pub const OWL_ANNOTATION_PROPERTY: &str = "http://www.w3.org/2002/07/owl#AnnotationProperty";
pub const OWL_UNION_OF: &str = "http://www.w3.org/2002/07/owl#unionOf";
pub const OWL_ONTOLOGY: &str = "http://www.w3.org/2002/07/owl#Ontology";
pub const OWL_IMPORTS: &str = "http://www.w3.org/2002/07/owl#imports";
pub const VANN_PREFERRED_NAMESPACE_URI: &str = "http://purl.org/vocab/vann/preferredNamespaceUri";

pub const X0K_TARGET_CLASS: &str = "https://0k.computer/ontology#targetClass";
pub const X0K_SUBJECT_CLASS: &str = "https://0k.computer/ontology#subjectClass";
/// The module name of a module IRI (`https://0k.computer/ontology/work` → `work`),
/// or `None` for anything else under the prefix, such as a term in an
/// extension's namespace.
pub fn module_name(iri: &str) -> Option<&str> {
    let name = iri.strip_prefix(MODULE_IRI_PREFIX)?;
    let well_formed = name.chars().next().is_some_and(|ch| ch.is_ascii_lowercase())
        && name.chars().all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-');
    well_formed.then_some(name)
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum OntologyValue {
    Text(String),
    Entity(String),
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct OntologyFact {
    pub entity: String,
    pub predicate: String,
    pub value: OntologyValue,
}
impl OntologyFact {
    pub fn text(entity: impl Into<String>, predicate: impl Into<String>, value: impl Into<String>) -> Self {
        Self { entity: entity.into(), predicate: predicate.into(), value: OntologyValue::Text(value.into()) }
    }

    pub fn entity(entity: impl Into<String>, predicate: impl Into<String>, value: impl Into<String>) -> Self {
        Self { entity: entity.into(), predicate: predicate.into(), value: OntologyValue::Entity(value.into()) }
    }
}
#[derive(Debug, Clone)]
pub struct OntologyModel {
    facts: Vec<OntologyFact>,
}

impl OntologyModel {
    pub fn new(facts: impl IntoIterator<Item = OntologyFact>) -> Self {
        let mut seen = BTreeSet::new();
        let facts = facts.into_iter().filter(|fact| seen.insert(fact.clone())).collect();
        Self { facts }
    }

    pub fn facts(&self) -> &[OntologyFact] {
        &self.facts
    }
}
impl OntologyModel {
    pub fn with_fact_plane_root(mut self) -> Self {
        self.ensure(OntologyFact::entity(CONCEPT_URI, RDF_TYPE, OWL_CLASS));
        self.ensure(OntologyFact::entity(CONCEPT_URI, RDF_TYPE, CONCEPT_URI));
        self.ensure(OntologyFact::text(CONCEPT_URI, RDFS_LABEL, "Concept"));
        self.ensure(OntologyFact::text(
            CONCEPT_URI,
            RDFS_COMMENT,
            "The root ontology concept: every registered class and property is typed by it, and it is typed by itself.",
        ));

        for entity in self.declared_entities() {
            self.ensure(OntologyFact::entity(entity, RDF_TYPE, CONCEPT_URI));
        }
        self
    }

    fn ensure(&mut self, fact: OntologyFact) {
        if !self.facts.contains(&fact) { self.facts.push(fact); }
    }
}
impl OntologyModel {
    fn declared_entities(&self) -> Vec<String> {
        let kinds = [OWL_CLASS, OWL_OBJECT_PROPERTY, OWL_DATATYPE_PROPERTY, OWL_ANNOTATION_PROPERTY];
        self.facts.iter().filter_map(|fact| match &fact.value {
            OntologyValue::Entity(kind) if fact.predicate == RDF_TYPE && kinds.contains(&kind.as_str()) => Some(fact.entity.clone()),
            _ => None,
        }).collect::<BTreeSet<_>>().into_iter().collect()
    }

    pub fn concept_entities(&self) -> BTreeSet<String> {
        self.entities_typed_as(CONCEPT_URI)
    }

    fn entities_typed_as(&self, kind: &str) -> BTreeSet<String> {
        self.facts.iter().filter_map(|fact| match &fact.value {
            OntologyValue::Entity(value) if fact.predicate == RDF_TYPE && value == kind => Some(fact.entity.clone()),
            _ => None,
        }).collect()
    }
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct ClassRecord {
    pub uri: String,
    pub label: String,
}

#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct PropertyRecord {
    pub uri: String,
    pub domain: Option<String>,
    pub range: Option<String>,
}
impl OntologyModel {
    /// The extension namespaces the modules declare, as `(prefix, namespace)`.
    fn extension_namespaces(&self) -> Vec<(String, String)> {
        self.modules().into_iter()
            .filter_map(|module| module.namespace.map(|namespace| (module.name, namespace)))
            .collect()
    }

    /// The compact name of a term IRI: `x0k:<Name>` in the base namespace,
    /// `<module>:<Name>` in a declared extension namespace, `None` for an
    /// IRI no module claims.
    pub fn compact(&self, iri: &str) -> Option<String> {
        if let Some(local) = iri.strip_prefix(X0K_NS) {
            return Some(format!("x0k:{local}"));
        }
        self.extension_namespaces().into_iter()
            .find_map(|(prefix, namespace)| iri.strip_prefix(namespace.as_str()).map(|local| format!("{prefix}:{local}")))
    }

    /// The inverse of [`compact`](Self::compact); a name with no known
    /// prefix is returned as it came.
    pub fn expand(&self, bare: &str) -> String {
        if let Some(local) = bare.strip_prefix("x0k:") {
            return format!("{X0K_NS}{local}");
        }
        self.extension_namespaces().into_iter()
            .find_map(|(prefix, namespace)| bare.strip_prefix(&format!("{prefix}:")).map(|local| format!("{namespace}{local}")))
            .unwrap_or_else(|| bare.to_string())
    }

    pub fn classes(&self) -> Vec<ClassRecord> {
        self.entities_typed_as(OWL_CLASS).into_iter().filter_map(|full| {
            let uri = self.compact(&full)?;
            let label = uri.rsplit(':').next().unwrap_or(&uri).to_string();
            Some(ClassRecord { uri, label })
        }).collect()
    }

    pub fn object_properties(&self) -> Vec<PropertyRecord> {
        self.entities_typed_as(OWL_OBJECT_PROPERTY).into_iter().filter_map(|full| {
            let uri = self.compact(&full)?;
            Some(PropertyRecord {
                uri,
                domain: self.first_class_value(&full, RDFS_DOMAIN),
                range: self.first_class_value(&full, RDFS_RANGE),
            })
        }).collect()
    }
}
impl OntologyModel {
    fn first_class_value(&self, entity: &str, predicate: &str) -> Option<String> {
        self.facts.iter().filter(|fact| fact.entity == entity && fact.predicate == predicate)
            .filter_map(|fact| match &fact.value { OntologyValue::Entity(value) => Some(value), _ => None })
            .flat_map(|value| self.resolve_class_set(value))
            .next().map(|iri| self.compact(&iri).unwrap_or(iri))
    }

    fn resolve_class_set(&self, node: &str) -> Vec<String> {
        if !node.starts_with(STRUCTURAL_NODE_PREFIX) { return vec![node.to_string()]; }
        self.entity_values(node, OWL_UNION_OF).into_iter()
            .flat_map(|head| self.rdf_list_members(&head)).collect()
    }

    fn entity_values(&self, entity: &str, predicate: &str) -> Vec<String> {
        self.facts.iter().filter_map(|fact| match &fact.value {
            OntologyValue::Entity(value) if fact.entity == entity && fact.predicate == predicate => Some(value.clone()),
            _ => None,
        }).collect()
    }

    fn text_values(&self, entity: &str, predicate: &str) -> Vec<String> {
        self.facts.iter().filter_map(|fact| match &fact.value {
            OntologyValue::Text(value) if fact.entity == entity && fact.predicate == predicate => Some(value.clone()),
            _ => None,
        }).collect()
    }

    /// The classes an axiom names, with `owl:unionOf` lists resolved to
    /// their members. The closure check reads cross-module references here.
    pub fn class_references(&self, entity: &str, predicate: &str) -> Vec<String> {
        self.entity_values(entity, predicate).into_iter()
            .flat_map(|node| self.resolve_class_set(&node)).collect()
    }
}
impl OntologyModel {
    fn rdf_list_members(&self, head: &str) -> Vec<String> {
        let mut out = Vec::new();
        let mut seen = BTreeSet::new();
        let mut cursor = head.to_string();
        while cursor != RDF_NIL && seen.insert(cursor.clone()) {
            if let Some(first) = self.entity_values(&cursor, RDF_FIRST).into_iter().next() { out.push(first); }
            let Some(rest) = self.entity_values(&cursor, RDF_REST).into_iter().next() else { break };
            cursor = rest;
        }
        out
    }
}
impl OntologyModel {
    pub fn decision_edge_predicates(&self) -> Vec<(String, String)> {
        let decision = format!("{X0K_NS}Decision");
        let mut classes = BTreeSet::from([decision.clone()]);
        for fact in &self.facts {
            if fact.predicate == RDFS_SUBCLASS_OF && fact.value == OntologyValue::Entity(decision.clone()) {
                classes.insert(fact.entity.clone());
            }
        }
        self.entities_typed_as(OWL_OBJECT_PROPERTY).into_iter().filter_map(|iri| {
            let in_scope = self.entity_values(&iri, RDFS_DOMAIN).into_iter()
                .flat_map(|node| self.resolve_class_set(&node))
                .chain(self.entity_values(&iri, X0K_SUBJECT_CLASS))
                .any(|class| classes.contains(&class));
            let camel = iri.strip_prefix(X0K_NS)?.to_string();
            in_scope.then(|| (camel_to_snake(&camel), camel))
        }).collect()
    }
}
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct ModuleRecord {
    pub iri: String,
    pub name: String,
    pub imports: Vec<String>,
    pub namespace: Option<String>,
}

impl OntologyModel {
    pub fn modules(&self) -> Vec<ModuleRecord> {
        self.entities_typed_as(OWL_ONTOLOGY).into_iter().filter_map(|iri| {
            let name = module_name(&iri)?.to_string();
            let mut imports = self.entity_values(&iri, OWL_IMPORTS);
            imports.sort();
            imports.dedup();
            let namespace = self.text_values(&iri, VANN_PREFERRED_NAMESPACE_URI).into_iter().next();
            Some(ModuleRecord { iri, name, imports, namespace })
        }).collect()
    }

    /// The modules an entity says define it. Exactly one for a well-formed
    /// term; the closure check reports every other count.
    pub fn defining_modules(&self, entity: &str) -> Vec<String> {
        self.entity_values(entity, RDFS_IS_DEFINED_BY)
    }

    fn defined_in(&self, module_iri: &str) -> BTreeSet<String> {
        self.facts.iter().filter(|fact| {
            fact.predicate == RDFS_IS_DEFINED_BY && fact.value == OntologyValue::Entity(module_iri.to_string())
        }).map(|fact| fact.entity.clone()).collect()
    }
}
impl OntologyModel {
    /// Modules with imports before importers, or the missing import or cycle
    /// that makes the set unloadable.
    pub fn import_order(&self) -> Result<Vec<ModuleRecord>, String> {
        let modules = self.modules();
        let by_iri: BTreeMap<&str, &ModuleRecord> = modules.iter().map(|module| (module.iri.as_str(), module)).collect();
        let mut state: BTreeMap<String, bool> = BTreeMap::new();
        let mut order = Vec::new();
        for module in &modules {
            visit_module(module, &by_iri, &mut state, &mut order, &mut Vec::new())?;
        }
        Ok(order)
    }

    /// The module and everything it transitively imports; references into
    /// this set are licensed, references outside it are closure errors.
    pub fn import_closure(&self, module_iri: &str) -> BTreeSet<String> {
        let modules = self.modules();
        let mut closure = BTreeSet::new();
        let mut pending = vec![module_iri.to_string()];
        while let Some(iri) = pending.pop() {
            if !closure.insert(iri.clone()) { continue; }
            if let Some(module) = modules.iter().find(|module| module.iri == iri) {
                pending.extend(module.imports.iter().cloned());
            }
        }
        closure
    }
}

fn visit_module(
    module: &ModuleRecord,
    by_iri: &BTreeMap<&str, &ModuleRecord>,
    state: &mut BTreeMap<String, bool>,
    order: &mut Vec<ModuleRecord>,
    path: &mut Vec<String>,
) -> Result<(), String> {
    match state.get(&module.iri) {
        Some(true) => return Ok(()),
        Some(false) => {
            path.push(module.iri.clone());
            return Err(format!("module import cycle: {}", path.join(" -> ")));
        }
        None => {}
    }
    state.insert(module.iri.clone(), false);
    path.push(module.iri.clone());
    for import in &module.imports {
        let Some(target) = by_iri.get(import.as_str()) else {
            return Err(format!("module {} imports {import}, which is not a module of the set", module.iri));
        };
        visit_module(target, by_iri, state, order, path)?;
    }
    path.pop();
    state.insert(module.iri.clone(), true);
    order.push(module.clone());
    Ok(())
}
impl OntologyModel {
    pub fn classes_in(&self, module_iri: &str) -> Vec<ClassRecord> {
        let defined = self.defined_in(module_iri);
        self.classes().into_iter().filter(|class| defined.contains(&self.expand(&class.uri))).collect()
    }

    pub fn object_properties_in(&self, module_iri: &str) -> Vec<PropertyRecord> {
        let defined = self.defined_in(module_iri);
        self.object_properties().into_iter().filter(|property| defined.contains(&self.expand(&property.uri))).collect()
    }

    pub fn decision_edge_predicates_in(&self, module_iri: &str) -> Vec<(String, String)> {
        let defined = self.defined_in(module_iri);
        self.decision_edge_predicates().into_iter()
            .filter(|(_, camel)| defined.contains(&format!("{X0K_NS}{camel}"))).collect()
    }
}
impl OntologyModel {
    pub fn module_facts(&self, module_iri: &str) -> Vec<&OntologyFact> {
        let mut owners = self.defined_in(module_iri);
        owners.insert(module_iri.to_string());
        let mut pending: Vec<String> = owners.iter().cloned().collect();
        while let Some(entity) = pending.pop() {
            for fact in self.facts.iter().filter(|fact| fact.entity == entity) {
                if let OntologyValue::Entity(value) = &fact.value {
                    if value.starts_with(STRUCTURAL_NODE_PREFIX) && owners.insert(value.clone()) {
                        pending.push(value.clone());
                    }
                }
            }
        }
        self.facts.iter().filter(|fact| owners.contains(&fact.entity)).collect()
    }
}
pub fn bare_c0k(iri: &str) -> String {
    iri.strip_prefix(X0K_NS).map(|local| format!("x0k:{local}")).unwrap_or_else(|| iri.to_string())
}

pub fn full_c0k(bare: &str) -> String {
    bare.strip_prefix("x0k:").map(|local| format!("{X0K_NS}{local}")).unwrap_or_else(|| bare.to_string())
}

pub fn camel_to_snake(camel: &str) -> String {
    let mut out = String::with_capacity(camel.len() + 4);
    for (index, ch) in camel.chars().enumerate() {
        if index > 0 && ch.is_ascii_uppercase() { out.push('_'); }
        out.push(ch.to_ascii_lowercase());
    }
    out
}
/// True for a predicate that states a shape rather than a term. A shape is
/// applied to a document, never imported by a term, so it may name a class
/// from any module — which is why the import-closure check (which walks
/// `subClassOf`, `domain` and `range`) must not see one of these.
pub fn is_shape_predicate(predicate: &str) -> bool {
    predicate == X0K_TARGET_CLASS || predicate == X0K_SUBJECT_CLASS
}

impl OntologyModel {
    /// The module's facts minus its shapes: what its terms mean.
    pub fn term_facts(&self, module_iri: &str) -> Vec<&OntologyFact> {
        self.module_facts(module_iri).into_iter().filter(|fact| !is_shape_predicate(&fact.predicate)).collect()
    }

    /// The module's shapes: what a document must do to satisfy them.
    pub fn shape_facts(&self, module_iri: &str) -> Vec<&OntologyFact> {
        self.module_facts(module_iri).into_iter().filter(|fact| is_shape_predicate(&fact.predicate)).collect()
    }
}
impl OntologyModel {
    pub fn render_module(&self, module: &ModuleRecord) -> String {
        render_view(&self.term_facts(&module.iri), &format!("# Module: {}", module.name))
    }

    /// The module's shape file, or `None` when the module constrains nothing.
    /// A module with no shapes materializes no file rather than an empty one,
    /// so the directory listing answers "which modules constrain anything".
    pub fn render_shapes(&self, module: &ModuleRecord) -> Option<String> {
        let facts = self.shape_facts(&module.iri);
        if facts.is_empty() {
            return None;
        }
        for fact in &facts {
            let structural = matches!(&fact.value, OntologyValue::Entity(value) if value.starts_with(STRUCTURAL_NODE_PREFIX));
            assert!(
                !structural,
                "shape fact {} {} points at a structural node; the native shape form is flat — \
                 a disjunction repeats the fact rather than unioning it, so a shape file holds \
                 no list cells and reading one needs no list walk",
                fact.entity, fact.predicate,
            );
        }
        Some(render_view(&facts, &format!("# Shapes: {}", module.name)))
    }
}

/// The two views differ in one header line and in nothing else.
fn render_view(facts: &[&OntologyFact], subject_line: &str) -> String {
    let labels = module_blank_labels(facts);
    let mut lines: Vec<String> = facts.iter().map(|fact| render_fact(fact, &labels)).collect();
    lines.sort();
    lines.dedup();
    let mut out = format!(
        "# @generated from the concept region of the fact plane. DO NOT AUTHOR HERE.\n\
         # Bootstrap source: this view seeds an empty region exactly once.\n\
         {subject_line}\n\n",
    );
    for line in lines { out.push_str(&line); out.push('\n'); }
    out
}

/// Module-local blank labels for every structural node among `facts`.
fn module_blank_labels(facts: &[&OntologyFact]) -> BTreeMap<String, String> {
    let is_structural = |value: &str| value.starts_with(STRUCTURAL_NODE_PREFIX);
    let mut roots: Vec<(&str, &str, &str)> = facts.iter().filter_map(|fact| match &fact.value {
        OntologyValue::Entity(value) if is_structural(value) && !is_structural(&fact.entity) => {
            Some((fact.entity.as_str(), fact.predicate.as_str(), value.as_str()))
        }
        _ => None,
    }).collect();
    roots.sort();
    roots.dedup();
    let mut labels = BTreeMap::new();
    let assign_component = |root: &str, root_index: usize, labels: &mut BTreeMap<String, String>| {
        let mut queue = std::collections::VecDeque::from([root.to_string()]);
        let mut node_index = 0usize;
        while let Some(node) = queue.pop_front() {
            if labels.contains_key(&node) { continue; }
            labels.insert(node.clone(), format!("b{root_index:04}n{node_index:04}"));
            node_index += 1;
            let mut children: Vec<&str> = facts.iter().filter_map(|fact| match &fact.value {
                OntologyValue::Entity(value) if fact.entity == node && is_structural(value) => Some(value.as_str()),
                _ => None,
            }).collect();
            children.sort();
            children.dedup();
            queue.extend(children.into_iter().map(str::to_string));
        }
    };
    for (root_index, (_, _, root)) in roots.iter().enumerate() {
        assign_component(root, root_index, &mut labels);
    }
    // A structural node no owned term reaches is still labelled, after the
    // rooted ones, so the file never holds an unrendered skolem.
    let mut stray: Vec<&str> = facts.iter().flat_map(|fact| {
        let object = match &fact.value {
            OntologyValue::Entity(value) if is_structural(value) => Some(value.as_str()),
            _ => None,
        };
        is_structural(&fact.entity).then_some(fact.entity.as_str()).into_iter().chain(object)
    }).collect();
    stray.sort();
    stray.dedup();
    let mut next_root = roots.len();
    for node in stray {
        if !labels.contains_key(node) {
            assign_component(node, next_root, &mut labels);
            next_root += 1;
        }
    }
    labels
}

fn render_fact(fact: &OntologyFact, labels: &BTreeMap<String, String>) -> String {
    let subject = render_entity(&fact.entity, labels);
    let predicate = format!("<{}>", escape_iri(&fact.predicate));
    let object = match &fact.value {
        OntologyValue::Entity(value) => render_entity(value, labels),
        OntologyValue::Text(value) => format!("\"{}\"", escape_literal(value)),
    };
    format!("{subject} {predicate} {object} .")
}
fn render_entity(value: &str, labels: &BTreeMap<String, String>) -> String {
    if let Some(local) = value.strip_prefix(STRUCTURAL_NODE_PREFIX) {
        return match labels.get(value) {
            Some(label) => format!("_:{label}"),
            None => format!("_:{}", local.replace(|ch: char| !ch.is_ascii_alphanumeric(), "_")),
        };
    }
    format!("<{}>", escape_iri(value))
}

fn escape_iri(value: &str) -> String {
    value.replace('>', "\\u003E")
}

fn escape_literal(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"), '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"), '\r' => out.push_str("\\r"), '\t' => out.push_str("\\t"),
            ch if ch.is_control() => out.push_str(&format!("\\u{:04X}", ch as u32)),
            ch => out.push(ch),
        }
    }
    out
}
#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    fn bootstrap_model() -> OntologyModel {
        OntologyModel::new(crate::bootstrap_concept_facts())
    }

    #[test]
    fn concept_facts_projection_parity() {
        let model = bootstrap_model();
        let folded_classes: Vec<_> = model.classes().into_iter()
            .map(|class| (class.uri, class.label)).collect();
        let generated_classes: Vec<_> = crate::ONTOLOGY_CLASSES.iter()
            .map(|class| (class.uri.to_string(), class.label.to_string())).collect();
        assert_eq!(folded_classes, generated_classes, "class counts and names differ");

        let folded_predicates: Vec<_> = model.object_properties().into_iter()
            .map(|property| (property.uri, property.domain, property.range)).collect();
        let generated_predicates: Vec<_> = crate::ONTOLOGY_OBJECT_PROPERTIES.iter()
            .map(|property| (
                property.uri.to_string(),
                property.domain.map(str::to_string),
                property.range.map(str::to_string),
            )).collect();
        assert_eq!(folded_predicates, generated_predicates, "predicate counts, names, or shapes differ");

        let folded_edges: Vec<_> = model.decision_edge_predicates().into_iter()
            .map(|(snake, _)| snake).collect();
        let generated_edges: Vec<_> = crate::KNOWN_EDGE_PREDICATES.iter()
            .map(|predicate| predicate.to_string()).collect();
        assert_eq!(folded_edges, generated_edges, "Decision predicate view differs");
    }

    #[test]
    fn concept_facts_root_closes() {
        let model = bootstrap_model();
        let concepts = model.concept_entities();
        let declared: BTreeSet<_> = model.declared_entities().into_iter().collect();
        assert_eq!(concepts, declared, "every declaration must occupy the one Concept level");

        for concept in &concepts {
            let typings = model.facts().iter().filter(|fact| {
                fact.entity == *concept
                    && fact.predicate == RDF_TYPE
                    && fact.value == OntologyValue::Entity(CONCEPT_URI.to_string())
            }).count();
            assert_eq!(typings, 1, "{concept} must have exactly one Concept typing");
        }

        let root_concept_types: BTreeSet<_> = model.facts().iter().filter_map(|fact| {
            match &fact.value {
                OntologyValue::Entity(target)
                    if fact.entity == CONCEPT_URI
                        && fact.predicate == RDF_TYPE
                        && concepts.contains(target) => Some(target.clone()),
                _ => None,
            }
        }).collect();
        assert_eq!(
            root_concept_types,
            BTreeSet::from([CONCEPT_URI.to_string()]),
            "Concept must close on itself with no concept above it",
        );
    }

    #[test]
    fn concept_facts_view_roundtrip() {
        let model = bootstrap_model();
        let modules = model.modules();
        let names: Vec<_> = modules.iter().map(|module| module.name.as_str()).collect();
        assert_eq!(names, crate::MODULES, "folded module set differs from the compiled one");
        for module in &modules {
            let checked = crate::checked_module_file(&module.name)
                .unwrap_or_else(|| panic!("module {} has no checked file", module.name));
            assert_eq!(
                model.render_module(module),
                checked,
                "checked ontology/modules/{}.ttl is not the exact materialized module view",
                module.name,
            );
            // A shape file exists exactly when the module has shapes, so the
            // `Option`s must agree in both directions: a checked file with no
            // shapes behind it is as much a drift as shapes with no file.
            assert_eq!(
                model.render_shapes(module).as_deref(),
                crate::checked_shape_file(&module.name),
                "checked ontology/shapes/{}.ttl is not the exact materialized shape view",
                module.name,
            );
        }
    }

    #[test]
    fn concept_facts_modules_import_in_order() {
        let model = bootstrap_model();
        let order = model.import_order().expect("module imports form a DAG over the set");
        for (index, module) in order.iter().enumerate() {
            for import in &module.imports {
                let position = order.iter().position(|other| &other.iri == import)
                    .unwrap_or_else(|| panic!("{} imports {import}, which is not in the order", module.name));
                assert!(position < index, "{} is ordered before its import {import}", module.name);
            }
        }
        for concept in model.concept_entities() {
            let defining = model.defining_modules(&concept);
            assert_eq!(defining.len(), 1, "{concept} must be defined by exactly one module: {defining:?}");
        }
    }
}
