// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/ontology/views.md — DO NOT EDIT.
//! Fold-derived ontology compatibility views.
//!
//! `KNOWN_EDGE_PREDICATES` and `snake_to_camel` are emitted by
//! `build.rs` from [`concept_facts::OntologyModel`] and re-exported here.
//! `ontology/modules/*.ttl` are the checked bootstrap/materialized views,
//! one per vocabulary module (`x0k:architecture/ontology-modules`): their
//! union seeds an empty concept region, after which the self-typed
//! `x0k:Concept` root in the fact plane is authoritative. `MODULES` names
//! the set, sorted by name; each `pub mod <name>` (`core`, `document`,
//! …) carries that module's `IRI`, `IMPORTS`, and its slice of the tables,
//! and `MODULE_TABLES` indexes those slices by name for code that must
//! not assume which modules a build shipped — a publication compiles a
//! subset, and only `core` is certain to be present.
//!
//! The runtime crate graph never sees `oxttl` — the TTL parser is a
//! build-only dependency, and a consumer only ever sees the generated
//! `&[&str]` constant slices and the `snake_to_camel` match function.
//!
//! The hand-authored vocabularies that spell x0k's own internal
//! subjects live behind the off-by-default `product` feature; a build
//! that does not ask for it gets the fold and its views and nothing
//! else.
//!
//! Snake-case is the wire/frontmatter form on folio/v1 envelopes;
//! camelCase is the URI suffix that appears in the ontology view. The two
//! forms map deterministically by inserting `_` before uppercase
//! letter boundaries (excluding position 0) and lowercasing.

pub mod concept_facts;

#[cfg(feature = "product")]
pub mod admission_grant;
#[cfg(feature = "product")]
pub mod calendar;
#[cfg(feature = "product")]
pub mod declaration;
#[cfg(feature = "product")]
pub mod entry_vocab;
#[cfg(feature = "product")]
pub mod finding_vocab;
#[cfg(feature = "product")]
pub mod proposal_vocab;
#[cfg(feature = "product")]
pub mod settlement;
#[cfg(feature = "product")]
pub mod usage_vocab;

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

/// The `rdfs:label` for a class URI (bare `x0k:` form), or `None` if the
/// URI is not a vocabulary class (e.g. a synthetic UI-only class like
/// `x0k:Ontology` / `x0k:Home` / `x0k:Population`).
pub fn class_label(uri: &str) -> Option<&'static str> {
    ONTOLOGY_CLASSES
        .iter()
        .find(|c| c.uri == uri)
        .map(|c| c.label)
}

/// The resolved `(domain, range)` for an object-property URI (bare `x0k:`
/// form), or `None` if no shipped module declares it as an object
/// property — `x0k:synthesizes`, a UI-only edge no vocabulary declares at
/// all, is the live example. Either component may itself be `None` when
/// the property omits that constraint, which is a different answer
/// entirely: `cites` is a `core` term with neither a domain nor a range,
/// so it resolves to `Some((None, None))` — declared, and constrained
/// nowhere, since a citation's target may be a document in the corpus or
/// one on the web.
pub fn predicate_domain_range(uri: &str) -> Option<(Option<&'static str>, Option<&'static str>)> {
    ONTOLOGY_OBJECT_PROPERTIES
        .iter()
        .find(|p| p.uri == uri)
        .map(|p| (p.domain, p.range))
}

/// The checked `ontology/modules/<name>.ttl` this crate was built from, so
/// round-trip tests compare against the bytes the compiler saw.
pub fn checked_module_file(name: &str) -> Option<&'static str> {
    MODULE_FILES
        .iter()
        .find(|(module, _)| *module == name)
        .map(|(_, contents)| *contents)
}

/// The checked `ontology/shapes/<name>.ttl` this crate was built from, or
/// `None` when the module constrains nothing. Absence is the ordinary case
/// and never a missing file: a shape file exists only where there are shapes.
pub fn checked_shape_file(name: &str) -> Option<&'static str> {
    SHAPE_FILES
        .iter()
        .find(|(module, _)| *module == name)
        .map(|(_, contents)| *contents)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shipped(name: &str) -> bool {
        MODULES.contains(&name)
    }

    #[test]
    fn generated_slice_is_non_empty() {
        if !shipped("document") {
            return;
        }
        assert!(
            !KNOWN_EDGE_PREDICATES.is_empty(),
            "build.rs failed to emit any Decision-domain predicates from \
             ontology/modules/*.ttl; either the parser silently dropped triples \
             or the domain-resolution logic regressed."
        );
    }

    #[test]
    fn every_known_predicate_has_camel_mapping() {
        for snake in KNOWN_EDGE_PREDICATES {
            assert!(
                snake_to_camel(snake).is_some(),
                "KNOWN_EDGE_PREDICATES contains `{snake}` but \
                 snake_to_camel has no mapping for it. The two are emitted \
                 from the same source set in build.rs, so a missing pair \
                 means the codegen regressed."
            );
        }
        // Unknown predicates return None.
        assert_eq!(snake_to_camel("definitely_not_a_predicate"), None);
    }

    /// Predicates the corpus actively uses, by the module that defines them.
    const CANONICAL: &[(&str, &[(&str, &str)])] = &[
        (
            // A predicate whose subject reaches `Decision` through a shape
            // rather than an `rdfs:domain`, which is what `core` residency
            // costs and what clause 8 buys. If this line goes missing the
            // fold has stopped reading the shape half of the T-box union and
            // every decision document's `realizes` edge has gone unrecognised.
            "core",
            &[("realizes", "realizes")],
        ),
        (
            "document",
            &[
                ("supports", "supports"),
                ("refined_by", "refinedBy"),
                ("mentions", "mentions"),
                ("raises", "raises"),
                ("resolves", "resolves"),
                ("implements", "implements"),
                // Placed here by its `x0k:Decision` domain, with its former
                // `Intent` range now a shape
                // (`x0k:architecture/vocabulary-shapes` §3). Before that it
                // sat in `work`, and a `[core, document]` build — what an
                // adopter of the document format takes — could not spell the
                // commonest edge in the corpus.
                ("motivated_by", "motivatedBy"),
                ("published_by", "publishedBy"),
                ("published_for", "publishedFor"),
                // Same treatment, same reason: an `x0k:Decision` domain, and
                // a range unioning `Decision` with `Observation` — a `work`
                // term — that is now a shape.
                ("informed_by", "informedBy"),
                // Declared 2026-09-04 rather than moved: the publication
                // manifest had carried it as a forward-compat edge no module
                // spelled. Domain `Publication`, which subclasses `Decision`,
                // so it lands in the slice; its two admissible targets span
                // `document` and `product` and are a shape.
                ("excludes", "excludes"),
                // Placed here by its `x0k:Decision` domain, with the union of
                // `Decision`, `Techne` and `SoftwareModule` it used to declare
                // as a range now three `x0k:targetClass` facts. That union
                // spans three modules and was the whole reason the term sat in
                // `product` — a build shipping the subject class could not
                // spell the predicate.
                ("constrains", "constrains"),
                // Declared 2026-09-04, the counterpart authored from the
                // constrained end. Domain `Implementation`, which is where
                // every one of the corpus's 95 uses has its subject, so it
                // lands in the slice beside `implements`; range-free like
                // `implements`, with the Architecture expectation a shape.
                ("constrained_by", "constrainedBy"),
            ],
        ),
        (
            "work",
            &[
                ("supersedes", "supersedes"),
                ("superseded_by", "supersededBy"),
            ],
        ),
        (
            "software",
            &[
                ("defines", "defines"),
                ("verified_by", "verifiedBy"),
            ],
        ),
        (
            "product",
            &[
                ("serves", "serves"),
                ("depends_on", "dependsOn"),
            ],
        ),
    ];

    #[test]
    fn canonical_predicates_are_present() {
        // Smoke check: for every shipped module, the predicates the corpus
        // uses from it are emitted, in the module's own table and in the
        // union. Adding a new Decision-domain predicate to a module file is
        // enough to make it appear; removing one of these (other than
        // during a deliberate ontology edit) should fail loudly.
        for (module, predicates) in CANONICAL {
            if !shipped(module) {
                continue;
            }
            let tables = MODULE_TABLES.iter().find(|t| t.name == *module).unwrap();
            for (snake, camel) in *predicates {
                assert!(
                    tables.edge_predicates.contains(snake),
                    "expected canonical predicate `{snake}` in {module}::EDGE_PREDICATES"
                );
                assert!(
                    KNOWN_EDGE_PREDICATES.contains(snake),
                    "expected canonical predicate `{snake}` in KNOWN_EDGE_PREDICATES"
                );
                assert_eq!((tables.snake_to_camel)(snake), Some(*camel));
                assert_eq!(snake_to_camel(snake), Some(*camel));
            }
        }
    }

    #[test]
    fn modules_partition_the_union() {
        // The index and the name list agree; a checked file exists for
        // every module; the set is closed under imports and rooted in
        // `core`.
        let names: Vec<&str> = MODULE_TABLES.iter().map(|t| t.name).collect();
        assert_eq!(names, MODULES);
        assert!(!MODULES.is_empty(), "x0k-ontology built from an empty module set");
        assert!(shipped("core"), "every module set is rooted in core");
        assert_eq!(core::IRI, "https://0k.computer/ontology/core");
        assert!(core::IMPORTS.is_empty());
        for tables in MODULE_TABLES {
            assert!(checked_module_file(tables.name).is_some(), "no checked file for module {}", tables.name);
            assert_eq!(tables.iri, format!("https://0k.computer/ontology/{}", tables.name));
            for import in tables.imports {
                assert!(
                    MODULE_TABLES.iter().any(|t| t.iri == *import),
                    "{} imports {import}, which the build did not ship",
                    tables.name
                );
            }
        }

        // Each term lives in exactly one module and the union is the sum.
        let class_count: usize = MODULE_TABLES.iter().map(|t| t.classes.len()).sum();
        assert_eq!(class_count, ONTOLOGY_CLASSES.len());
        let property_count: usize = MODULE_TABLES.iter().map(|t| t.object_properties.len()).sum();
        assert_eq!(property_count, ONTOLOGY_OBJECT_PROPERTIES.len());
        let edge_count: usize = MODULE_TABLES.iter().map(|t| t.edge_predicates.len()).sum();
        assert_eq!(edge_count, KNOWN_EDGE_PREDICATES.len());

        // Placement follows the ADR's table, for whichever modules are here.
        for (module, class) in [
            ("core", "x0k:Concept"),
            ("document", "x0k:Decision"),
            ("work", "x0k:Intent"),
            ("actor", "x0k:Actor"),
            ("software", "x0k:Affordance"),
            ("product", "x0k:SoftwareModule"),
            ("paracosm", "paracosm:Place"),
        ] {
            if let Some(tables) = MODULE_TABLES.iter().find(|t| t.name == module) {
                assert!(
                    tables.classes.iter().any(|c| c.uri == class),
                    "{module} should define {class}"
                );
            }
        }
        for (module, imports) in [
            ("document", &["core"][..]),
            ("work", &["core", "document"]),
            ("actor", &["core"]),
            ("software", &["core", "document"]),
            ("paracosm", &["core", "work"]),
            ("product", &["actor", "core", "document", "software", "work"]),
        ] {
            if let Some(tables) = MODULE_TABLES.iter().find(|t| t.name == module) {
                let expected: Vec<String> =
                    imports.iter().map(|i| format!("https://0k.computer/ontology/{i}")).collect();
                assert_eq!(tables.imports, expected, "{module} imports");
            }
        }
        if let Some(document) = MODULE_TABLES.iter().find(|t| t.name == "document") {
            assert!(document.edge_predicates.contains(&"supports"));
            // `motivated_by` is `document`'s since the shape extraction, and
            // `depends_on` is not: its domain is a union of four classes that
            // do not join, so clause 8 places it in `core`… which it has not
            // been moved to yet. What it is NOT is document's, which is the
            // property this line is pinning.
            assert_eq!((document.snake_to_camel)("depends_on"), None);
        }
    }
}
