// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/folio/dialog.md — DO NOT EDIT.
use anyhow::Result;
use x0k_folio_dialog::{DialogBackend, QueryRequest};
use x0k_folio_ingest::backend::FactSink;
use x0k_fact_projection::{FactEntry, FactValue};

fn fact(value: FactValue) -> FactEntry {
    FactEntry { entity: "https://example.org/document/one".into(),
        predicate: format!("https://example.org/ontology/{}", "a-long-predicate/".repeat(8)),
        value, cause: Some("identical-content".into()) }
}
fn request(predicate: &str) -> QueryRequest {
    QueryRequest {
        premises: vec![serde_json::json!({
            "assert": { "with": { "value": { "the": predicate, "cardinality": "many" } } },
            "where": { "this": {"?":{"name":"entity"}}, "value": {"?":{"name":"value"}} }
        })],
        select: vec!["entity".into(), "value".into()], ..Default::default()
    }
}
#[tokio::test]
async fn native_values_source_support_update_delete_reopen_and_live_reader() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let path = directory.path().join("database");
    let mut writer = DialogBackend::open(&path)?;
    assert!(DialogBackend::open(&path).is_err());
    let values = vec![
        FactValue::Text("urn:text-is-not-reference".into()), FactValue::EntityRef("urn:reference".into()),
        FactValue::Boolean(true), FactValue::UnsignedInt(u128::MAX), FactValue::SignedInt(i128::MIN),
        FactValue::Float(1.25), FactValue::Bytes(vec![0,255]), FactValue::Record(vec![1,255]),
        FactValue::Symbol("https://other.example/ontology/full-symbol".into()),
    ];
    let facts: Vec<_> = values.iter().cloned().map(fact).collect();
    let batches = vec![(facts[0].entity.clone(), facts.clone())];
    writer.replace_source("/source/a", &batches, &[], "same-content")?;
    writer.replace_source("/source/b", &batches, &[], "same-content")?;
    let reader = DialogBackend::open_reader(&path)?;
    let response = reader.query(request(&facts[0].predicate)).await?;
    assert_eq!(response.rows.len(), values.len());
    for value in &values { assert!(response.rows.iter().any(|row| row.get("value") == Some(value)), "{value:?}"); }
    assert!(response.rows.iter().all(|r| r.get("entity") == Some(&FactValue::EntityRef(facts[0].entity.clone()))));
    writer.replace_source("/source/a", &vec![], &facts, "deleted")?;
    assert_eq!(reader.query(request(&facts[0].predicate)).await?.rows.len(), 9);
    let updated = vec![(facts[0].entity.clone(), vec![fact(FactValue::Text("changed".into()))])];
    writer.replace_source("/source/b", &updated, &facts, "new-revision")?;
    let response = reader.query(request(&facts[0].predicate)).await?;
    assert_eq!(response.rows.len(), 1);
    assert_eq!(response.rows[0]["value"], FactValue::Text("changed".into()));
    // A lost host acknowledgement replays against source state already committed.
    writer.replace_source("/source/b", &updated, &facts, "new-revision")?;
    assert_eq!(reader.query(request(&facts[0].predicate)).await?.rows.len(), 1);
    // Readers never expose a write path.
    let mut read_only = reader.clone();
    assert!(read_only.replace_source("/illegal", &batches, &[], "x").is_err());
    drop(writer);
    // Worker stops after last sending handle disappears; poll lock acquisition,
    // rather than assuming the detached thread has already released the lock.
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
    let mut reopened = loop {
        anyhow::ensure!(std::time::Instant::now() < deadline, "writer lock did not release");
        match DialogBackend::open(&path) {
            Ok(writer) => break writer,
            Err(_) => tokio::time::sleep(std::time::Duration::from_millis(5)).await,
        }
    };
    assert_eq!(reader.query(request(&facts[0].predicate)).await?.rows.len(), 1);
    reopened.replace_source("/source/b", &vec![], &facts, "deleted")?;
    assert!(reader.query(request(&facts[0].predicate)).await?.rows.is_empty());
    Ok(())
}
#[tokio::test]
async fn native_query_limits_and_read_only_missing_directory() -> Result<()> {
    let directory = tempfile::tempdir()?;
    assert!(DialogBackend::open_reader(directory.path().join("missing")).is_err());
    assert!(!directory.path().join("missing").exists());
    let mut writer = DialogBackend::open(directory.path())?;
    let facts: Vec<_> = (0..3).map(|n| fact(FactValue::UnsignedInt(n))).collect();
    writer.replace_source("a", &vec![(facts[0].entity.clone(),facts.clone())], &[], "r")?;
    let mut query = request(&facts[0].predicate);
    query.max_rows = 2;
    let result = writer.query(query.clone()).await?;
    assert_eq!(result.rows.len(), 2); assert!(result.truncated);
    query.max_rows = 0; assert!(writer.query(query).await.is_err());
    Ok(())
}
#[tokio::test]
async fn native_recursive_rules_reach_fixpoint_over_source_facts() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let mut db = DialogBackend::open(directory.path())?;
    let parent = "https://example.org/family/parent";
    let ancestor = "https://example.org/family/ancestor";
    let facts: Vec<_> = [("urn:a","urn:b"),("urn:b","urn:c"),("urn:c","urn:a")].into_iter()
        .map(|(entity,target)| FactEntry { entity:entity.into(),predicate:parent.into(),
            value:FactValue::EntityRef(target.into()),cause:None }).collect();
    db.replace_source("family", &vec![("urn:family".into(),facts)], &[], "revision")?;
    let parent_descriptor = serde_json::json!({"with":{"parent":{"the":parent,"as":"Entity","cardinality":"many"}}});
    let ancestor_descriptor = serde_json::json!({"with":{"ancestor":{"the":ancestor,"as":"Entity","cardinality":"many"}}});
    let base = serde_json::json!({
        "deduce":ancestor_descriptor,
        "when":[{"assert":parent_descriptor,"where":{"this":{"?":{"name":"this"}},"parent":{"?":{"name":"ancestor"}}}}]
    });
    let recursive = serde_json::json!({
        "deduce":ancestor_descriptor,
        "when":[
            {"assert":parent_descriptor,"where":{"this":{"?":{"name":"this"}},"parent":{"?":{"name":"p"}}}},
            {"assert":ancestor_descriptor,"where":{"this":{"?":{"name":"p"}},"ancestor":{"?":{"name":"ancestor"}}}}
        ]
    });
    let query = QueryRequest {
        rules: vec![base,recursive],
        premises:vec![serde_json::json!({"assert":ancestor_descriptor,"where":{
            "this":{"?":{"name":"who"}},"ancestor":{"?":{"name":"relative"}}
        }})],
        select:vec!["who".into(),"relative".into()], ..Default::default()
    };
    let result = db.query(query).await?;
    assert_eq!(result.rows.len(),9);
    assert!(!result.truncated);
    Ok(())
}
#[tokio::test]
async fn empty_store_has_stable_incarnation_and_missing_root_is_not_new_store() -> Result<()> {
    let directory = tempfile::tempdir()?;
    let writer = DialogBackend::open(directory.path())?;
    let reader = DialogBackend::open_reader(directory.path())?;
    assert_eq!(writer.instance_id(), reader.instance_id());
    assert!(reader.query(request("urn:empty")).await?.rows.is_empty());
    // Keep marker but remove the published root. A checkpoint bound to the old
    // incarnation must never be accepted as acknowledgement of an empty store.
    let root = dialog_artifacts::make_reference(b"folio-v1");
    let filename = root.iter().map(|b| format!("{b:02x}")).collect::<String>();
    std::fs::remove_file(directory.path().join(filename))?;
    assert!(DialogBackend::open_reader(directory.path()).is_err());
    assert!(reader.query(request("urn:empty")).await.is_err());
    Ok(())
}
