// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/icon/validate.md — DO NOT EDIT.
//! Checking a parsed declaration against the icon profile.
//!
//! [`validate`] reads an [`Icon`] against every refusal rule of
//! `x0k:design/icon-profile` § "What the checker refuses" and returns
//! either an [`Accepted`] icon — the same icon, its grid known, the type
//! the binder and emitter take — or every [`Defect`] found, each naming
//! its [`Rule`] and the element that broke it. Nothing is repaired: a
//! declaration is what its author wrote. [`one_per_grid`] is the one
//! rule that spans declarations, for the section reader that holds
//! several.

use std::fmt;
use std::ops::Deref;

use crate::parse::{Element, Grid, Icon, Paint, PathCommand, Role, Shape, Transform};

use crate::emit::num;

/// The profile's refusal rules, in the design's numbering
/// (`x0k:design/icon-profile` § "What the checker refuses").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Rule {
    NotOneRoot,
    OffGridViewBox,
    UnknownElement,
    UnknownAttribute,
    LiteralPaint,
    PaperAsStroke,
    OffRegisterStroke,
    OffProfileDash,
    RelativeOrUnknownPathCommand,
    OffTheHalfUnit,
    OutsideTheSafeArea,
    OverBudget,
    TransformNotATranslation,
    NothingPainted,
    TwoIconsOnOneGrid,
}

impl Rule {
    /// The rule's number in the design's list.
    pub fn number(self) -> u8 {
        self as u8 + 1
    }

    /// The design's title for the rule.
    pub fn title(self) -> &'static str {
        match self {
            Rule::NotOneRoot => "not one root",
            Rule::OffGridViewBox => "off-grid viewBox",
            Rule::UnknownElement => "unknown element",
            Rule::UnknownAttribute => "unknown attribute",
            Rule::LiteralPaint => "a literal paint",
            Rule::PaperAsStroke => "paper as a stroke",
            Rule::OffRegisterStroke => "off-register stroke",
            Rule::OffProfileDash => "off-profile dash",
            Rule::RelativeOrUnknownPathCommand => "relative or unknown path command",
            Rule::OffTheHalfUnit => "off the half-unit",
            Rule::OutsideTheSafeArea => "outside the safe area",
            Rule::OverBudget => "over budget",
            Rule::TransformNotATranslation => "a transform that is not a translation",
            Rule::NothingPainted => "nothing painted",
            Rule::TwoIconsOnOneGrid => "two icons on one grid",
        }
    }
}

/// The element a defect names: its document-order ordinal (0 is the
/// root) and its tag.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ElementRef {
    pub ordinal: usize,
    pub tag: String,
}

impl ElementRef {
    fn root() -> ElementRef {
        ElementRef { ordinal: 0, tag: "svg".to_string() }
    }

    fn of(el: &Element) -> ElementRef {
        ElementRef { ordinal: el.ordinal, tag: el.tag().to_string() }
    }
}

/// One broken rule: which, where, and what was written there.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Defect {
    pub rule: Rule,
    pub element: ElementRef,
    pub detail: String,
}

impl fmt::Display for Defect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "rule {} ({}): {} #{} — {}",
            self.rule.number(),
            self.rule.title(),
            self.element.tag,
            self.element.ordinal,
            self.detail
        )
    }
}

/// An icon the checker accepted, with its grid. The only way to obtain
/// one is [`validate`]; the binder and emitter take nothing else.
#[derive(Debug, Clone, PartialEq)]
pub struct Accepted {
    icon: Icon,
    grid: Grid,
}

impl Accepted {
    /// The grid the icon is drawn on.
    pub fn grid(&self) -> Grid {
        self.grid
    }

    /// The icon, unwrapped.
    pub fn into_icon(self) -> Icon {
        self.icon
    }
}

impl Deref for Accepted {
    type Target = Icon;
    fn deref(&self) -> &Icon {
        &self.icon
    }
}

/// Check a parsed icon against every profile rule. `Ok` is the icon,
/// accepted; `Err` is every defect found, in document order, the
/// whole-drawing rules last.
pub fn validate(icon: Icon) -> Result<Accepted, Vec<Defect>> {
    let mut defects = Vec::new();
    check_root(&icon, &mut defects);
    let grid = icon.grid();
    let mut walk = Walk { grid, defects, painted: false };
    let inherited = Inherited { fill: None, stroke: None, offset: (0.0, 0.0), parent: "svg" };
    for el in &icon.children {
        walk.element(el, &inherited);
    }
    if let Some(grid) = grid {
        walk.budget(&icon, grid);
    }
    if !walk.painted {
        walk.report(Rule::NothingPainted, ElementRef::root(), "no element carries a visible paint");
    }
    match (grid, walk.defects.is_empty()) {
        (Some(grid), true) => Ok(Accepted { icon, grid }),
        _ => Err(walk.defects),
    }
}

fn check_root(icon: &Icon, defects: &mut Vec<Defect>) {
    let root = ElementRef { ordinal: 0, tag: icon.root_tag.clone() };
    if icon.root_tag != "svg" {
        defects.push(Defect {
            rule: Rule::NotOneRoot,
            element: root.clone(),
            detail: format!("the root is `<{}>`, not `<svg>`", icon.root_tag),
        });
    }
    for name in &icon.root_extra {
        defects.push(Defect {
            rule: Rule::NotOneRoot,
            element: root.clone(),
            detail: format!("the root carries `{name}`; only `viewBox` and `xmlns` are admitted"),
        });
    }
    if icon.grid().is_none() {
        let written = match icon.view_box {
            Some(vb) => format!("viewBox=\"{}\"", vb.map(num).join(" ")),
            None => "no viewBox".to_string(),
        };
        defects.push(Defect {
            rule: Rule::OffGridViewBox,
            element: root,
            detail: format!("{written}; the grids are `0 0 16 16` and `0 0 24 24`"),
        });
    }
}

struct Walk {
    grid: Option<Grid>,
    defects: Vec<Defect>,
    painted: bool,
}

struct Inherited<'a> {
    fill: Option<&'a Paint>,
    stroke: Option<&'a Paint>,
    offset: (f64, f64),
    parent: &'a str,
}

impl Walk {
    fn report(&mut self, rule: Rule, element: ElementRef, detail: impl Into<String>) {
        self.defects.push(Defect { rule, element, detail: detail.into() });
    }
}

impl Walk {
    fn element(&mut self, el: &Element, inherited: &Inherited<'_>) {
        let at = ElementRef::of(el);
        if let Shape::Foreign(what) = &el.shape {
            self.report(Rule::UnknownElement, at, format!("`{what}` is not in the vocabulary"));
            return;
        }
        if inherited.parent != "svg" && inherited.parent != "g" {
            let detail = format!("`{}` inside a `{}`", el.tag(), inherited.parent);
            self.report(Rule::UnknownElement, at.clone(), detail);
        }
        self.attributes(el, &at);
        self.paints(el, &at);
        self.stroke(el, &at);
        self.path_commands(el, &at);
        let offset = self.transform(el, &at, inherited.offset);
        self.geometry(el, &at, offset);
        let below = Inherited {
            fill: el.fill.as_ref().or(inherited.fill),
            stroke: el.stroke.as_ref().or(inherited.stroke),
            offset,
            parent: el.tag(),
        };
        self.painted |= is_painted(el, &below);
        for child in &el.children {
            self.element(child, &below);
        }
    }
}

impl Walk {
    fn attributes(&mut self, el: &Element, at: &ElementRef) {
        for name in &el.unknown_attrs {
            let detail = format!("`{name}` is not admitted on `{}`", el.tag());
            self.report(Rule::UnknownAttribute, at.clone(), detail);
        }
    }
}

impl Walk {
    fn paints(&mut self, el: &Element, at: &ElementRef) {
        for (attr, paint) in [("fill", &el.fill), ("stroke", &el.stroke)] {
            if let Some(Paint::Literal(value)) = paint {
                let detail = format!("{attr}=\"{value}\"; a paint is ink, line, paper, accent or none");
                self.report(Rule::LiteralPaint, at.clone(), detail);
            }
        }
        if el.stroke == Some(Paint::Role(Role::Paper)) {
            self.report(Rule::PaperAsStroke, at.clone(), "stroke=\"paper\"; paper is a fill only");
        }
    }
}

impl Walk {
    fn stroke(&mut self, el: &Element, at: &ElementRef) {
        if let (Some(width), Some(grid)) = (el.stroke_width, self.grid) {
            if width != grid.regular() && width != grid.bold() {
                let detail = format!(
                    "stroke-width=\"{}\"; the register is {} (regular) and {} (bold)",
                    num(width),
                    num(grid.regular()),
                    num(grid.bold())
                );
                self.report(Rule::OffRegisterStroke, at.clone(), detail);
            }
        }
        if let Some(dash) = &el.dasharray {
            if dash != &[1.0, 2.0] {
                let written = dash.iter().map(|v| num(*v)).collect::<Vec<_>>().join(" ");
                let detail = format!("stroke-dasharray=\"{written}\"; the one dash is `1 2`");
                self.report(Rule::OffProfileDash, at.clone(), detail);
            }
        }
    }
}

impl Walk {
    fn path_commands(&mut self, el: &Element, at: &ElementRef) {
        let Shape::Path { d, .. } = &el.shape else { return };
        for command in d {
            if let PathCommand::Unknown(letter) = command {
                let detail = format!("`{letter}` in d; commands are absolute M L H V C Q A Z");
                self.report(Rule::RelativeOrUnknownPathCommand, at.clone(), detail);
            }
        }
    }
}

impl Walk {
    fn transform(&mut self, el: &Element, at: &ElementRef, offset: (f64, f64)) -> (f64, f64) {
        match &el.transform {
            None => offset,
            Some(Transform::Other(text)) => {
                let detail = format!("transform=\"{text}\"; only `translate(x y)` is admitted");
                self.report(Rule::TransformNotATranslation, at.clone(), detail);
                offset
            }
            Some(Transform::Translate(dx, dy)) => {
                if el.tag() != "g" {
                    let detail = format!("a transform on `{}`; only a `g` may carry one", el.tag());
                    self.report(Rule::TransformNotATranslation, at.clone(), detail);
                }
                for (name, v) in [("translate x", *dx), ("translate y", *dy)] {
                    self.half_unit(at, name, v);
                }
                (offset.0 + dx, offset.1 + dy)
            }
        }
    }
}

impl Walk {
    fn geometry(&mut self, el: &Element, at: &ElementRef, offset: (f64, f64)) {
        let (values, points) = geometry_of(&el.shape);
        for (name, v) in values {
            self.half_unit(at, name, v);
        }
        for (name, (x, y)) in points {
            self.safe_area(at, name, (x + offset.0, y + offset.1));
        }
    }

    fn half_unit(&mut self, at: &ElementRef, name: &str, v: f64) {
        if (v * 2.0).fract() != 0.0 {
            let detail = format!("{name} = {}; coordinates sit on multiples of 0.5", num(v));
            self.report(Rule::OffTheHalfUnit, at.clone(), detail);
        }
    }

    fn safe_area(&mut self, at: &ElementRef, name: &str, (x, y): (f64, f64)) {
        let Some(grid) = self.grid else { return };
        let (lo, hi) = grid.safe_area();
        if !(lo..=hi).contains(&x) || !(lo..=hi).contains(&y) {
            let detail = format!(
                "{name} at ({} {}) leaves the safe area {} … {}",
                num(x),
                num(y),
                num(lo),
                num(hi)
            );
            self.report(Rule::OutsideTheSafeArea, at.clone(), detail);
        }
    }
}

type Values = Vec<(&'static str, f64)>;
type Points = Vec<(&'static str, (f64, f64))>;

fn geometry_of(shape: &Shape) -> (Values, Points) {
    let mut values = Vec::new();
    let mut points = Vec::new();
    match shape {
        Shape::Group | Shape::Foreign(_) => {}
        Shape::Line { x1, y1, x2, y2 } => {
            values.extend([("x1", *x1), ("y1", *y1), ("x2", *x2), ("y2", *y2)]);
            points.extend([("x1 y1", (*x1, *y1)), ("x2 y2", (*x2, *y2))]);
        }
        Shape::Circle { cx, cy, r } => {
            values.extend([("cx", *cx), ("cy", *cy), ("r", *r)]);
            points.extend([
                ("left extreme", (cx - r, *cy)),
                ("right extreme", (cx + r, *cy)),
                ("top extreme", (*cx, cy - r)),
                ("bottom extreme", (*cx, cy + r)),
            ]);
        }
        Shape::Rect { x, y, width, height, rx } => {
            values.extend([("x", *x), ("y", *y), ("width", *width), ("height", *height)]);
            values.extend(rx.map(|rx| ("rx", rx)));
            points.extend([("corner", (*x, *y)), ("far corner", (x + width, y + height))]);
        }
        Shape::Polyline { points: pts } => {
            for (x, y) in pts {
                values.extend([("point x", *x), ("point y", *y)]);
                points.push(("point", (*x, *y)));
            }
        }
        Shape::Path { d, .. } => path_geometry(d, &mut values, &mut points),
    }
    (values, points)
}

fn path_geometry(d: &[PathCommand], values: &mut Values, points: &mut Points) {
    let mut current = (0.0, 0.0);
    for command in d {
        match command {
            PathCommand::MoveTo(x, y) | PathCommand::LineTo(x, y) => {
                values.extend([("x", *x), ("y", *y)]);
                current = (*x, *y);
                points.push(("point", current));
            }
            PathCommand::Horizontal(x) => {
                values.push(("x", *x));
                current.0 = *x;
                points.push(("point", current));
            }
            PathCommand::Vertical(y) => {
                values.push(("y", *y));
                current.1 = *y;
                points.push(("point", current));
            }
            PathCommand::Cubic([x1, y1, x2, y2, x, y]) => {
                values.extend([("x1", *x1), ("y1", *y1), ("x2", *x2), ("y2", *y2), ("x", *x), ("y", *y)]);
                points.extend([("control point", (*x1, *y1)), ("control point", (*x2, *y2))]);
                current = (*x, *y);
                points.push(("point", current));
            }
            PathCommand::Quadratic([x1, y1, x, y]) => {
                values.extend([("x1", *x1), ("y1", *y1), ("x", *x), ("y", *y)]);
                points.push(("control point", (*x1, *y1)));
                current = (*x, *y);
                points.push(("point", current));
            }
            PathCommand::Arc { rx, ry, x, y, .. } => {
                values.extend([("rx", *rx), ("ry", *ry), ("x", *x), ("y", *y)]);
                current = (*x, *y);
                points.push(("point", current));
            }
            PathCommand::Close | PathCommand::Unknown(_) => {}
        }
    }
}

impl Walk {
    fn budget(&mut self, icon: &Icon, grid: Grid) {
        let commands = icon.command_count();
        if commands > grid.command_budget() {
            let detail = format!("{commands} drawing commands; the budget is {}", grid.command_budget());
            self.report(Rule::OverBudget, ElementRef::root(), detail);
        }
        let elements = icon.element_count();
        if elements > grid.element_budget() {
            let detail = format!("{elements} elements; the budget is {}", grid.element_budget());
            self.report(Rule::OverBudget, ElementRef::root(), detail);
        }
    }
}

fn is_painted(el: &Element, effective: &Inherited<'_>) -> bool {
    let visible = |paint: Option<&Paint>| matches!(paint, Some(Paint::Role(_) | Paint::Literal(_)));
    match &el.shape {
        Shape::Group | Shape::Foreign(_) => false,
        Shape::Line { .. } | Shape::Polyline { .. } => visible(effective.stroke),
        _ => visible(effective.fill) || visible(effective.stroke),
    }
}

/// Rule 15 over the icons of one section: a second icon on a grid one
/// already occupies is a defect naming the later icon by its position in
/// the slice.
pub fn one_per_grid(icons: &[&Accepted]) -> Vec<Defect> {
    let mut seen: Vec<Grid> = Vec::new();
    let mut defects = Vec::new();
    for (i, icon) in icons.iter().enumerate() {
        if seen.contains(&icon.grid()) {
            defects.push(Defect {
                rule: Rule::TwoIconsOnOneGrid,
                element: ElementRef::root(),
                detail: format!("icon {} of the section is a second on the {} grid", i + 1, num(icon.grid().size())),
            });
        }
        seen.push(icon.grid());
    }
    defects
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fixtures;
    use crate::parse::parse;

    fn refusals(svg: &str) -> Vec<Rule> {
        match validate(parse(svg).unwrap()) {
            Ok(_) => Vec::new(),
            Err(defects) => defects.into_iter().map(|d| d.rule).collect(),
        }
    }

    fn wrap(body: &str) -> String {
        format!("<svg viewBox=\"0 0 16 16\">{body}</svg>")
    }

    const RING: &str = r#"<circle cx="8" cy="8" r="6" fill="none" stroke="ink" stroke-width="1.5"/>"#;

    #[test]
    fn the_tangle_icon_is_accepted() {
        let accepted = validate(parse(fixtures::TANGLE).unwrap()).unwrap();
        assert_eq!(accepted.grid(), Grid::Sixteen);
        assert_eq!(accepted.command_count(), 16);
    }

    #[test]
    fn a_literal_colour_is_refused_by_rule_5() {
        let svg = fixtures::TANGLE.replace(r#"stroke="ink" stroke-width="1.5""#, r##"stroke="#111111" stroke-width="1.5""##);
        let defects = validate(parse(&svg).unwrap()).unwrap_err();
        assert_eq!(defects.len(), 1);
        assert_eq!(defects[0].rule, Rule::LiteralPaint);
        assert_eq!(defects[0].element, ElementRef { ordinal: 4, tag: "rect".to_string() });
        assert_eq!(
            defects[0].to_string(),
            "rule 5 (a literal paint): rect #4 — stroke=\"#111111\"; a paint is ink, line, paper, accent or none"
        );
    }

    #[test]
    fn a_corner_past_the_safe_area_is_refused_by_rule_11() {
        let svg = fixtures::TANGLE.replace(r#"x="6.5" y="9.5" width="7""#, r#"x="8.5" y="9.5" width="7""#);
        let defects = validate(parse(&svg).unwrap()).unwrap_err();
        assert_eq!(defects.len(), 1);
        assert_eq!(defects[0].rule, Rule::OutsideTheSafeArea);
        assert_eq!(defects[0].element.ordinal, 4);
        assert!(defects[0].detail.starts_with("far corner at (15.5 13.5)"), "{}", defects[0].detail);
    }

    #[test]
    fn a_page_over_budget_is_refused_by_rule_12() {
        let svg = fixtures::TANGLE.replace(
            r#"d="M4.5 6.5 H9 M4.5 8.5 H7""#,
            r#"d="M4.5 6.5 H9 M4.5 8.5 H7 M4.5 10.5 H7 M4.5 11 H7 M4.5 12 H7 M4.5 13 H7 M4.5 14 H7""#,
        );
        let defects = validate(parse(&svg).unwrap()).unwrap_err();
        assert_eq!(defects.len(), 1);
        assert_eq!(defects[0].rule, Rule::OverBudget);
        assert_eq!(defects[0].element.ordinal, 0);
        assert_eq!(defects[0].detail, "26 drawing commands; the budget is 24");
    }

    #[test]
    fn every_broken_rule_is_reported_in_one_pass() {
        let svg = fixtures::TANGLE
            .replace(r#"stroke="ink" stroke-width="1.5""#, r##"stroke="#111111" stroke-width="1.5""##)
            .replace(r#"x="6.5" y="9.5" width="7""#, r#"x="8.5" y="9.5" width="7""#)
            .replace(
                r#"d="M4.5 6.5 H9 M4.5 8.5 H7""#,
                r#"d="M4.5 6.5 H9 M4.5 8.5 H7 M4.5 10.5 H7 M4.5 11 H7 M4.5 12 H7 M4.5 13 H7 M4.5 14 H7""#,
            );
        assert_eq!(refusals(&svg), vec![Rule::LiteralPaint, Rule::OutsideTheSafeArea, Rule::OverBudget]);
    }

    #[test]
    fn each_rule_has_a_drawing_that_breaks_only_it() {
        let cases: Vec<(String, Rule)> = vec![
            (format!("<g viewBox=\"0 0 16 16\">{RING}</g>"), Rule::NotOneRoot),
            (format!("<svg viewBox=\"0 0 16 16\" width=\"16\">{RING}</svg>"), Rule::NotOneRoot),
            (format!("<svg viewBox=\"0 0 20 20\">{RING}</svg>"), Rule::OffGridViewBox),
            (wrap(&format!("{RING}<text x=\"2\" y=\"2\">a</text>")), Rule::UnknownElement),
            (wrap(&format!("{RING}<!-- a comment -->")), Rule::UnknownElement),
            (wrap(&RING.replace("fill=\"none\"", "fill=\"none\" id=\"ring\"")), Rule::UnknownAttribute),
            (wrap(&RING.replace("stroke=\"ink\"", "stroke=\"currentColor\"")), Rule::LiteralPaint),
            (wrap(&RING.replace("stroke=\"ink\"", "stroke=\"paper\"")), Rule::PaperAsStroke),
            (wrap(&RING.replace("stroke-width=\"1.5\"", "stroke-width=\"2\"")), Rule::OffRegisterStroke),
            (wrap(&RING.replace("stroke-width=\"1.5\"", "stroke-width=\"1\" stroke-dasharray=\"2 2\"")), Rule::OffProfileDash),
            (wrap(r#"<path d="M4 4 l8 8" fill="none" stroke="ink" stroke-width="1"/>"#), Rule::RelativeOrUnknownPathCommand),
            (wrap(&RING.replace("r=\"6\"", "r=\"5.25\"")), Rule::OffTheHalfUnit),
            (wrap(&RING.replace("cx=\"8\"", "cx=\"9.5\"")), Rule::OutsideTheSafeArea),
            (wrap(&RING.repeat(9)), Rule::OverBudget),
            (wrap(&format!("<g transform=\"rotate(45)\">{RING}</g>")), Rule::TransformNotATranslation),
            (wrap(&RING.replace("<circle", "<circle transform=\"translate(1 1)\"")), Rule::TransformNotATranslation),
            (wrap(&RING.replace("stroke=\"ink\"", "stroke=\"none\"")), Rule::NothingPainted),
        ];
        for (svg, rule) in cases {
            assert_eq!(refusals(&svg), vec![rule], "{svg}");
        }
    }

    #[test]
    fn a_translation_moves_the_safe_area_check_with_its_subtree() {
        let inside = wrap(&format!("<g transform=\"translate(1 1)\">{}</g>", RING.replace("r=\"6\"", "r=\"5\"").replace("cx=\"8\" cy=\"8\"", "cx=\"7\" cy=\"7\"")));
        assert_eq!(refusals(&inside), vec![]);
        let outside = wrap(&format!("<g transform=\"translate(2 2)\">{RING}</g>"));
        assert_eq!(refusals(&outside), vec![Rule::OutsideTheSafeArea, Rule::OutsideTheSafeArea]);
    }

    #[test]
    fn a_paint_inherited_from_a_group_counts_as_painted() {
        let svg = wrap(r#"<g stroke="ink" stroke-width="1.5"><circle cx="8" cy="8" r="6"/></g>"#);
        assert_eq!(refusals(&svg), vec![]);
    }

    #[test]
    fn a_second_icon_on_one_grid_is_refused_by_rule_15() {
        let a = validate(parse(fixtures::TANGLE).unwrap()).unwrap();
        let b = validate(parse(fixtures::WEAVE).unwrap()).unwrap();
        let defects = one_per_grid(&[&a, &b]);
        assert_eq!(defects.len(), 1);
        assert_eq!(defects[0].rule, Rule::TwoIconsOnOneGrid);
        assert_eq!(one_per_grid(&[&a]), vec![]);
    }
}
