// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/folio/dialog.md — DO NOT EDIT.
use std::{collections::{BTreeMap, BTreeSet}, path::Path};
use anyhow::{Result, Context};
use dialog_artifacts::{Artifact, ArtifactSelector, ArtifactStoreMut, Artifacts, Entity, Instruction, Value};
use futures_util::TryStreamExt;
use x0k_fact_projection::{FactEntry, FactValue, payload::FactPayload};
use x0k_folio_ingest::backend::FactBatches;
use crate::storage::DurableStorage;

pub(crate) struct Database {
    pub(crate) store: Artifacts<DurableStorage>,
    pub(crate) storage: DurableStorage,
    pub(crate) read_only: bool,
    pub(crate) instance_id: String,
    marker_path: std::path::PathBuf,
}
fn decode_marker(bytes: &[u8]) -> Result<String> {
    let marker: serde_json::Value = serde_json::from_slice(bytes)?;
    anyhow::ensure!(marker.get("version").and_then(|v| v.as_u64()) == Some(1), "unsupported database format");
    let id = marker.get("instance_id").and_then(|v| v.as_str()).context("missing database incarnation")?;
    uuid::Uuid::parse_str(id)?;
    Ok(id.into())
}
pub(crate) fn digest(bytes: &[u8]) -> String { blake3::hash(bytes).to_hex().to_string() }
pub(crate) fn relation(full: &str) -> String { format!("f/p{}", &digest(full.as_bytes())[..56]) }
fn identity(kind: &str, bytes: &[u8]) -> Result<Entity> {
    Ok(format!("urn:folio:{kind}:{}", digest(bytes)).parse()?)
}
fn artifact(entity: Entity, predicate: &str, value: Value) -> Result<Artifact> {
    Ok(Artifact { of: entity, the: predicate.parse()?, is: value, cause: None })
}
fn normalized(fact: &FactEntry) -> FactEntry {
    let mut fact = fact.clone();
    fact.cause = None;
    fact
}
impl Database {
    pub(crate) async fn open(path: &Path, read_only: bool) -> Result<Self> {
        let storage = DurableStorage::open(path, read_only)?;
        use dialog_storage::StorageBackend;
        let marker_path = path.canonicalize()?.join("store.json");
        let mut store = Self::open_store(&storage, read_only).await?;
        let instance_id = match std::fs::read(&marker_path) {
            Ok(bytes) => decode_marker(&bytes)?,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                anyhow::ensure!(!read_only, "database instance marker is missing");
                anyhow::ensure!(storage.get(&dialog_artifacts::make_reference(b"folio-v1")).await?.is_none(),
                    "database has root but no instance marker; rebuild into a fresh directory");
                store.commit(futures_util::stream::empty()).await?;
                let id = uuid::Uuid::new_v4().to_string();
                let bytes = serde_json::to_vec(&serde_json::json!({"version":1,"instance_id":id}))?;
                use std::io::Write;
                let mut marker = tempfile::NamedTempFile::new_in(marker_path.parent().context("marker parent")?)?;
                marker.write_all(&bytes)?;
                marker.as_file().sync_all()?;
                marker.persist(&marker_path)?;
                std::fs::File::open(marker_path.parent().context("marker parent")?)?.sync_all()?;
                id
            }
            Err(error) => return Err(error.into()),
        };
        // A previously initialized store must never become an empty store.
        anyhow::ensure!(storage.get(&dialog_artifacts::make_reference(b"folio-v1")).await?.is_some(),
            "initialized database root is missing; rebuild into a fresh directory");
        Ok(Self { store, storage, read_only, instance_id, marker_path })
    }
    pub(crate) fn check_instance(&self) -> Result<()> {
        anyhow::ensure!(decode_marker(&std::fs::read(&self.marker_path)?)? == self.instance_id,
            "database incarnation changed while open");
        Ok(())
    }
    pub(crate) async fn open_store(storage: &DurableStorage, require_root: bool) -> Result<Artifacts<DurableStorage>> {
        use dialog_storage::StorageBackend;
        let root = storage.get(&dialog_artifacts::make_reference(b"folio-v1")).await?;
        anyhow::ensure!(!require_root || root.is_some(), "database has no committed root");
        if let Some(bytes) = root {
            anyhow::ensure!(bytes.len() == 32, "invalid database root pointer");
            if bytes != dialog_artifacts::NULL_REVISION_HASH {
                let hash: [u8;32] = bytes.try_into().map_err(|_| anyhow::anyhow!("invalid root length"))?;
                anyhow::ensure!(storage.get(&hash).await?.is_some(), "database root block is missing");
            }
        }
        Ok(Artifacts::open("folio-v1".into(), storage.clone()).await?)
    }
    pub(crate) async fn values(&self, entity: &Entity, predicate: &str) -> Result<Vec<Value>> {
        let selector = ArtifactSelector::new().of(entity.clone()).the(predicate.parse()?);
        Ok(self.store.select(selector).and_then(|a| async move { Ok(a.to_owned()?.is) }).try_collect().await?)
    }
    async fn check_identity(&self, entity: &Entity, predicate: &str, expected: &Value) -> Result<()> {
        let values = self.values(entity, predicate).await?;
        anyhow::ensure!(values.iter().all(|v| v == expected), "stored identity collision or corruption at {entity}");
        Ok(())
    }
    async fn dictionary(&self, full: &str, instructions: &mut Vec<Instruction>) -> Result<()> {
        let short = relation(full);
        let key: Entity = format!("urn:folio:predicate:{short}").parse()?;
        let value = Value::String(full.into());
        self.check_identity(&key, "folio/predicate", &value).await?;
        instructions.push(Instruction::Assert(artifact(key, "folio/predicate", value)?));
        Ok(())
    }
    pub(crate) async fn full_relation(&self, short: &str) -> Result<String> {
        let key: Entity = format!("urn:folio:predicate:{short}").parse()?;
        let values = self.values(&key, "folio/predicate").await?;
        match values.as_slice() {
            [Value::String(full)] if relation(full) == short => Ok(full.clone()),
            _ => anyhow::bail!("missing or corrupt predicate dictionary for {short}"),
        }
    }
    fn visible(&self, fact: &FactEntry) -> Result<Artifact> {
        let value = match &fact.value {
            FactValue::Text(x) => Value::String(x.clone()),
            FactValue::EntityRef(x) => Value::Entity(x.parse()?),
            FactValue::Boolean(x) => Value::Boolean(*x),
            FactValue::UnsignedInt(x) => Value::UnsignedInt(*x),
            FactValue::SignedInt(x) => Value::SignedInt(*x),
            FactValue::Float(x) => Value::Float(*x),
            FactValue::Bytes(x) => Value::Bytes(x.clone()),
            FactValue::Record(x) => Value::Record(x.clone()),
            FactValue::Symbol(x) => Value::Symbol(relation(x).parse()?),
            FactValue::Retracted(_) => anyhow::bail!("source projection must contain current facts, not retraction markers"),
        };
        artifact(fact.entity.parse()?, &relation(&fact.predicate), value)
    }
    /// Persist support changes and visible facts under one published root.
    pub(crate) async fn replace(&mut self, source: &str, batches: &FactBatches) -> Result<usize> {
        anyhow::ensure!(!self.read_only, "read-only database");
        self.check_instance()?;
        let source_id = identity("source", source.as_bytes())?;
        let source_value = Value::String(source.into());
        self.check_identity(&source_id, "folio/source", &source_value).await?;
        let mut old = BTreeMap::new();
        for value in self.values(&source_id, "folio/contribution").await? {
            let Value::Bytes(bytes) = value else { anyhow::bail!("invalid source contribution"); };
            let fact = FactPayload::from_bytes(&bytes)?.into_fact();
            anyhow::ensure!(FactPayload::from_fact(&normalized(&fact)).to_bytes() == bytes, "noncanonical source contribution");
            old.insert(bytes, fact);
        }
        let mut desired = BTreeMap::new();
        for (_, facts) in batches {
            for fact in facts {
                let fact = normalized(fact);
                anyhow::ensure!(!matches!(fact.value, FactValue::Retracted(_)), "retraction marker in desired source");
                desired.insert(FactPayload::from_fact(&fact).to_bytes(), fact);
            }
        }
        let mut instructions = vec![Instruction::Assert(artifact(source_id.clone(), "folio/source", source_value)?)];
        let cells: BTreeSet<_> = old.keys().chain(desired.keys()).cloned().collect();
        let mut pending_cells = BTreeMap::new();
        let mut predicates = BTreeMap::new();
        for (bytes, fact) in old.iter().chain(desired.iter()) {
            let cell = digest(bytes);
            if let Some(previous) = pending_cells.insert(cell, bytes) {
                anyhow::ensure!(previous == bytes, "fact collision within pending transaction");
            }
            let mut names = vec![&fact.predicate];
            if let FactValue::Symbol(symbol) = &fact.value { names.push(symbol); }
            for full in names {
                if let Some(previous) = predicates.insert(relation(full), full) {
                    anyhow::ensure!(previous == full, "predicate collision within pending transaction");
                }
            }
        }
        for full in predicates.values() { self.dictionary(full, &mut instructions).await?; }
        let mut touched = 0;
        for bytes in cells {
            let fact = desired.get(&bytes).or_else(|| old.get(&bytes)).context("missing fact")?;
            let cell = identity("fact", &bytes)?;
            let encoded = Value::Bytes(bytes.clone());
            self.check_identity(&cell, "folio/fact", &encoded).await?;
            let support = artifact(cell.clone(), "folio/support", Value::Entity(source_id.clone()))?;
            let contribution = artifact(source_id.clone(), "folio/contribution", encoded.clone())?;
            let visible = self.visible(fact)?;
            if desired.contains_key(&bytes) {
                instructions.push(Instruction::Assert(artifact(cell, "folio/fact", encoded)?));
                instructions.push(Instruction::Assert(support));
                instructions.push(Instruction::Assert(contribution));
                instructions.push(Instruction::Assert(visible));
            } else {
                let others = self.values(&cell, "folio/support").await?;
                anyhow::ensure!(others.iter().all(|x| matches!(x, Value::Entity(_))), "invalid source support");
                if !others.iter().any(|x| x != &Value::Entity(source_id.clone())) {
                    instructions.push(Instruction::Retract(visible));
                }
                instructions.push(Instruction::Retract(support));
                instructions.push(Instruction::Retract(contribution));
            }
            touched += 1;
        }
        // Failed publication is retried from durable source contributions; never
        // infer ownership from revision causes or a host's previous projection.
        self.store.commit(futures_util::stream::iter(instructions)).await?;
        Ok(touched)
    }
    pub(crate) async fn value(&self, value: Value) -> Result<FactValue> {
        Ok(match value {
            Value::String(x) => FactValue::Text(x),
            Value::Entity(x) => FactValue::EntityRef(x.to_string()),
            Value::Boolean(x) => FactValue::Boolean(x),
            Value::UnsignedInt(x) => FactValue::UnsignedInt(x),
            Value::SignedInt(x) => FactValue::SignedInt(x),
            Value::Float(x) => FactValue::Float(x),
            Value::Bytes(x) => FactValue::Bytes(x),
            Value::Record(x) => FactValue::Record(x),
            Value::Symbol(x) => FactValue::Symbol(self.full_relation(&x.to_string()).await?),
        })
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn failed_root_publication_reopens_old_support_then_retries() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let mut db = Database::open(directory.path(), false).await?;
        let make = |text: &str| FactEntry { entity: "urn:example".into(), predicate: "https://example.org/name".into(),
            value: FactValue::Text(text.into()), cause: None };
        let old = make("old"); let new = make("new");
        db.replace("a", &vec![(old.entity.clone(),vec![old.clone()])]).await?;
        db.storage.fail_root.store(true, std::sync::atomic::Ordering::SeqCst);
        assert!(db.replace("a", &vec![(new.entity.clone(),vec![new.clone()])]).await.is_err());
        drop(db);
        let mut db = Database::open(directory.path(), false).await?;
        let source = identity("source", b"a")?;
        assert_eq!(db.values(&old.entity.parse()?, &relation(&old.predicate)).await?, vec![Value::String("old".into())]);
        assert_eq!(db.values(&source,"folio/contribution").await?,
            vec![Value::Bytes(FactPayload::from_fact(&old).to_bytes())]);
        db.replace("a", &vec![(new.entity.clone(),vec![new.clone()])]).await?;
        assert_eq!(db.values(&source,"folio/contribution").await?,
            vec![Value::Bytes(FactPayload::from_fact(&new).to_bytes())]);
        db.replace("a", &vec![]).await?;
        assert!(db.values(&new.entity.parse()?, &relation(&new.predicate)).await?.is_empty());
        assert!(db.values(&source,"folio/contribution").await?.is_empty());
        Ok(())
    }
    #[tokio::test]
    async fn corrupt_root_reference_does_not_open_an_empty_store() -> Result<()> {
        use dialog_storage::StorageBackend;
        let directory = tempfile::tempdir()?;
        let mut storage = DurableStorage::open(directory.path(), false)?;
        storage.set(dialog_artifacts::make_reference(b"folio-v1"), vec![42;32]).await?;
        drop(storage);
        assert!(Database::open(directory.path(), true).await.is_err());
        assert!(Database::open(directory.path(), false).await.is_err());
        Ok(())
    }
    #[tokio::test]
    async fn dictionary_mismatch_fails_before_source_or_visible_writes() -> Result<()> {
        let directory = tempfile::tempdir()?;
        let mut db = Database::open(directory.path(), false).await?;
        let predicate = "https://example.org/predicate";
        let key: Entity = format!("urn:folio:predicate:{}", relation(predicate)).parse()?;
        let poisoned = artifact(key, "folio/predicate", Value::String("different full identity".into()))?;
        db.store.commit(futures_util::stream::iter(vec![Instruction::Assert(poisoned)])).await?;
        let before = db.store.revision().await?;
        let fact = FactEntry { entity:"urn:item".into(),predicate:predicate.into(),value:FactValue::Boolean(true),cause:None };
        assert!(db.replace("source", &vec![(fact.entity.clone(),vec![fact])]).await.is_err());
        assert_eq!(before,db.store.revision().await?);
        assert!(db.values(&identity("source",b"source")?,"folio/source").await?.is_empty());
        Ok(())
    }
}
