// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/folio/dialog.md — DO NOT EDIT.
use anyhow::Result;
use async_trait::async_trait;
use dialog_artifacts::{ArtifactSelector, ArtifactStream, DialogArtifactsError, Select, inspect::Load, selector::Constrained};
use dialog_capability::Provider;
use dialog_query::{ConceptDescriptor, Environment, Match, Premise, RuleRegistry, Term, types::Any};
use dialog_query::{concept::query::ConceptRules, error::EvaluationError, planner::Planner, source::SelectRules, rule::deductive::DeductiveRule};
use dialog_storage::{Blake3Hash, StorageBackend};
use futures_util::TryStreamExt;
use crate::{database::{Database, relation}, QueryRequest, QueryResult};

struct Source<'a> { database: &'a Database, rules: RuleRegistry }
#[async_trait]
impl<'a> Provider<Select<'a>> for Source<'a> {
    async fn execute(&self, input: ArtifactSelector<Constrained>) -> Result<ArtifactStream<'a>, DialogArtifactsError> {
        Ok(Box::pin(self.database.store.select(input)))
    }
}
#[async_trait]
impl Provider<SelectRules> for Source<'_> {
    async fn execute(&self, input: ConceptDescriptor) -> Result<ConceptRules, EvaluationError> { self.rules.acquire(&input) }
}
#[async_trait]
impl Provider<Load> for Source<'_> {
    async fn execute(&self, input: Blake3Hash) -> Result<Option<Vec<u8>>, DialogArtifactsError> {
        Ok(self.database.storage.get(&input).await?)
    }
}

/// Only descriptor keys identify predicates; ordinary text values stay text.
fn map_descriptor(value: &mut serde_json::Value, names: &mut std::collections::BTreeMap<String,String>) -> Result<()> {
    if let Some(object) = value.as_object_mut() {
        if let Some(serde_json::Value::String(full)) = object.get_mut("the") {
            let short = relation(full);
            if let Some(previous) = names.insert(short.clone(), full.clone()) {
                anyhow::ensure!(previous == *full, "predicate collision within query");
            }
            *full = short;
        }
        if let Some(fields) = object.get_mut("with").and_then(|value| value.as_object_mut()) {
            for field in fields.values_mut() { map_descriptor(field, names)?; }
        }
    }
    Ok(())
}
fn map_descriptors(value: &mut serde_json::Value, names: &mut std::collections::BTreeMap<String,String>) -> Result<()> {
    match value {
        serde_json::Value::Object(object) => {
            for key in ["assert", "deduce"] {
                if let Some(descriptor) = object.get_mut(key) { map_descriptor(descriptor, names)?; }
            }
            for key in ["when", "unless"] {
                if let Some(premises) = object.get_mut(key) { map_descriptors(premises, names)?; }
            }
        }
        serde_json::Value::Array(values) => for value in values { map_descriptors(value, names)?; },
        _ => {}
    }
    Ok(())
}
impl Database {
    pub(crate) async fn query(&mut self, mut request: QueryRequest) -> Result<QueryResult> {
        self.check_instance()?;
        if self.read_only {
            self.store = Self::open_store(&self.storage, true).await?;
        }
        let mut names = std::collections::BTreeMap::new();
        let mut rules = RuleRegistry::new();
        for rule in &mut request.rules {
            map_descriptors(rule, &mut names)?;
            rules.register(serde_json::from_value::<DeductiveRule>(rule.clone())?)?;
        }
        anyhow::ensure!(rules.validate()?.is_empty(), "invalid recursive rule program");
        let mut premises = vec![];
        for premise in &mut request.premises {
            map_descriptors(premise, &mut names)?;
            premises.push(if let Some(unless) = premise.get("unless") {
                Premise::Unless(dialog_query::Negation(serde_json::from_value(unless.clone())?))
            } else { Premise::Assert(serde_json::from_value(premise.clone())?) });
        }
        for (short, full) in &names {
            let key = format!("urn:folio:predicate:{short}").parse()?;
            let values = self.values(&key, "folio/predicate").await?;
            anyhow::ensure!(values.iter().all(|v| v == &dialog_artifacts::Value::String(full.clone())),
                "stored predicate collision while planning query");
        }
        let source = Source { database: self, rules };
        let plan = Planner::from(premises).plan(&Environment::new())?;
        let stream = plan.evaluate(Match::new().seed(), &source);
        tokio::pin!(stream);
        let mut rows = vec![];
        let mut truncated = false;
        while let Some(matched) = stream.try_next().await? {
            if rows.len() == request.max_rows { truncated = true; break; }
            let mut row = std::collections::BTreeMap::new();
            for name in &request.select {
                let binding = matched.lookup(&Term::<Any>::var(name))?;
                if binding.is_present() {
                    row.insert(name.clone(), self.value(binding.content()?).await?);
                }
            }
            rows.push(row);
        }
        Ok(QueryResult { rows, truncated })
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn query_mapping_preserves_record_literals_and_rejects_misspelled_options() -> Result<()> {
        let literal = serde_json::json!({"the":"literal predicate text","assert":{"the":"also literal"}});
        let mut query = serde_json::json!({
            "assert":{"with":{"data":{"the":"https://example.org/record","as":"Record"}}},
            "where":{"data":literal}
        });
        let mut names = std::collections::BTreeMap::new();
        map_descriptors(&mut query, &mut names)?;
        assert_eq!(query["where"]["data"],literal);
        assert_eq!(names.len(),1);
        assert!(serde_json::from_value::<QueryRequest>(serde_json::json!({"max_row":10})).is_err());
        Ok(())
    }
}
