// @generated by x0k-tangle (pipeline: identity-tangle) from corpora/x0k/implementation/folio/ingestion.md — DO NOT EDIT.
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, atomic::{AtomicBool, Ordering}};
use anyhow::Result;
use x0k_fact_projection::{FactEntry, FactValue};
use x0k_fact_projection::payload::file_content_cause;
use x0k_folio_ingest::backend::{Backend, FactSink, MemorySink};
use x0k_folio_ingest::lifecycle::{self, DocumentSource, DocumentProjection};
struct Lines;
impl DocumentSource for Lines {
    fn discover(&self, root: &Path) -> Result<Vec<PathBuf>> {
        Ok(std::fs::read_dir(root)?.map(|entry| entry.map(|e| e.path()))
            .collect::<std::io::Result<Vec<_>>>()?
            .into_iter().filter(|path| self.accepts(path)).collect())
    }
    fn accepts(&self, path: &Path) -> bool {
        path.extension().and_then(|s| s.to_str()) == Some("txt")
    }
    fn project(&self, _path: &Path, bytes: &[u8], hash: &str) -> Result<Option<DocumentProjection>> {
        let text = std::str::from_utf8(bytes)?.trim();
        if text.is_empty() { return Ok(None); }
        let (uri, label) = text.split_once('=').ok_or_else(|| anyhow::anyhow!("invalid line document"))?;
        let fact = FactEntry {
            entity: uri.to_string(), predicate: "urn:label".to_string(),
            value: FactValue::Text(label.to_string()), cause: Some(file_content_cause(hash)),
        };
        Ok(Some(DocumentProjection {
            uri: uri.to_string(), content_hash: hash.to_string(),
            batches: vec![(uri.to_string(), vec![fact])],
        }))
    }
}
struct Offline {
    view: MemorySink,
    down: Arc<AtomicBool>,
}
impl FactSink for Offline {
    fn replace(&mut self, entity: &str, facts: &[FactEntry], cause: &str) -> Result<usize> {
        anyhow::ensure!(!self.down.load(Ordering::SeqCst), "offline");
        self.view.replace(entity, facts, cause)
    }
    fn retract(&mut self, facts: &[FactEntry], cause: &str) -> Result<usize> {
        anyhow::ensure!(!self.down.load(Ordering::SeqCst), "offline");
        self.view.retract(facts, cause)
    }
    fn retains_history(&self) -> bool { false }
}
#[tokio::test]
async fn standalone_source_recovers_without_a_backend_read_view() {
    let root = tempfile::tempdir().unwrap();
    let scratch = tempfile::tempdir().unwrap();
    let state = scratch.path().join("state.json");
    let file = root.path().join("source.txt");
    let a = MemorySink::default();
    let b = MemorySink::default();
    let down = Arc::new(AtomicBool::new(false));
    let stores = || Mutex::new(vec![
        Backend::new("a", a.clone()),
        Backend::new("b", Offline { view: b.clone(), down: down.clone() }),
    ]);
    std::fs::write(&file, "urn:old=Before").unwrap();
    lifecycle::reconcile(&mut Lines, root.path(), &state, &stores(), None).await.unwrap();
    down.store(true, Ordering::SeqCst);
    std::fs::write(&file, "urn:new=After").unwrap();
    lifecycle::reconcile(&mut Lines, root.path(), &state, &stores(), None).await.unwrap();
    assert_ne!(a.facts(), b.facts());
    down.store(false, Ordering::SeqCst);
    lifecycle::reconcile(&mut Lines, root.path(), &state, &stores(), None).await.unwrap();
    assert_eq!(a.facts(), b.facts());
    assert_eq!(b.facts()[0].entity, "urn:new");
    down.store(true, Ordering::SeqCst);
    std::fs::remove_file(&file).unwrap();
    lifecycle::reconcile(&mut Lines, root.path(), &state, &stores(), None).await.unwrap();
    assert!(a.facts().is_empty() && !b.facts().is_empty());
    down.store(false, Ordering::SeqCst);
    lifecycle::reconcile(&mut Lines, root.path(), &state, &stores(), None).await.unwrap();
    assert!(b.facts().is_empty());
}
#[tokio::test]
async fn invalid_source_keeps_last_good_but_non_document_retracts() {
    let root = tempfile::tempdir().unwrap();
    let scratch = tempfile::tempdir().unwrap();
    let state = scratch.path().join("state.json");
    let file = root.path().join("source.txt");
    let view = MemorySink::default();
    let stores = Mutex::new(vec![Backend::new("memory", view.clone())]);
    std::fs::write(&file, "urn:paper=Readable").unwrap();
    lifecycle::apply_path_change(&Lines, &file, &state, &stores).unwrap();
    let before = view.facts();
    std::fs::write(&file, "invalid").unwrap();
    assert!(lifecycle::apply_path_change(&Lines, &file, &state, &stores).is_err());
    let (_, ingested, _) = lifecycle::reconcile(&mut Lines, root.path(), &state, &stores, None).await.unwrap();
    assert_eq!(ingested, 0);
    assert_eq!(view.facts(), before);
    std::fs::write(&file, "").unwrap();
    lifecycle::apply_path_change(&Lines, &file, &state, &stores).unwrap();
    assert!(view.facts().is_empty());
}
#[tokio::test]
async fn ambiguous_backend_names_cannot_write_checkpoints_or_facts() {
    for names in [["same", "same"], ["", "second"], ["   ", "second"]] {
        let root = tempfile::tempdir().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let state = scratch.path().join("state.json");
        let file = root.path().join("source.txt");
        std::fs::write(&file, "urn:paper=Untouched").unwrap();
        let a = MemorySink::default();
        let b = MemorySink::default();
        let stores = Mutex::new(vec![Backend::new(names[0], a.clone()), Backend::new(names[1], b.clone())]);
        assert!(lifecycle::reconcile(&mut Lines, root.path(), &state, &stores, None).await.is_err());
        assert!(lifecycle::apply_path_change(&Lines, &file, &state, &stores).is_err());
        assert!(!x0k_folio_ingest::checkpoint::source_directory(&state).exists());
        assert!(a.facts().is_empty() && b.facts().is_empty());
    }
}
#[tokio::test]
async fn source_revision_changes_replay_unchanged_bytes_at_source_boundary() {
    struct Versioned(u8);
    impl DocumentSource for Versioned {
        fn discover(&self, root: &Path) -> Result<Vec<PathBuf>> { Lines.discover(root) }
        fn accepts(&self, path: &Path) -> bool { Lines.accepts(path) }
        fn revision_hash(&self, bytes: &[u8]) -> String { format!("{}:{}", self.0, blake3::hash(bytes)) }
        fn project(&self, path: &Path, bytes: &[u8], hash: &str) -> Result<Option<DocumentProjection>> { Lines.project(path, bytes, hash) }
    }
    struct SourceSink(Arc<Mutex<Vec<String>>>);
    impl FactSink for SourceSink {
        fn replace_source(&mut self, source: &str, _batches: &x0k_folio_ingest::backend::FactBatches,
            _prior: &[FactEntry], _cause: &str) -> Result<usize> {
            self.0.lock().unwrap().push(source.into()); Ok(1)
        }
        fn replace(&mut self, _: &str, _: &[FactEntry], _: &str) -> Result<usize> { panic!("entity delivery bypassed source") }
        fn retract(&mut self, _: &[FactEntry], _: &str) -> Result<usize> { panic!("retraction bypassed source") }
        fn retains_history(&self) -> bool { false }
    }
    let root = tempfile::tempdir().unwrap();
    let scratch = tempfile::tempdir().unwrap();
    let state = scratch.path().join("state");
    for name in ["a.txt", "b.txt"] { std::fs::write(root.path().join(name), "urn:same=value").unwrap(); }
    let calls = Arc::new(Mutex::new(Vec::new()));
    let sinks = Mutex::new(vec![Backend::new("source", SourceSink(calls.clone()))]);
    lifecycle::reconcile(&mut Versioned(1), root.path(), &state, &sinks, None).await.unwrap();
    assert_eq!(calls.lock().unwrap().len(), 2);
    lifecycle::reconcile(&mut Versioned(1), root.path(), &state, &sinks, None).await.unwrap();
    assert_eq!(calls.lock().unwrap().len(), 2);
    lifecycle::reconcile(&mut Versioned(2), root.path(), &state, &sinks, None).await.unwrap();
    assert_eq!(calls.lock().unwrap().len(), 4);
    let unique: std::collections::BTreeSet<_> = calls.lock().unwrap().iter().cloned().collect();
    assert_eq!(unique.len(), 2);
}
#[test]
fn blocked_backend_does_not_own_registry_or_hold_healthy_delivery() {
    use std::sync::Condvar;
    struct Blocked { entered: std::sync::mpsc::Sender<()>, gate: Arc<(Mutex<bool>, Condvar)> }
    impl FactSink for Blocked {
        fn replace(&mut self, _: &str, _: &[FactEntry], _: &str) -> Result<usize> {
            self.entered.send(()).unwrap();
            let (lock, wake) = &*self.gate;
            let mut release = lock.lock().unwrap();
            while !*release { release = wake.wait(release).unwrap(); }
            Ok(1)
        }
        fn retract(&mut self, _: &[FactEntry], _: &str) -> Result<usize> { Ok(0) }
        fn retains_history(&self) -> bool { false }
    }
    let (entered, waiting) = std::sync::mpsc::channel();
    let gate = Arc::new((Mutex::new(false),Condvar::new()));
    let healthy = MemorySink::default();
    let backends = Arc::new(Mutex::new(vec![
        Backend::new("blocked",Blocked { entered,gate:gate.clone() }),
        Backend::new("healthy",healthy.clone()),
    ]));
    let scratch = tempfile::tempdir().unwrap();
    let path = scratch.path().join("state");
    let projection = Lines.project(Path::new("a.txt"),b"urn:example=value","revision").unwrap().unwrap();
    let shared = backends.clone();
    let operation = std::thread::spawn(move || {
        lifecycle::deliver(&mut Default::default(),&path,"source",&shared,Some(&projection)).unwrap();
    });
    waiting.recv_timeout(std::time::Duration::from_secs(3)).unwrap();
    let deadline = std::time::Instant::now()+std::time::Duration::from_millis(200);
    while healthy.facts().is_empty() && std::time::Instant::now()<deadline { std::thread::yield_now(); }
    let progressed = !healthy.facts().is_empty();
    let registry_free = backends.try_lock().is_ok();
    *gate.0.lock().unwrap() = true;
    gate.1.notify_all();
    operation.join().unwrap();
    assert!(progressed,"healthy sink waited for unrelated blocked sink");
    assert!(registry_free,"registry remained locked across sink effects");
}
#[tokio::test]
async fn timed_out_backend_stays_pending_while_next_source_reaches_healthy_sink() {
    use std::sync::Condvar;
    struct Slow { view: MemorySink, gate: Arc<(Mutex<bool>,Condvar)> }
    impl FactSink for Slow {
        fn replace(&mut self, entity:&str,facts:&[FactEntry],cause:&str)->Result<usize> {
            let mut ready = self.gate.0.lock().unwrap();
            while !*ready { ready = self.gate.1.wait(ready).unwrap(); }
            self.view.replace(entity,facts,cause)
        }
        fn retract(&mut self,facts:&[FactEntry],cause:&str)->Result<usize> { self.view.retract(facts,cause) }
        fn retains_history(&self)->bool { false }
    }
    for reverse in [false,true] {
        let root = tempfile::tempdir().unwrap();
        let scratch = tempfile::tempdir().unwrap();
        let state_path = scratch.path().join("state");
        let slow = MemorySink::default(); let healthy = MemorySink::default();
        let gate = Arc::new((Mutex::new(false),Condvar::new()));
        let mut list = vec![
            Backend::new("slow",Slow {view:slow.clone(),gate:gate.clone()}).with_delivery_grace(std::time::Duration::from_millis(20)),
            Backend::new("healthy",healthy.clone()).with_delivery_grace(std::time::Duration::from_millis(20)),
        ];
        if reverse {list.reverse();}
        let backends = Mutex::new(list);
        for (name,text) in [("a.txt","urn:a=A"),("b.txt","urn:b=B")] {
            let path=root.path().join(name); std::fs::write(&path,text).unwrap();
            lifecycle::apply_path_change(&Lines,&path,&state_path,&backends).unwrap();
        }
        let pending = x0k_folio_ingest::checkpoint::load_state(&state_path).unwrap();
        assert_eq!(healthy.facts().len(),2);
        assert!(pending.files.values().all(|file| file.acked_by.contains("healthy") && !file.acked_by.contains("slow")));
        *gate.0.lock().unwrap()=true;gate.1.notify_all();
        let deadline=std::time::Instant::now()+std::time::Duration::from_secs(3);
        while slow.facts().is_empty() && std::time::Instant::now()<deadline {std::thread::yield_now();}
        assert_eq!(slow.facts().len(),1,"busy backend queued a second source");
        drop(backends);
        let restarted=Mutex::new(vec![Backend::new("slow",slow.clone()),Backend::new("healthy",healthy.clone())]);
        lifecycle::reconcile(&mut Lines,root.path(),&state_path,&restarted,None).await.unwrap();
        assert_eq!(slow.facts().len(),2);
        let caught_up=x0k_folio_ingest::checkpoint::load_state(&state_path).unwrap();
        assert!(caught_up.files.values().all(|file|file.acked_by.len()==2));
    }
}
#[tokio::test]
async fn identity_failure_and_loss_do_not_reuse_acks_and_new_store_replays_only_itself() {
    use std::sync::atomic::AtomicUsize;
    struct Identified { mode:Arc<AtomicUsize>,writes:Arc<AtomicUsize>,view:MemorySink }
    impl FactSink for Identified {
        fn retains_history(&self)->bool {false}
        fn incarnation(&mut self)->Result<Option<String>> {
            match self.mode.load(Ordering::SeqCst) {
                1=>anyhow::bail!("identity unavailable"),
                2=>Ok(None),
                3=>Ok(Some("new-store".into())),
                _=>Ok(Some("initial-store".into())),
            }
        }
        fn replace(&mut self,entity:&str,facts:&[FactEntry],cause:&str)->Result<usize> {
            self.writes.fetch_add(1,Ordering::SeqCst);
            self.view.replace(entity,facts,cause)
        }
        fn retract(&mut self,facts:&[FactEntry],cause:&str)->Result<usize> {self.view.retract(facts,cause)}
    }
    for reverse in [false,true] {
        let root=tempfile::tempdir().unwrap();
        let checkpoint_dir=tempfile::tempdir().unwrap();
        let checkpoint=checkpoint_dir.path().join("state");
        let source=root.path().join("source.txt");
        std::fs::write(&source,"urn:source=unchanged").unwrap();
        let mode=Arc::new(AtomicUsize::new(0));
        let writes=Arc::new(AtomicUsize::new(0));
        let healthy=Arc::new(AtomicUsize::new(0));
        let mut list=vec![
            Backend::new("replaceable",Identified {mode:mode.clone(),writes:writes.clone(),view:MemorySink::default()}),
            Backend::new("healthy",Identified {mode:Arc::new(AtomicUsize::new(0)),writes:healthy.clone(),view:MemorySink::default()})];
        if reverse {list.reverse();}
        let backends=Mutex::new(list);
        lifecycle::reconcile(&mut Lines,root.path(),&checkpoint,&backends,None).await.unwrap();
        for failed in [1,2] {
            mode.store(failed,Ordering::SeqCst);
            lifecycle::reconcile(&mut Lines,root.path(),&checkpoint,&backends,None).await.unwrap();
            let state=x0k_folio_ingest::checkpoint::load_state(&checkpoint).unwrap();
            assert_eq!(state.files[source.to_str().unwrap()].acked_by.iter().cloned().collect::<Vec<_>>(),vec!["healthy"]);
            assert_eq!(writes.load(Ordering::SeqCst),1);
        }
        mode.store(3,Ordering::SeqCst);
        lifecycle::reconcile(&mut Lines,root.path(),&checkpoint,&backends,None).await.unwrap();
        assert_eq!(writes.load(Ordering::SeqCst),2);
        assert_eq!(healthy.load(Ordering::SeqCst),1);
        let state=x0k_folio_ingest::checkpoint::load_state(&checkpoint).unwrap();
        assert_eq!(state.files[source.to_str().unwrap()].acked_by.len(),2);
        assert_eq!(state.recovery[source.to_str().unwrap()].revisions["replaceable"].incarnation.as_deref(),Some("new-store"));
    }
}
#[test]
fn blocked_identity_reserves_time_for_healthy_source_acknowledgement() {
    struct BlockedIdentity(std::sync::mpsc::Receiver<()>);
    impl FactSink for BlockedIdentity {
        fn incarnation(&mut self)->Result<Option<String>> {
            self.0.recv().map_err(|_|anyhow::anyhow!("identity released"))?;
            Ok(Some("blocked".into()))
        }
        fn replace(&mut self,_:&str,_:&[FactEntry],_:&str)->Result<usize> {Ok(0)}
        fn retract(&mut self,_:&[FactEntry],_:&str)->Result<usize> {Ok(0)}
        fn retains_history(&self)->bool {false}
    }
    for reverse in [false,true] {
        let (release,blocked)=std::sync::mpsc::channel();
        let healthy=MemorySink::default();
        let mut list=vec![Backend::new("blocked",BlockedIdentity(blocked)),Backend::new("healthy",healthy.clone())];
        if reverse {list.reverse();}
        let backends=Mutex::new(list.into_iter().map(|b|b.with_delivery_grace(std::time::Duration::from_millis(90))).collect());
        let scratch=tempfile::tempdir().unwrap();
        let mut state=lifecycle::IngesterState::default();
        for source in ["urn:first","urn:second"] {
            let desired=Lines.project(Path::new("source.txt"),format!("{source}=value").as_bytes(),"revision").unwrap().unwrap();
            lifecycle::deliver(&mut state,&scratch.path().join("state"),source,&backends,Some(&desired)).unwrap();
            assert_eq!(state.files[source].acked_by.iter().cloned().collect::<Vec<_>>(),vec!["healthy"]);
        }
        assert_eq!(healthy.facts().len(),2);
        drop(release);
    }
}
