// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/folio/format.md — DO NOT EDIT.
//! folio/v1 envelope types + HTML canonicalizer, and — under the `plugins`
//! feature — the projection plugin that binds the format into a live substrate.
//!
//! Substrate for ontology-aware markdown/HTML documents. Lives apart from
//! `x0k-types` so that `x0k-types` itself stays narrow (publishable
//! substrate primitives only) and so that consumers who don't care about
//! the folio format don't pull `html5ever` and friends.
//!
//! Modules:
//!
//! - [`colophon`] — envelope parser and types (`Colophon`, `DocType`, `Status`, `Materialization`)
//! - [`entity_id`] — the id grammar: `x0k:<class>/<slug>`, parsed and rendered
//! - [`envelope_check`] — an envelope read against the vocabulary this build compiled
//! - [`inline_entity`] — entities authored inside a document body, extracted
//! - [`html_canonical`] — HTML canonicalizer for folio/v1 HTML bodies (stable attribute ordering, whitespace policy, behavior stripping)
//! - `projection` — the `ColophonProjection` projection plugin. Compiled only
//!   under the `plugins` feature; the source ships either way, so a build
//!   without the feature has a module to read and no item to link to. Named
//!   in prose rather than as a doc link for exactly that reason.
//!
//! Plugin registration: at startup, a host that wants the `folio/v1` projection
//! active calls `projection::register_colophon_factory` before loading its class
//! registry. Nothing hard-wires that registration.

pub mod block_provenance;
pub mod block_segment;
pub mod canonical_patch;
pub mod colophon;
pub mod entity_id;
pub mod envelope_check;
pub mod html_canonical;
pub mod inline_entity;
#[cfg(feature = "plugins")]
pub mod projection;
pub mod structural_block;
pub mod transclusion;

pub use block_provenance::{
    fold_events, viewer_state, AgentAttestation, AgentAttestationRecord, AttestationTarget,
    BlockProvenance, GenerationContext, ProposalDisposition, ProvenanceEvent, Underwriting,
    ViewerState,
};
pub use block_segment::{hash_block, segment_body, BlockKind, BlockSegment};
pub use entity_id::{EntityId, EntityIdError};
pub use envelope_check::{
    check_corpus, check_declarations, check_envelope, predicate_standing, CorpusReport,
    DanglingEdge, DeclarationDefect, DeclarationReport, Defect, EnvelopeReport,
    PredicateStanding,
};
pub use inline_entity::{
    declared_facts, declared_facts_with, defined_in_fact, document_edges, extract_from_markdown,
    inline_entity_facts, prose_edges, InlineEntity, InlineEntityError,
};
pub use canonical_patch::{
    apply_body_patches, apply_folio_patches, apply_markdown_patches,
    canonicalize_edited_folio_content, canonicalize_folio_content, CanonicalHtmlPatch,
    CanonicalPatch, CanonicalPatchError, CanonicalTextPoint,
};
#[cfg(feature = "plugins")]
pub use projection::{ColophonProjection, FOLIO_V1_PLUGIN_NAME};
pub use structural_block::{
    BlockId, BlockIdAllocator, FenceInfo, InlineSpan, MarkerId, StructuralBlock, StructuralDoc,
    StructuralListItem, TableAlignment,
};
pub use transclusion::{
    DocSource, Resolved, TranscludeRef, TranscludeWarning, MAX_TRANSCLUDE_DEPTH,
};

/// Idempotent registration of the `folio/v1` projection factory in
/// `x0k_types::class_registry::PLUGIN_FACTORIES`. Daemons call this once at
/// startup (before loading their `ClassRegistry`) so that
/// `plugin = "folio/v1"` entries in `config/projection-classes.toml`
/// resolve to a [`ColophonProjection`] instance.
///
/// Wrapped in a `std::sync::Once` so duplicate calls are no-ops — mirrors
/// the inline `ensure_builtin_plugins_registered` path that
/// `x0k_types::class_registry::ClassRegistry::from_config` triggers
/// lazily.
#[cfg(feature = "plugins")]
pub fn register_colophon_factory() {
    use std::sync::Arc;

    use x0k_types::class_registry::register_plugin_factory;

    static INIT: std::sync::Once = std::sync::Once::new();
    INIT.call_once(|| {
        register_plugin_factory(FOLIO_V1_PLUGIN_NAME, |pt, lep| {
            Arc::new(ColophonProjection::new(pt, lep))
        });
    });
}
