// @generated by x0k-tangle (pipeline: identity-tangle) from corpora/x0k/implementation/folio/ingestion.md — DO NOT EDIT.
use std::collections::{BTreeMap, BTreeSet, HashSet};

use anyhow::Result;
use tracing::{info, warn};
use x0k_fact_projection::payload::canonical_value_bytes;
use x0k_fact_projection::{FactEntry, FactValue};

use crate::events::{PathChangeEvent, ScanState};

/// Where a document's facts land. A sink owns its own idempotency —
/// replaying an applied batch is a no-op — and says whether it keeps
/// superseded facts (`folio-backends` §2, §5).
pub trait FactSink: Send {
    /// Durable store identity, checked before reusing acknowledgements.
    /// None is the compatibility contract for sinks without replaceable storage.
    fn incarnation(&mut self) -> Result<Option<String>> { Ok(None) }

    /// Replace a source contribution. Shared-support sinks override this
    /// boundary; the compatibility default retains entity-region semantics.
    fn replace_source(&mut self, source_key: &str, batches: &FactBatches,
        possible_prior: &[FactEntry], cause: &str) -> Result<usize> {
        let _ = source_key;
        let mut count = 0;
        let mut failure = None;
        for (entity, facts) in batches {
            match self.replace(entity, facts, cause) {
                Ok(n) => count += n,
                Err(error) => failure = Some(error),
            }
        }
        let dropped = dropped_cells(possible_prior.to_vec(), batches);
        if !dropped.is_empty() {
            match self.retract(&dropped, cause) {
                Ok(n) => count += n,
                Err(error) => failure = Some(error),
            }
        }
        if let Some(error) = failure { return Err(error); }
        Ok(count)
    }

    /// Replace `entity`'s whole fact region with `facts`, every one caused
    /// by `cause`. Returns how many facts the sink applied.
    fn replace(&mut self, entity: &str, facts: &[FactEntry], cause: &str) -> Result<usize>;
    /// Retract `facts` as previously asserted, the removal caused by `cause`.
    fn retract(&mut self, facts: &[FactEntry], cause: &str) -> Result<usize>;
    /// Whether superseded and retracted facts stay readable in this sink.
    fn retains_history(&self) -> bool;
    /// The current-view facts this sink holds under `cause` — `None` when
    /// the sink keeps no readable view at all (a write-only mirror).
    fn facts_caused_by(&self, cause: &str) -> Result<Option<Vec<FactEntry>>> {
        let _ = cause;
        Ok(None)
    }
}
/// A world outside the fact plane that wants to hear the core's change
/// events — a timeline, a search index, a webhook.
pub trait Notifier: Send {
    /// One folio document was written or removed under a watched root.
    fn document_changed(&mut self, event: &PathChangeEvent) {
        let _ = event;
    }
    /// A full scan of the tree finished; `scan` carries its content hash.
    fn scan_completed(&mut self, scan: &ScanState) {
        let _ = scan;
    }
}
/// One answer row: variable name → bound value.
pub type QueryRow = BTreeMap<String, FactValue>;

/// Answers queries in the language the backend names (`datalog`,
/// `spine-view`, `search`) over the facts its own sink holds.
pub trait QueryEngine: Send {
    fn language(&self) -> &str;
    fn query(&self, text: &str) -> Result<Vec<QueryRow>>;
}
/// A named backend: a required sink and its optional listener and engine.
pub struct Backend {
    pub name: String,
    pub(crate) worker: crate::delivery::Worker,
    pub(crate) grace: std::time::Duration,
    sink: Box<dyn FactSink>,
    pub notifier: Option<Box<dyn Notifier>>,
    pub query: Option<Box<dyn QueryEngine>>,
}

impl Backend {
    pub fn new(name: impl Into<String>, sink: impl FactSink + 'static) -> Self {
        let worker = crate::delivery::Worker::new(Box::new(sink));
        Self { name: name.into(), sink: Box::new(worker.clone()), worker,
            grace: std::time::Duration::from_millis(250), notifier: None, query: None }
    }
    /// Access the worker-backed sink without replacing its delivery identity.
    pub fn sink(&self) -> &dyn FactSink { self.sink.as_ref() }
    pub fn sink_mut(&mut self) -> &mut dyn FactSink { self.sink.as_mut() }
    /// Overall completion grace after fan-out admission, capped at 30 seconds.
    /// Late success remains unacknowledged and is safely replayed.
    pub fn with_delivery_grace(mut self, grace: std::time::Duration) -> Self {
        self.grace = grace.min(std::time::Duration::from_secs(30));
        self
    }
    pub fn with_notifier(mut self, notifier: impl Notifier + 'static) -> Self {
        self.notifier = Some(Box::new(notifier));
        self
    }
    pub fn with_query(mut self, query: impl QueryEngine + 'static) -> Self {
        self.query = Some(Box::new(query));
        self
    }
}

/// The names of `backends`, in list order.
pub fn backend_names(backends: &[Backend]) -> BTreeSet<String> {
    backends.iter().map(|backend| backend.name.clone()).collect()
}
/// One document's fold: the document's own region, then one region per
/// inline entity its body declares.
pub type FactBatches = Vec<(String, Vec<FactEntry>)>;

/// The fold-cell identity of a fact — `(entity, predicate, canonical
/// value bytes)` — shared with the spine coordinate scheme.
pub fn fact_cell_key(fact: &FactEntry) -> (String, String, Vec<u8>) {
    (fact.entity.clone(), fact.predicate.clone(), canonical_value_bytes(&fact.value))
}

/// The facts of `batches` the prior projection asserted and the new one
/// does not: what every sink must retract.
fn dropped_cells(prior: Vec<FactEntry>, batches: &FactBatches) -> Vec<FactEntry> {
    let kept: HashSet<(String, String, Vec<u8>)> =
        batches.iter().flat_map(|(_, facts)| facts.iter().map(fact_cell_key)).collect();
    prior.into_iter().filter(|fact| !kept.contains(&fact_cell_key(fact))).collect()
}
/// What the document's previous content projected, from the first sink
/// that holds a view. Empty when no sink does, or the read fails — then
/// nothing is retracted, and the region barrier is the only pruning.
fn prior_projection(backends: &[Backend], cause: &str) -> Vec<FactEntry> {
    for backend in backends {
        match backend.sink.facts_caused_by(cause) {
            Ok(Some(facts)) => return facts,
            Ok(None) => continue,
            Err(error) => {
                warn!(backend = %backend.name, error = %error, "folio.backend.prior_read_failed");
                return Vec::new();
            }
        }
    }
    Vec::new()
}
/// What one document's fan-out did, summed over the backends it reached.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FanOut {
    /// Backends whose every call succeeded — including those already
    /// acknowledged before this fan-out and therefore skipped.
    pub acked: BTreeSet<String>,
    /// Facts handed to sinks, replace and retract calls together.
    pub facts: usize,
    /// `replace` and `retract` calls made.
    pub sink_calls: usize,
    /// The diff, computed once and retracted from every reached sink.
    pub retracted: Vec<FactEntry>,
}
/// Hand one document's fold to every backend not in `already`, retracting
/// what its previous content (under `prior_cause`) projected and the new
/// content does not. Sinks are independent: one failing leaves the
/// others' acknowledgement intact.
pub fn replace_document(
    backends: &mut [Backend],
    already: &BTreeSet<String>,
    batches: &FactBatches,
    prior_cause: Option<&str>,
    cause: &str,
) -> FanOut {
    let prior = prior_cause.map(|c| prior_projection(backends, c)).unwrap_or_default();
    replace_document_with_prior(backends, already, batches, prior, cause)
}

/// Deliver against a caller-owned durable projection; reads no sink.
pub fn replace_document_with_prior(
    backends: &mut [Backend],
    already: &BTreeSet<String>,
    batches: &FactBatches,
    prior: Vec<FactEntry>,
    cause: &str,
) -> FanOut {
    let retracted = dropped_cells(prior, batches);
    let mut out = FanOut { acked: already.clone(), retracted, ..FanOut::default() };
    for backend in backends.iter_mut().filter(|b| !already.contains(&b.name)) {
        let mut facts = 0usize;
        let mut ok = true;
        for (entity, entity_facts) in batches {
            out.sink_calls += 1;
            match backend.sink.replace(entity, entity_facts, cause) {
                Ok(applied) => facts += applied,
                Err(error) => {
                    warn!(backend = %backend.name, entity = %entity, error = %error, "folio.backend.replace_failed");
                    ok = false;
                }
            }
        }
        if !out.retracted.is_empty() {
            out.sink_calls += 1;
            match backend.sink.retract(&out.retracted, cause) {
                Ok(applied) => facts += applied,
                Err(error) => {
                    warn!(backend = %backend.name, error = %error, "folio.backend.retract_failed");
                    ok = false;
                }
            }
        }
        out.facts += facts;
        info!(backend = %backend.name, facts, batches = batches.len(), retracted = out.retracted.len(), ok, "folio.backend.replace");
        if ok {
            out.acked.insert(backend.name.clone());
        }
    }
    out
}
/// Retract from every backend everything the document's last content
/// (under `prior_cause`) projected; `cause` names the deletion.
pub fn retract_document(backends: &mut [Backend], prior_cause: &str, cause: &str) -> FanOut {
    let retracted = prior_projection(backends, prior_cause);
    let mut out = FanOut { retracted, ..FanOut::default() };
    if out.retracted.is_empty() {
        return out;
    }
    for backend in backends.iter_mut() {
        out.sink_calls += 1;
        match backend.sink.retract(&out.retracted, cause) {
            Ok(applied) => {
                out.facts += applied;
                out.acked.insert(backend.name.clone());
            }
            Err(error) => warn!(backend = %backend.name, error = %error, "folio.backend.retract_failed"),
        }
        info!(backend = %backend.name, facts = out.retracted.len(), "folio.backend.retract");
    }
    out
}
/// A current-view sink over a `Vec<FactEntry>`: the smallest backend, and
/// the witness the tests below read.
#[derive(Debug, Clone, Default)]
pub struct MemorySink(std::sync::Arc<std::sync::Mutex<Vec<FactEntry>>>);

impl MemorySink {
    /// The current view — replaced regions and retracted cells applied.
    pub fn facts(&self) -> Vec<FactEntry> {
        self.0.lock().unwrap_or_else(|poisoned| poisoned.into_inner()).clone()
    }
}

impl FactSink for MemorySink {
    fn replace(&mut self, entity: &str, facts: &[FactEntry], _cause: &str) -> Result<usize> {
        let mut view = self.0.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        view.retain(|fact| fact.entity != entity);
        view.extend(facts.iter().cloned());
        Ok(facts.len())
    }
    fn retract(&mut self, facts: &[FactEntry], _cause: &str) -> Result<usize> {
        let gone: HashSet<_> = facts.iter().map(fact_cell_key).collect();
        let mut view = self.0.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
        view.retain(|fact| !gone.contains(&fact_cell_key(fact)));
        Ok(facts.len())
    }
    fn retains_history(&self) -> bool {
        false
    }
    fn facts_caused_by(&self, cause: &str) -> Result<Option<Vec<FactEntry>>> {
        Ok(Some(self.facts().into_iter().filter(|f| f.cause.as_deref() == Some(cause)).collect()))
    }
}
