// @generated by x0k-tangle (pipeline: identity-tangle) from corpora/x0k/implementation/folio/ingestion.md — DO NOT EDIT.
use std::path::PathBuf;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PathChangeEvent {
    /// `path` still exists and parsed as folio/v1.
    Upserted(PathBuf),
    /// `path` no longer exists on disk.
    Removed(PathBuf),
}

/// Per-run summary written to `state_path` and embedded in the milestone row.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ScanState {
    pub scan_root: String,
    pub tree_content_hash: String,
    pub file_count: usize,
    pub started_at_us: u64,
    pub finished_at_us: u64,
}
