// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/tangle/crate.md — DO NOT EDIT.
//! Pins for the verdicts the CLI returns
//! (`x0k:implementation/tangle/crate`): what `sync` exits with when a
//! chunk it was asked to fill stayed empty, and what `check` says about
//! an edge that leaves the set.

use std::fs;
use std::path::Path;
use std::process::{Command, Output};

use tempfile::TempDir;

const JS_SOURCE: &str =
    "export function createHorizonRemap(scale) {\n  return (u) => u * scale;\n}\n";

fn write(dir: &Path, rel: &str, content: &str) {
    let path = dir.join(rel);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

fn run(args: &[&str], dir: &Path) -> Output {
    Command::new(env!("CARGO_BIN_EXE_x0k-tangle"))
        .args(args)
        .arg(dir)
        .output()
        .expect("the x0k-tangle binary runs")
}

fn sync(dir: &Path) -> Output {
    Command::new(env!("CARGO_BIN_EXE_x0k-tangle"))
        .arg("sync")
        .arg(dir)
        .arg("--workspace")
        .arg(dir)
        .output()
        .expect("the x0k-tangle binary runs")
}

#[test]
fn sync_fills_a_javascript_chunk_and_passes() {
    let tmp = TempDir::new().unwrap();
    write(tmp.path(), "remap.js", JS_SOURCE);
    write(
        tmp.path(),
        "doc.md",
        "# Remap\n\n```javascript {#remap from=\"remap.js\" symbol=\"createHorizonRemap\"}\n```\n",
    );

    let out = sync(tmp.path());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(out.status.success(), "sync failed: {stderr}");
    assert!(stderr.contains("synced 1 chunk(s)"), "got {stderr}");

    let synced = fs::read_to_string(tmp.path().join("doc.md")).unwrap();
    assert!(
        synced.contains("export function createHorizonRemap(scale)"),
        "got {synced}"
    );
}

#[test]
fn sync_exits_nonzero_when_a_chunk_it_was_asked_to_fill_stayed_empty() {
    let tmp = TempDir::new().unwrap();
    write(
        tmp.path(),
        "doc.md",
        "# Remap\n\n```rust {#remap from=\"missing.rs\" symbol=\"remap\"}\n```\n",
    );

    let out = sync(tmp.path());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(
        !out.status.success(),
        "a sync that filled nothing reported success: {stderr}"
    );
    assert!(stderr.contains("error:"), "got {stderr}");
}

#[test]
fn sync_names_the_language_limit_rather_than_the_symbol() {
    let tmp = TempDir::new().unwrap();
    write(tmp.path(), "remap.py", "def create_remap():\n    return 1\n");
    write(
        tmp.path(),
        "doc.md",
        "# Remap\n\n```python {#remap from=\"remap.py\" symbol=\"create_remap\"}\n```\n",
    );

    let out = sync(tmp.path());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(!out.status.success(), "got {stderr}");
    assert!(stderr.contains("symbol extraction supports"), "got {stderr}");
    assert!(
        !stderr.contains("not found"),
        "an unwalkable language must not read as a mistyped symbol: {stderr}"
    );
}

#[test]
fn sync_passes_a_document_with_nothing_to_fill() {
    let tmp = TempDir::new().unwrap();
    write(
        tmp.path(),
        "doc.md",
        "---\nx0k:\n  format: folio/v1\n  id: x0k:implementation/fixture\n  \
         type: implementation\n  status: draft\n  tangle:\n    crate: fixture\n    \
         root: src/lib.rs\n---\n# Doc\n\n```rust {#root}\nfn f() {}\n```\n",
    );

    let out = sync(tmp.path());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(out.status.success(), "sync failed: {stderr}");
    assert!(stderr.contains("synced 0 chunk(s)"), "got {stderr}");
}

/// A predicate this build is certain to accept, so the fixture measures
/// the note and not the module selection.
fn shipped_predicate() -> &'static str {
    x0k_ontology::KNOWN_EDGE_PREDICATES
        .first()
        .copied()
        .expect("a build whose vocabulary declares no document edge ships no document module")
}

#[test]
fn the_dangling_edge_note_claims_only_what_is_true_of_any_tree() {
    let tmp = TempDir::new().unwrap();
    write(
        tmp.path(),
        "docs/fixture.md",
        &format!(
            "---\nx0k:\n  format: folio/v1\n  id: x0k:design/fixture\n  type: design\n  \
             status: draft\n  edges:\n    {}:\n      - x0k:design/elsewhere\n---\n# Fixture\n",
            shipped_predicate()
        ),
    );

    let out = run(&["check"], tmp.path());
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(out.status.success(), "check failed: {stderr}");
    assert!(
        stderr.contains("names no document under the paths scanned"),
        "the note names the set it scanned: {stderr}"
    );
    assert!(
        !stderr.contains("projected from"),
        "the note claims nothing about a corpus the reader may not have: {stderr}"
    );
}
