// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/tangle/crate.md — DO NOT EDIT.
//! The protocol-only `x0k-tangle` CLI: the crate's verbs in a shell,
//! with the built-in registry and no plugins. The binary a projected
//! repository ships and builds.

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

#[derive(Parser)]
#[command(
    name = "x0k-tangle",
    about = "Literate programming tangler with bidirectional sync",
    after_help = "Commands marked [corpus-only] read the publication corpus \
(decisions/publications/ and the decision documents it names). They are not \
runnable from a projected repository, which carries only the literate documents \
under knowledge/implementation/ — everything else here works there."
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Tangle .md documents to their source files (writes .tangle-map.json sidecars)
    Tangle {
        /// Paths to scan for documents with tangle: frontmatter
        paths: Vec<PathBuf>,
        /// Workspace root (defaults to current directory)
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Overwrite outputs holding content this tangler did not write
        #[arg(long)]
        force: bool,
    },
    /// Verify chunk references resolve and no cycles exist, and read every
    /// folio/v1 envelope against a vocabulary.
    ///
    /// Two things can go wrong with an envelope, and they are reported
    /// apart. A defect — a malformed id or edge target, a predicate no
    /// module of the vocabulary declares, an envelope that does not parse —
    /// is a gap in what this publication selected, and fails the check. An
    /// edge whose target names no document under the paths scanned simply
    /// leaves the set — often into a wider corpus this selection was drawn
    /// from, and expected either way: printed as a note, never a failure.
    /// A third thing is checked across the set: an
    /// affordance claimed for a human that no signifier signifies is a
    /// defect, because the audience has nothing to perceive.
    ///
    /// Every `from=` chunk is resolved against its source file too —
    /// missing file, missing symbol, ambiguous symbol, a language symbol
    /// extraction cannot walk — and each failure fails the check. Nothing
    /// is written: this is the read-only half of `sync`.
    Check {
        /// Paths to scan
        paths: Vec<PathBuf>,
        /// Workspace root that `from=` paths resolve against
        /// (defaults to current directory)
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Directory of ontology module files (*.ttl) to check against.
        /// Defaults to the modules this projection's PROVENANCE.json names,
        /// then to the set this build compiled.
        #[arg(long)]
        vocabulary: Option<PathBuf>,
    },
    /// Print every affordance the folio/v1 documents under the paths
    /// declare, as a JSON array on stdout.
    ///
    /// One record per `yaml x0k:affordance` block: `id`, `title` (the
    /// enclosing heading), `description` (the prose under it), `defined_in`
    /// (the parent document's id), and `facts` — every other declared fact
    /// grouped by predicate, each value tagged `{"entity": …}` for an id or
    /// `{"string": …}` for a literal. A block the extractor refuses is
    /// reported on stderr and skipped.
    Affordances {
        /// Paths to scan for folio/v1 documents
        paths: Vec<PathBuf>,
    },
    /// Check every `svg x0k:icon` declaration in the folio/v1 documents
    /// under the paths against the icon profile, and with `--out` write
    /// each as its light and dark files bound to a publication's palette.
    ///
    /// A drawing outside the profile is printed with the rule it broke and
    /// the element, and fails the run; nothing is redrawn. `--out` needs
    /// `--palette`: the publication document whose envelope carries the
    /// `palette:` block the four paint roles are bound with.
    Icon {
        /// Paths to scan for folio/v1 documents
        paths: Vec<PathBuf>,
        /// Directory to write `<stem>-light.svg` and `<stem>-dark.svg` into
        #[arg(long, requires = "palette")]
        out: Option<PathBuf>,
        /// The publication document whose `palette:` binds the roles
        #[arg(long, requires = "out")]
        palette: Option<PathBuf>,
    },
    /// Sync from= chunks: populate code blocks from source files.
    /// Symbol extraction reads rust, typescript, javascript, tsx, python, julia
    Sync {
        /// Paths to scan for documents with from= chunks
        paths: Vec<PathBuf>,
        /// Workspace root (defaults to current directory)
        #[arg(long)]
        workspace: Option<PathBuf>,
    },
    /// Build a JSON index of all folio/v1 files
    Index {
        /// Paths to scan for folio/v1 documents
        paths: Vec<PathBuf>,
        /// Workspace root (defaults to current directory)
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Output file (defaults to stdout)
        #[arg(short, long)]
        output: Option<PathBuf>,
    },
    /// Weave a literate document into HTML
    Weave {
        /// Path to a literate document
        path: PathBuf,
        /// Output directory (defaults to stdout if not set)
        #[arg(long)]
        output_dir: Option<PathBuf>,
    },
    /// [corpus-only] Project a publication region into a self-contained,
    /// navigable multi-page web artifact.
    ///
    /// `region` is the publication decision doc
    /// (`decisions/publications/<slug>.md`, `type: publication`). Its
    /// `publishes:` membership + `entryPoint:` define the region; each member's
    /// decision doc is woven (wrapping the single-doc weaver), cross-doc links
    /// are rewritten to artifact-relative paths, and a site nav is injected.
    ///
    /// Reads `decisions/publications/` and the decision documents it names,
    /// so it needs a corpus checkout; a projected repository carries only
    /// `knowledge/implementation/` and this verb refuses there.
    WeaveRegion {
        /// Path to the publication decision doc.
        region: PathBuf,
        /// Directory to write the artifact into (created if absent).
        #[arg(long)]
        output_dir: PathBuf,
        /// Workspace root the `decisions/<subtype>/...` tree hangs off of
        /// (defaults to current directory). Member sources + motif scanning
        /// resolve against this.
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Skip motif wasm bundling (page/nav/link-rewrite core only). Motif
        /// refs are still reported but no `.wasm`/`host.js` is emitted.
        #[arg(long)]
        no_motifs: bool,
    },
    /// [corpus-only] Project a publication region into a standalone,
    /// buildable Cargo repository.
    ///
    /// Literate `.md` source + committed tangled code + workspace manifest +
    /// the publication's declared license + README + CI, git-init'd. Sibling
    /// to `weave-region` (which emits an HTML reader site).
    ///
    /// Reads `decisions/publications/` and the decision documents it names,
    /// so it needs a corpus checkout; a projected repository carries only
    /// `knowledge/implementation/` and this verb refuses there.
    ProjectRepo {
        /// Path to the publication decision doc (`type: publication`).
        region: PathBuf,
        /// Directory to write the standalone repo into (created if absent).
        #[arg(long)]
        output_dir: PathBuf,
        /// Workspace root the published crates resolve against (defaults to cwd).
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Explicit SPDX license override. Without this flag the license comes
        /// from the publication doc's `license:` envelope field (the manifest
        /// is authoritative); with neither, the projection refuses. There is
        /// no silent default.
        #[arg(long)]
        license: Option<String>,
        /// Do not `git init` / commit the output dir.
        #[arg(long)]
        no_git: bool,
        /// Do not emit `.github/workflows/` wrappers (the forge-agnostic
        /// `tools/ci` + `tools/x0k-guard-generated` are always emitted).
        #[arg(long)]
        no_github: bool,
        /// Bypass leak / closure / publish-exclusion guards (escape hatch).
        #[arg(long)]
        allow_dirty: bool,
    },
    /// [corpus-only] Publish pipeline for a projected repository: project,
    /// prove, rehearse, and (only under --really) publish.
    ///
    /// Projects with guards on, builds + tests the projection standalone,
    /// rehearses with one `cargo publish --dry-run --workspace` over the
    /// whole bundle, and reports. The real `cargo publish --workspace` and
    /// the `git push` to the publication's configured remote run ONLY under
    /// `--really` (operator-only; refuses unless the rehearsal passed).
    ///
    /// Reads `decisions/publications/` and the decision documents it names,
    /// so it needs a corpus checkout; a projected repository carries only
    /// `knowledge/implementation/` and this verb refuses there.
    PublishRepo {
        /// Path to the publication decision doc (`type: publication`).
        region: PathBuf,
        /// Directory to project the repo into (created if absent).
        #[arg(long)]
        output_dir: PathBuf,
        /// Workspace root the published crates resolve against (defaults to cwd).
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Explicit SPDX license override (default: the publication doc's
        /// `license:` field is authoritative).
        #[arg(long)]
        license: Option<String>,
        /// Do not emit `.github/workflows/` wrappers.
        #[arg(long)]
        no_github: bool,
        /// Actually publish to crates.io and push to the configured remote.
        /// Operator-only.
        #[arg(long)]
        really: bool,
    },
    /// [corpus-only] Receive changes made in a projected repository (a
    /// contributor's clone) back into the corpus as a proposed change.
    ///
    /// Diffs the clone against a reference projection at the clone's
    /// `corpus_rev`, classifies every changed path, writes unified diffs +
    /// `receipt.json`, and — under `--apply` — patches the working copy
    /// (never commits). Exits non-zero when any change was refused (an
    /// `@generated` edit).
    ///
    /// Reads `decisions/publications/` and the decision documents it names,
    /// so it needs a corpus checkout; a projected repository carries only
    /// `knowledge/implementation/` and this verb refuses there.
    ReceiveRepo {
        /// The contributor's clone of the projected repository.
        clone: PathBuf,
        /// Workspace root the patches apply to (defaults to cwd).
        #[arg(long)]
        workspace: Option<PathBuf>,
        /// Directory for the patch set + receipt.json (default: temp).
        #[arg(long)]
        out: Option<PathBuf>,
        /// Apply the receivable patches to the working copy. Refused when a
        /// target path already has uncommitted changes.
        #[arg(long)]
        apply: bool,
        /// Publication doc override (default: resolved from the clone's
        /// PROVENANCE.json `publication_uri` under decisions/publications/).
        #[arg(long)]
        publication: Option<PathBuf>,
        /// Root for the reference projection's temp dir (must be outside the
        /// workspace; default: the system temp dir).
        #[arg(long)]
        scratch: Option<PathBuf>,
    },
    /// List chunks and their targets in a document
    List {
        /// Path to a literate document
        path: PathBuf,
    },
    /// Tangle every dirty literate document this binary's registry
    /// can handle.
    ///
    /// This binary ships only the built-in `PipelineRegistry::default()`,
    /// which carries only the `identity-tangle` plugin. It walks every
    /// literate root claimed by that plugin (`knowledge/implementation/**`) and
    /// re-tangles dirty docs. Docs that declare additional pipelines
    /// land in the `errored` bucket as "unknown pipeline kind"; a host
    /// that registers more plugins builds its own binary around the
    /// library.
    Workspace {
        /// Workspace root (defaults to the current directory)
        #[arg(long)]
        root: Option<PathBuf>,
        /// Overwrite outputs holding content this tangler did not write
        #[arg(long)]
        force: bool,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Command::Tangle { paths, workspace, force } => {
            // Route identity tangling through the unified dispatcher.
            // The default registry has `IdentityPipeline` registered;
            // docs that also declare extra pipelines will error here
            // because this binary doesn't ship those plugins.
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let docs = discover_documents(&paths)?;
            let registry = x0k_tangle::PipelineRegistry::default();
            let settings = clobber_settings(force);
            let mut total_files = 0;
            let mut tangled_docs = 0;
            let mut nowhere_to_write = 0;

            for doc_path in &docs {
                let declared = declares(doc_path);
                if !declared.target {
                    eprintln!("  {}", nothing_to_write(doc_path, declared.chunks));
                    nowhere_to_write += 1;
                    continue;
                }
                tangled_docs += 1;
                let result = x0k_tangle::tangle_document_with(doc_path, &ws, &registry, &settings)?;
                for out in &result.identity_outputs {
                    eprintln!("  {} → {}", doc_path.display(), out.path.display());
                    total_files += 1;
                }
                for out in &result.pipeline_outputs {
                    if out.kind == x0k_tangle::IDENTITY_KIND {
                        // Already reported via identity_outputs.
                        continue;
                    }
                    eprintln!("  {} → {}", doc_path.display(), out.path.display());
                    total_files += 1;
                }
            }

            eprintln!(
                "tangled {} file(s) from {} document(s)",
                total_files, tangled_docs
            );

            if nowhere_to_write > 0 {
                eprintln!("{nowhere_to_write} document(s) named nowhere to write");
                std::process::exit(1);
            }
        }

        Command::Sync { paths, workspace } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let docs = discover_documents_any(&paths)?;
            let mut total_populated = 0;
            let mut unfilled = 0;

            for doc_path in &docs {
                let result = x0k_tangle::sync::sync_document(doc_path, &ws)?;

                for err in &result.errors {
                    eprintln!("  error: {}: {}", doc_path.display(), err);
                    unfilled += 1;
                }

                if result.chunks_populated > 0 {
                    eprintln!(
                        "  {} — populated {} chunk(s)",
                        doc_path.display(),
                        result.chunks_populated
                    );
                    total_populated += result.chunks_populated;
                }
            }

            eprintln!(
                "synced {} chunk(s) across {} document(s)",
                total_populated,
                docs.len()
            );

            if unfilled > 0 {
                eprintln!("{unfilled} chunk(s) named a source and were left empty");
                std::process::exit(1);
            }
        }

        Command::Check { paths, workspace, vocabulary } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let model = x0k_tangle::faces::vocabulary(vocabulary.as_deref())?;
            let mut has_errors = false;
            let mut chunked_documents = 0;
            let mut source_refs = 0;
            let mut ids: HashMap<String, PathBuf> = HashMap::new();

            for doc_path in markdown_under(&paths) {
                let content = match std::fs::read_to_string(&doc_path) {
                    Ok(content) => content,
                    Err(e) => {
                        // A file the gate cannot read is a file it cannot vouch
                        // for, and saying so beats counting it as clean.
                        eprintln!("{}: cannot be read: {e}", doc_path.display());
                        has_errors = true;
                        continue;
                    }
                };
                let parsed = match x0k_tangle::parser::parse_document(&content) {
                    Ok(parsed) => parsed,
                    Err(e) => {
                        eprintln!("{}: does not parse: {e}", doc_path.display());
                        has_errors = true;
                        continue;
                    }
                };

                if !parsed.chunks.is_empty() {
                    chunked_documents += 1;
                    for err in &x0k_tangle::resolve::check_all_refs(&parsed)? {
                        eprintln!("{}: {}", doc_path.display(), err);
                        has_errors = true;
                    }
                    let sources = x0k_tangle::source_check::check_source_refs(&parsed, &ws);
                    source_refs += sources.checked;
                    for finding in &sources.findings {
                        eprintln!("{}: {}", doc_path.display(), finding);
                        has_errors = true;
                    }
                }

                if let Some(id) = parsed.id {
                    match ids.get(&id) {
                        Some(first) => {
                            eprintln!(
                                "{}: duplicate document id `{id}`, already declared by {}",
                                doc_path.display(),
                                first.display()
                            );
                            has_errors = true;
                        }
                        None => {
                            ids.insert(id, doc_path.clone());
                        }
                    }
                }
            }

            let report = x0k_tangle::faces::check_vocabulary(&model, &paths)?;
            for (path, reason) in &report.unparsed {
                eprintln!("{path}: envelope does not parse: {reason}");
                has_errors = true;
            }
            for (path, defect) in &report.corpus.defects {
                eprintln!("{path}: {defect}");
                has_errors = true;
            }
            for defect in &report.declarations.defects {
                eprintln!("{defect}");
                has_errors = true;
            }
            for edge in &report.corpus.dangling {
                eprintln!(
                    "{}",
                    dangling_note(&edge.source, &edge.predicate, &edge.target)
                );
            }

            if has_errors {
                std::process::exit(1);
            } else {
                eprintln!(
                    "{}; {} envelope(s) read against the vocabulary, {} declaration(s) checked, {} edge(s) leave the set",
                    references_verdict(chunked_documents, source_refs),
                    report.corpus.checked,
                    report.declarations.checked,
                    report.corpus.dangling.len()
                );
            }
        }

        Command::Affordances { paths } => {
            let report = x0k_tangle::faces::declared_affordances(&paths)?;
            for (path, reason) in &report.skipped {
                eprintln!("{path}: skipped: {reason}");
            }
            println!("{}", serde_json::to_string_pretty(&report.records)?);
        }

        Command::Icon { paths, out, palette } => {
            let report = x0k_tangle::faces::declared_icons(&paths)?;
            for (path, reason) in &report.skipped {
                eprintln!("{path}: skipped: {reason}");
            }
            for (place, refusal) in &report.refused {
                eprintln!("{place}:\n{refusal}");
            }
            let mut written = 0;
            if let (Some(out), Some(palette)) = (out, palette) {
                let content = std::fs::read_to_string(&palette)
                    .with_context(|| format!("reading {}", palette.display()))?;
                let palette = x0k_tangle::region_repo::envelope_palette(&content)?.ok_or_else(|| {
                    anyhow::anyhow!("{} carries no `palette:` in its envelope", palette.display())
                })?;
                written = x0k_tangle::faces::write_icon_files(&report, &palette, &out)?.len();
            }
            eprintln!(
                "{} icon(s) checked, {} refused, {written} file(s) written",
                report.accepted.len() + report.refused.len(),
                report.refused.len()
            );
            if !report.refused.is_empty() {
                std::process::exit(1);
            }
        }

        Command::Index {
            paths,
            workspace,
            output,
        } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let index = x0k_tangle::index::build_index(&paths, &ws)?;
            let json = serde_json::to_string_pretty(&index)?;

            if let Some(out_path) = output {
                std::fs::write(&out_path, &json)?;
                eprintln!(
                    "indexed {} documents → {}",
                    index.docs.len(),
                    out_path.display()
                );
            } else {
                println!("{}", json);
            }
        }

        Command::Weave { path, output_dir } => {
            let content = std::fs::read_to_string(&path)?;
            let parsed = x0k_tangle::parser::parse_document(&content)?;
            let output = x0k_tangle::weave::weave_html(&content, &parsed)?;

            if let Some(dir) = output_dir {
                std::fs::create_dir_all(&dir)?;
                // Named after the document, so weaving a second chapter into one
                // directory no longer destroys the first (weave.md § the page's name).
                let html_path = dir.join(x0k_tangle::weave::page_file_name(&path));
                std::fs::write(&html_path, &output.html)?;
                eprintln!("wove {} → {}", path.display(), html_path.display());
            } else {
                print!("{}", output.html);
            }
        }

        Command::WeaveRegion {
            region,
            output_dir,
            workspace,
            no_motifs,
        } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let report = x0k_tangle::project_publication(&region, &output_dir, &ws, no_motifs)?;
            eprintln!(
                "wove region {} → {} ({} page(s), {} media ref(s), {} unresolved link(s))",
                region.display(),
                output_dir.join(&report.entry_rel_path).display(),
                report.page_count,
                report.media_refs.len(),
                report.unresolved_links.len(),
            );
            if !report.unresolved_links.is_empty() {
                for href in &report.unresolved_links {
                    eprintln!("  unresolved link: {href}");
                }
            }
            if !report.degraded_embeds.is_empty() {
                eprintln!(
                    "  {} embed(s) show their static fallback label",
                    report.degraded_embeds.len()
                );
            }
            eprintln!(
                "  atlas.json: {} node(s), {} edge(s), {} thread(s) [{}]",
                report.atlas_node_count,
                report.atlas_edge_count,
                report.atlas_threads.len(),
                report.atlas_threads.join(", "),
            );
            eprintln!(
                "  presentation: render-vello wasm {}, narrative {}",
                if report.wasm_bundled {
                    format!("bundled ({} KiB)", report.wasm_bytes / 1024)
                } else {
                    "MISSING (set X0K_RENDER_VELLO_WASM_DIR or build it)".to_string()
                },
                if report.narrative_bundled {
                    "bundled"
                } else {
                    "stub (no sidecar)"
                },
            );
            if !report.atlas_unresolved_years.is_empty() {
                for uri in &report.atlas_unresolved_years {
                    eprintln!("  atlas: unresolved year for {uri}");
                }
            }
        }

        Command::ProjectRepo {
            region,
            output_dir,
            workspace,
            license,
            no_git,
            no_github,
            allow_dirty,
        } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let opts = x0k_tangle::RepoProjectOptions {
                license,
                git_init: !no_git,
                allow_dirty,
                emit_github: !no_github,
            };
            let report = x0k_tangle::project_publication_repo(&region, &output_dir, &ws, &opts)?;
            eprintln!(
                "projected repo {} → {} ({} crate(s), {} literate doc(s), license {} [{}]{})",
                region.display(),
                output_dir.display(),
                report.crates.len(),
                report.literate_docs.len(),
                report.license,
                match report.license_source {
                    x0k_tangle::LicenseSource::PublicationDoc => "from publication doc",
                    x0k_tangle::LicenseSource::Override => "explicit override",
                },
                if report.committed {
                    ", committed"
                } else if !no_git {
                    ", unchanged (no new commit)"
                } else {
                    ""
                },
            );
            if !report.excluded.is_empty() {
                eprintln!("  publish-excluded: {}", report.excluded.join(", "));
            }
            for v in report
                .leak_violations
                .iter()
                .chain(report.closure_violations.iter())
            {
                eprintln!("  WARNING: {v}");
            }
        }

        Command::PublishRepo {
            region,
            output_dir,
            workspace,
            license,
            no_github,
            really,
        } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let opts = x0k_tangle::PublishRepoOptions {
                license,
                emit_github: !no_github,
                really,
            };
            let report = x0k_tangle::publish_repo(&region, &output_dir, &ws, &opts)?;
            eprintln!(
                "publish-repo {} → {} (license {})",
                region.display(),
                output_dir.display(),
                report.projection.license,
            );
            eprintln!(
                "  build: {}  test: {}",
                if report.build_ok { "ok" } else { "FAILED" },
                if report.test_ok { "ok" } else { "FAILED" },
            );
            eprintln!("  publish order: {}", report.publish_order.join(" → "));
            if let Some(r) = &report.rehearsal {
                eprintln!(
                    "  dry-run (whole bundle): {}",
                    if r.ok { "ok" } else { "FAILED" }
                );
                if !r.ok {
                    for line in r.output_tail.lines() {
                        eprintln!("      {line}");
                    }
                }
            }
            if !report.build_ok || !report.test_ok {
                eprintln!("  stopped: the projection must build and test green before any rehearsal");
                std::process::exit(1);
            }
            match (&report.surface, &report.remote) {
                (Some(s), Some(r)) => eprintln!("  remote: {s} → {r}"),
                (Some(s), None) => eprintln!(
                    "  remote: {s} has no [publish.remotes] entry in config/x0k-tangle.toml"
                ),
                (None, _) => eprintln!("  remote: publication has no publishedOn edge"),
            }
            if report.published || report.pushed {
                eprintln!(
                    "  PUBLISHED: crates.io={} push={}",
                    report.published, report.pushed
                );
            } else if !really {
                eprintln!("  stopped before publishing (pass --really to publish; operator-only)");
            }
        }

        Command::ReceiveRepo {
            clone,
            workspace,
            out,
            apply,
            publication,
            scratch,
        } => {
            let ws = workspace.unwrap_or_else(|| std::env::current_dir().unwrap());
            let opts = x0k_tangle::ReceiveOptions {
                apply,
                out_dir: out.clone(),
                publication,
                scratch,
            };
            let report = x0k_tangle::receive_repo(&clone, &ws, &opts)?;
            eprintln!(
                "receive-repo {} ({}): clone rev {} vs reference {}{}",
                clone.display(),
                report.publication_uri,
                if report.clone_rev.is_empty() { "(none)" } else { &report.clone_rev },
                if report.reference_rev.is_empty() { "(none)" } else { &report.reference_rev },
                if report.rev_exact { "" } else { "  [REV SKEW: diff includes the corpus's own drift, reversed]" },
            );
            for c in &report.changes {
                let class = match c.class {
                    x0k_tangle::receive::Class::Literate => "literate (received)",
                    x0k_tangle::receive::Class::Source => "source (received)",
                    x0k_tangle::receive::Class::Generated => "GENERATED (refused)",
                    x0k_tangle::receive::Class::ProjectionLocal => "overlay (projection-local, not received)",
                    x0k_tangle::receive::Class::ProjectionOwned => "projection-owned (not received)",
                };
                let size = c.patch.as_ref().map(|p| p.lines().count()).unwrap_or(0);
                match (&c.target, &c.produced_by) {
                    (Some(t), _) => eprintln!("  {:<9} {}  {class}  → {t}  ({size} patch lines)", c.kind, c.path),
                    (None, Some(o)) => eprintln!(
                        "  {:<9} {}  {class}  produced by {}{}",
                        c.kind,
                        c.path,
                        o.doc,
                        if o.chunks.is_empty() { String::new() } else { format!(" chunks {}", o.chunks.join(", ")) }
                    ),
                    (None, None) => eprintln!("  {:<9} {}  {class}", c.kind, c.path),
                }
            }
            eprintln!(
                "  {} change(s): {} received, {} refused{}{}",
                report.changes.len(),
                report.received(),
                report.refused(),
                match &out {
                    Some(d) => format!("; patch set in {}", d.display()),
                    None => String::new(),
                },
                if report.applied { format!("; applied to working copy (dirty check: {})", report.dirty_check) } else { "" .to_string() },
            );
            if report.refused() > 0 {
                std::process::exit(1);
            }
        }

        Command::Workspace { root, force } => {
            let ws = resolve_workspace_root(root)?;
            let registry = x0k_tangle::PipelineRegistry::default();
            let settings = clobber_settings(force);
            let report = x0k_tangle::tangle_workspace_with(&ws, &registry, &settings)?;
            print_workspace_summary(&ws, &report);
            if !report.errored.is_empty() {
                std::process::exit(1);
            }
        }

        Command::List { path } => {
            let content = std::fs::read_to_string(&path)?;
            let parsed = x0k_tangle::parser::parse_document(&content)?;

            if let Some(ref c) = parsed.tangle_crate {
                println!("crate: {}", c);
            }
            if let Some(ref r) = parsed.tangle_root {
                println!("root:  {}", r.display());
            }
            println!();

            for name in &parsed.chunk_order {
                let Some(chunk) = parsed.chunk(name) else {
                    continue;
                };
                let kind = if chunk.is_media {
                    "media"
                } else if chunk.is_from_ref() {
                    "from"
                } else {
                    "owned"
                };
                let target = chunk
                    .file_target
                    .as_ref()
                    .map(|p| p.display().to_string())
                    .or_else(|| chunk.from.as_ref().map(|p| p.display().to_string()))
                    .unwrap_or_default();
                let symbol = chunk.symbol.as_deref().unwrap_or("");
                let lines: usize = chunk.bodies.iter().map(|b| b.text.lines().count()).sum();

                println!(
                    "  {:<6} {:<24} {:>4} lines  {}{}",
                    kind,
                    name,
                    lines,
                    target,
                    if symbol.is_empty() {
                        String::new()
                    } else {
                        format!("  symbol={}", symbol)
                    }
                );
            }
        }
    }

    Ok(())
}

/// Resolve a workspace root from the CLI flag, else the current directory.
fn resolve_workspace_root(flag: Option<PathBuf>) -> Result<PathBuf> {
    let raw = match flag {
        Some(p) => p,
        None => std::env::current_dir()?,
    };
    // Canonicalize so the tree being written is named, not implied by
    // cwd. The library refuses writes outside this root regardless.
    std::fs::canonicalize(&raw)
        .with_context(|| format!("resolving workspace root {}", raw.display()))
}

/// The run-scoped settings a `--force` flag decides.
fn clobber_settings(force: bool) -> x0k_tangle::TangleSettings {
    x0k_tangle::TangleSettings {
        clobber: if force {
            x0k_tangle::ClobberPolicy::Force
        } else {
            x0k_tangle::ClobberPolicy::Refuse
        },
        ..Default::default()
    }
}

/// Pretty-print a `WorkspaceTangleReport` to stderr.
fn print_workspace_summary(
    workspace_root: &std::path::Path,
    report: &x0k_tangle::WorkspaceTangleReport,
) {
    eprintln!("tangle workspace summary:");
    eprintln!("  tangled:    {}", report.tangled.len());
    eprintln!("  up-to-date: {}", report.up_to_date.len());
    eprintln!("  errored:    {}", report.errored.len());

    for tr in &report.tangled {
        let rel_source = tr
            .source_path
            .strip_prefix(workspace_root)
            .unwrap_or(&tr.source_path)
            .display();
        let total_outputs = tr.identity_outputs.len() + tr.pipeline_outputs.len();
        let first = tr
            .identity_outputs
            .first()
            .map(|o| o.path.clone())
            .or_else(|| tr.pipeline_outputs.first().map(|o| o.path.clone()));
        if let Some(first) = first {
            let rel_first = first
                .strip_prefix(workspace_root)
                .unwrap_or(&first)
                .display()
                .to_string();
            if total_outputs > 1 {
                eprintln!(
                    "  {} → {} (+{} more)",
                    rel_source,
                    rel_first,
                    total_outputs - 1
                );
            } else {
                eprintln!("  {} → {}", rel_source, rel_first);
            }
        } else {
            eprintln!("  {} → (no outputs)", rel_source);
        }
    }

    for (path, err) in &report.errored {
        let rel = path.strip_prefix(workspace_root).unwrap_or(path).display();
        eprintln!("  ERROR {}: {}", rel, err);
    }
}

/// The note `check` prints for an edge that leaves the set.
///
/// The set is whatever the paths on the command line contain, and nothing
/// beyond it is knowable from here: not whether a wider corpus exists, not
/// whether this tree was projected out of one. So the note names the
/// situation and stops. A note that instead told the reader their edge
/// pointed into "the corpus this was projected from" would be true of one
/// repository and read as a misconfiguration to everyone else.
fn dangling_note(source: &str, predicate: &str, target: impl std::fmt::Display) -> String {
    format!("{source}: note: edge `{predicate}` → `{target}` names no document under the paths scanned")
}

/// What `check` says about the reference half of a clean run.
///
/// The counts are load-bearing, and they are separate because they are
/// separate claims. Zero is a real and common answer for either — a
/// directory of decision documents declares no chunks, and most
/// documents that do declare chunks name no source file — and each has
/// to read as zero rather than as a pass, because the shape that
/// produces it is also the shape a broken walk produces.
fn references_verdict(chunked_documents: usize, source_refs: usize) -> String {
    if chunked_documents == 0 {
        return "no chunk references to check".to_string();
    }
    let docs = match chunked_documents {
        1 => "1 document with chunks".to_string(),
        n => format!("{n} documents with chunks"),
    };
    let sources = match source_refs {
        0 => "no from= source references declared".to_string(),
        1 => "1 from= source reference resolves".to_string(),
        n => format!("{n} from= source references resolve"),
    };
    format!("splice references resolve in {docs}, {sources}")
}

/// What `tangle` says about a document it was named and cannot write from.
fn nothing_to_write(path: &Path, chunks: usize) -> String {
    format!(
        "{}: declares {chunks} chunk(s) and no tangle target \
         (tangle.root, tangle.crate, tangle.roots, or pipelines:); nothing to write",
        path.display()
    )
}

/// Every `.md` under `paths`, deduplicated and ordered: a file is taken
/// as given, a directory is walked.
///
/// This step finds files and nothing else. What a verb *does* with a
/// document is decided from its parse, below, so that the answer cannot
/// depend on whether the reader named the file or the directory holding
/// it.
fn markdown_under(paths: &[PathBuf]) -> Vec<PathBuf> {
    let mut found = Vec::new();
    for path in paths {
        if path.is_file() {
            if is_markdown(path) {
                found.push(path.clone());
            }
        } else if path.is_dir() {
            for entry in walkdir::WalkDir::new(path)
                .into_iter()
                .filter_map(|e| e.ok())
            {
                if is_markdown(entry.path()) {
                    found.push(entry.path().to_path_buf());
                }
            }
        }
    }
    found.sort();
    // Overlapping arguments (`check corpus corpus/implementation`) reach
    // one file twice, and a document counted twice collides with itself
    // on its own id.
    let mut seen = std::collections::HashSet::new();
    found.retain(|p| seen.insert(p.canonicalize().unwrap_or_else(|_| p.clone())));
    found
}

fn is_markdown(path: &Path) -> bool {
    path.extension().is_some_and(|e| e == "md")
}

/// What a document declares about itself, read off its parse.
struct Declares {
    /// It names somewhere to write: a `tangle:` crate or root,
    /// per-language roots, or a `pipelines:` block. The same predicate
    /// `tangle_document` applies before it does any work.
    target: bool,
    /// It has a chunk to fill from source (`from=`), which is what
    /// `sync` is about.
    fills: bool,
    /// How many chunks it declares — the number that makes "nothing to
    /// write" worth saying out loud instead of reporting as a zero.
    chunks: usize,
}

fn declares(path: &Path) -> Declares {
    let Ok(content) = std::fs::read_to_string(path) else {
        return Declares { target: false, fills: false, chunks: 0 };
    };
    let Ok(parsed) = x0k_tangle::parser::parse_document(&content) else {
        return Declares { target: false, fills: false, chunks: 0 };
    };
    Declares {
        target: parsed.tangle_crate.is_some()
            || parsed.tangle_root.is_some()
            || !parsed.tangle_roots.is_empty()
            || !parsed.pipelines.is_empty(),
        fills: parsed
            .chunks
            .values()
            .flatten()
            .any(|chunk| chunk.from.is_some()),
        chunks: parsed.chunks.len(),
    }
}

fn discover_documents_any(paths: &[PathBuf]) -> Result<Vec<PathBuf>> {
    let named = named_files(paths);
    Ok(markdown_under(paths)
        .into_iter()
        .filter(|p| {
            named.contains(p) || {
                let d = declares(p);
                d.fills || d.target
            }
        })
        .collect())
}

fn discover_documents(paths: &[PathBuf]) -> Result<Vec<PathBuf>> {
    let named = named_files(paths);
    Ok(markdown_under(paths)
        .into_iter()
        .filter(|p| named.contains(p) || declares(p).target)
        .collect())
}

/// The paths the reader named as files rather than directories.
fn named_files(paths: &[PathBuf]) -> std::collections::HashSet<PathBuf> {
    paths.iter().filter(|p| p.is_file()).cloned().collect()
}
