// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/tangle/pipeline.md — DO NOT EDIT.
//! Pipeline protocol: codegen plugins that consume named chunks from a
//! literate document and produce transformed outputs.
//!
//! See `corpora/x0k/decisions/design/corpus/literate-pipelines.md` for the design contract.
//!
//! ## Plugin contract
//!
//! A pipeline plugin implements [`TanglePipeline`]. It is pure: same
//! inputs + config produce the same outputs. The plugin never touches the
//! filesystem — it returns [`PipelineOutput`]s describing what should be
//! written, and tangle is responsible for atomic write, hash recording,
//! and the `@generated` header.
//!
//! ## Registry
//!
//! Plugins register against a [`PipelineRegistry`]. The library has no
//! plugin dependencies; the `x0k-tangle` binary wires the registry by
//! calling each first-party plugin's `register()` function. External
//! consumers (build scripts) build their own registry with only the
//! plugins they need.
//!
//! ## Frontmatter shape
//!
//! See [`x0k_folio::colophon::PipelineDecl`] for the
//! frontmatter wire format. Pipelines are declared inside the `x0k:`
//! envelope under `pipelines:`.
//!
//! ```yaml
//! x0k:
//!   pipelines:
//!     - kind: theme-codegen
//!       input: tokens                   # shorthand; long form is `inputs: { ... }`
//!       config:
//!         name: pansophia
//!         scheme: single
//! ```

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};
use std::sync::Arc;

/// A pipeline transformer. The plugin takes resolved chunks + config
/// and returns the artifacts to write. The plugin must be pure (no
/// filesystem access, no global state); tangle owns I/O.
pub trait TanglePipeline: Send + Sync {
    /// Unique identifier — matches the `kind:` field in
    /// frontmatter pipeline declarations.
    fn kind(&self) -> &str;

    /// Transform the inputs to outputs. Called with the resolved
    /// chunk content (already passed through `<<refs>>` expansion).
    fn transform(&self, ctx: &PipelineContext) -> Result<Vec<PipelineOutput>, PipelineError>;

    /// Conventional literate-source roots this plugin expects, expressed as
    /// workspace-relative path strings. Aggregated by
    /// [`crate::pipeline_runner::tangle_workspace`] into the discovery set
    /// it walks. Pipelines that don't claim roots (e.g., a pipeline only
    /// invoked programmatically) return an empty vec — the default.
    fn literate_roots(&self) -> Vec<&'static str> {
        Vec::new()
    }
}

/// Context passed to [`TanglePipeline::transform`]. Carries the
/// source-doc location (for diagnostics), workspace root (for
/// resolving outputs), the plugin's config payload, and the
/// resolved input chunks.
pub struct PipelineContext<'a> {
    /// Absolute path to the source `.md` document the pipeline runs
    /// against.
    pub source_path: &'a Path,
    /// Workspace root. Plugins emit workspace-relative paths in
    /// [`PipelineOutput::path`]; tangle joins them against this when
    /// writing.
    pub workspace_root: &'a Path,
    /// The pipeline's `config:` block from the frontmatter, captured
    /// as untyped JSON. Plugins deserialize this into their own typed
    /// shape via `serde_json`.
    pub config: &'a serde_json::Value,
    /// Resolved chunk inputs, keyed by the plugin-parameter name
    /// declared in the frontmatter `inputs:` map. For single-input
    /// plugins, the shorthand `input: <name>` normalizes to the
    /// canonical `"default"` key.
    pub inputs: &'a HashMap<String, ChunkInput>,
    /// The document's full parsed chunk graph, keyed by chunk name
    /// with one entry per language variant. Identity-tangle and any
    /// other pipeline that needs to walk the doc beyond the declared
    /// `inputs:` (e.g., to resolve `<<refs>>` across the whole graph)
    /// reads through this. Plugins that work off `inputs` alone may
    /// ignore it.
    pub all_chunks: &'a HashMap<String, Vec<crate::chunk::Chunk>>,
    /// Chunk names in declaration order — the order they appear in
    /// the source `.md`. Identity tangling consumes this so the
    /// emitted output's chunk concatenation matches the doc's
    /// authoring order (not alphabetical). Plugins that don't care
    /// about order may ignore it.
    pub chunk_order: &'a [String],
}

/// One resolved input. A chunk may have multiple language variants
/// (e.g., one rust + one typescript fence with the same `#name`); the
/// pipeline picks which variants it consumes.
#[derive(Debug, Clone)]
pub struct ChunkInput {
    /// All variants of this chunk by source-document fence-language.
    pub variants: Vec<ChunkVariant>,
}

/// One language variant of a chunk. Content has already been passed
/// through `<<chunk-ref>>` expansion, so the pipeline gets the same
/// final string identity-tangle would write.
#[derive(Debug, Clone)]
pub struct ChunkVariant {
    /// Fence info-string language token, e.g. `"toml"`, `"rust"`.
    /// Empty string when the source fence had no language.
    pub lang: String,
    /// Final expanded content. Multi-body chunks (multiple fences
    /// with the same `#name`) are already concatenated.
    pub content: String,
}

/// Style of `@generated` comment header tangle prepends to the
/// output. `None` means the plugin's content is written verbatim —
/// useful for binary outputs, JSON manifests, or files whose syntax
/// can't host comments.
#[derive(Debug, Clone, Copy)]
pub enum CommentStyle {
    /// Line-comment marker (`"//"`, `"#"`, `";"`, `"%"`, `"!"`).
    Line(&'static str),
    /// Block-comment open/close pair (`("/*", "*/")`, `("(*", "*)")`).
    Block(&'static str, &'static str),
}

/// One output file the pipeline wants tangle to write.
pub struct PipelineOutput {
    /// Workspace-relative (or absolute) path. Relative paths are
    /// joined against [`PipelineContext::workspace_root`].
    pub path: PathBuf,
    /// File body. Tangle prepends the `@generated` header when
    /// `header_comment_style` is `Some`, then writes verbatim.
    pub content: Vec<u8>,
    /// How to format the `@generated` header. `None` skips it
    /// (binary outputs, content-defining files).
    pub header_comment_style: Option<CommentStyle>,
}

/// What the bytes at an output path are, relative to what this
/// document last wrote there.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputProvenance {
    /// Nothing on disk: a first tangle, a `git clean`, a deleted
    /// output. There is nothing to destroy.
    Absent,
    /// Disk matches the hash the sidecar recorded for this path. The
    /// bytes there are the ones we last wrote, so they are ours to
    /// replace with whatever the document now says.
    Ours,
    /// Disk already holds exactly the bytes about to be written.
    /// Whoever put them there, the write changes nothing.
    AlreadyCurrent,
    /// A file is on disk and no sidecar entry claims the path. Either
    /// an existing file is being brought under literate authoring or
    /// a sidecar was lost; both are legitimate and the two are
    /// indistinguishable from here.
    Unrecorded,
    /// A file is on disk, the sidecar recorded different bytes for it,
    /// and the bytes about to be written differ again. What is there
    /// did not come from this document, and writing would destroy it.
    Foreign,
}

/// Classify one output path from three content hashes: `recorded` as
/// the sidecar has it (`None` when no entry claims the path),
/// `on_disk` as the file reads now (`None` when there is no file),
/// and `about_to_write` for the bytes this run composed.
pub fn classify_output(
    recorded: Option<&str>,
    on_disk: Option<&str>,
    about_to_write: &str,
) -> OutputProvenance {
    let Some(disk) = on_disk else {
        return OutputProvenance::Absent;
    };
    if recorded == Some(disk) {
        OutputProvenance::Ours
    } else if disk == about_to_write {
        OutputProvenance::AlreadyCurrent
    } else if recorded.is_none() {
        OutputProvenance::Unrecorded
    } else {
        OutputProvenance::Foreign
    }
}

/// What a run does when an output holds bytes it did not write.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClobberPolicy {
    /// Refuse the document rather than overwrite content it did not
    /// produce. The default.
    #[default]
    Refuse,
    /// Overwrite regardless: the operator has said the bytes on disk
    /// are expendable.
    Force,
}

/// The outputs of one document that a write would have destroyed.
///
/// Every offending path, not the first. Someone who hand-edited one
/// generated file has usually hand-edited its neighbours, and a
/// refusal that reveals them one run at a time is a refusal they learn
/// to route around.
#[derive(Debug, Clone)]
pub struct ClobberRefusal {
    /// The literate document whose tangle was refused.
    pub source_doc: PathBuf,
    /// Every output of that document holding foreign content.
    pub paths: Vec<PathBuf>,
}

impl fmt::Display for ClobberRefusal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(
            f,
            "tangle refused to overwrite {} file(s) it did not write:",
            self.paths.len()
        )?;
        for p in &self.paths {
            writeln!(f, "  {}", p.display())?;
        }
        writeln!(
            f,
            "\nEach differs from what tangling {} last produced, so it was\n\
             edited by hand or by another tool, and tangling would destroy that.\n\
             \n  \
             - to keep the change: move it into the document's chunks, then tangle\n  \
             - to discard it:      restore the file from version control, then tangle\n  \
             - to overwrite it:    re-run with --force",
            self.source_doc.display()
        )
    }
}

impl std::error::Error for ClobberRefusal {}

/// Screen one document's outputs before any of them is written.
///
/// Returns the paths that warrant an `Unrecorded` warning, leaving the
/// caller to choose how to say it. Errors — before any write — when
/// the policy is [`ClobberPolicy::Refuse`] and any output holds
/// foreign content.
pub fn guard_outputs<'a>(
    source_doc: &Path,
    outputs: impl IntoIterator<Item = (&'a Path, OutputProvenance)>,
    policy: ClobberPolicy,
) -> Result<Vec<&'a Path>, ClobberRefusal> {
    let mut unrecorded = Vec::new();
    let mut clobbered = Vec::new();
    for (path, provenance) in outputs {
        match provenance {
            OutputProvenance::Unrecorded => unrecorded.push(path),
            OutputProvenance::Foreign if policy == ClobberPolicy::Refuse => {
                clobbered.push(path.to_path_buf());
            }
            _ => {}
        }
    }
    if clobbered.is_empty() {
        Ok(unrecorded)
    } else {
        Err(ClobberRefusal {
            source_doc: source_doc.to_path_buf(),
            paths: clobbered,
        })
    }
}

/// Pipeline-side failure. Tangle promotes this into the top-level
/// `TangleError` so the operator sees one error stream regardless of
/// which side failed.
#[derive(Debug)]
pub struct PipelineError {
    pub kind: PipelineErrorKind,
    pub message: String,
}

#[derive(Debug)]
pub enum PipelineErrorKind {
    /// The `inputs:` map referenced a chunk by name, but the
    /// document didn't define one (and tangle reported it as
    /// missing).
    MissingInput { name: String },
    /// The `config:` payload didn't deserialize into the plugin's
    /// expected shape.
    InvalidConfig,
    /// Any other plugin-side failure — bad TOML, unknown role,
    /// etc. The `message` carries the human-readable detail.
    TransformFailed,
}

impl fmt::Display for PipelineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.kind {
            PipelineErrorKind::MissingInput { name } => {
                write!(f, "missing input chunk `{name}`: {}", self.message)
            }
            PipelineErrorKind::InvalidConfig => {
                write!(f, "invalid pipeline config: {}", self.message)
            }
            PipelineErrorKind::TransformFailed => {
                write!(f, "pipeline transform failed: {}", self.message)
            }
        }
    }
}

impl std::error::Error for PipelineError {}

impl PipelineError {
    pub fn missing_input(name: impl Into<String>) -> Self {
        let n = name.into();
        Self {
            message: format!("expected `{n}` to be declared in `inputs:`"),
            kind: PipelineErrorKind::MissingInput { name: n },
        }
    }

    pub fn invalid_config(message: impl Into<String>) -> Self {
        Self {
            kind: PipelineErrorKind::InvalidConfig,
            message: message.into(),
        }
    }

    pub fn transform_failed(message: impl Into<String>) -> Self {
        Self {
            kind: PipelineErrorKind::TransformFailed,
            message: message.into(),
        }
    }
}

/// Registry of pipeline plugins.
///
/// The library ships a default registry that already contains
/// [`crate::IdentityPipeline`] — every registry has identity tangling
/// for free, because identity-tangle is itself a plugin in the unified
/// dispatch model. First-party plugins (theme-codegen, future
/// service-codegen, ontology vocab) are registered on top by the
/// `x0k-tangle-bundle` crate's `default_registry()` factory. Build
/// scripts that want only a subset construct their own registry via
/// [`Self::empty`] or [`Self::new`] + selective `register()` calls.
#[derive(Clone)]
pub struct PipelineRegistry {
    pipelines: HashMap<String, Arc<dyn TanglePipeline>>,
}

impl Default for PipelineRegistry {
    fn default() -> Self {
        let mut registry = Self::empty();
        registry.register(crate::identity_pipeline::IdentityPipeline);
        registry
    }
}

impl PipelineRegistry {
    /// Alias for [`Self::default`] — every default registry already
    /// has identity tangling registered.
    pub fn new() -> Self {
        Self::default()
    }

    /// Build an empty registry with no plugins registered, not even
    /// identity. Reserved for tests and tooling that explicitly want a
    /// plugin-less surface.
    pub fn empty() -> Self {
        Self {
            pipelines: HashMap::new(),
        }
    }

    /// Register a plugin instance. Later registrations under the
    /// same `kind()` overwrite earlier ones (consumers wiring two
    /// crates that both export the same kind get the second).
    pub fn register<P: TanglePipeline + 'static>(&mut self, plugin: P) {
        let kind = plugin.kind().to_string();
        self.pipelines.insert(kind, Arc::new(plugin));
    }

    /// Look up a registered plugin by its `kind` string.
    pub fn get(&self, kind: &str) -> Option<&Arc<dyn TanglePipeline>> {
        self.pipelines.get(kind)
    }

    /// Iterate all registered kinds — useful for diagnostics and
    /// CLI help.
    pub fn kinds(&self) -> impl Iterator<Item = &str> {
        self.pipelines.keys().map(|s| s.as_str())
    }

    /// Iterate the registered plugin instances. Used by the workspace
    /// dispatcher to aggregate [`TanglePipeline::literate_roots`] into
    /// the directory-discovery set.
    pub fn iter(&self) -> impl Iterator<Item = &Arc<dyn TanglePipeline>> {
        self.pipelines.values()
    }

    /// Number of registered plugins.
    pub fn len(&self) -> usize {
        self.pipelines.len()
    }

    /// Whether the registry has any plugins.
    pub fn is_empty(&self) -> bool {
        self.pipelines.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A pipeline that mirrors its inputs back as outputs, named
    /// after the input. Useful as a fixture for end-to-end
    /// dispatcher tests. Named `MirrorPipeline` to avoid clashing
    /// with the real [`crate::IdentityPipeline`] now that identity
    /// tangling is itself a plugin.
    struct MirrorPipeline;

    impl TanglePipeline for MirrorPipeline {
        fn kind(&self) -> &str {
            "mirror"
        }

        fn transform(&self, ctx: &PipelineContext) -> Result<Vec<PipelineOutput>, PipelineError> {
            let mut outputs = Vec::new();
            let mut keys: Vec<&String> = ctx.inputs.keys().collect();
            keys.sort();
            for key in keys {
                let input = ctx
                    .inputs
                    .get(key)
                    .ok_or_else(|| PipelineError::missing_input(key.clone()))?;
                let body = input
                    .variants
                    .first()
                    .map(|v| v.content.clone())
                    .unwrap_or_default();
                outputs.push(PipelineOutput {
                    path: PathBuf::from(format!("out/{key}.txt")),
                    content: body.into_bytes(),
                    header_comment_style: Some(CommentStyle::Line("#")),
                });
            }
            Ok(outputs)
        }
    }

    #[test]
    fn register_and_get_round_trips() {
        // `empty()` (NOT `default()`) so this test sees a blank
        // registry — `default()` ships with `IdentityPipeline`
        // pre-registered.
        let mut registry = PipelineRegistry::empty();
        assert!(registry.is_empty());
        registry.register(MirrorPipeline);
        assert_eq!(registry.len(), 1);
        let p = registry.get("mirror").expect("mirror present");
        assert_eq!(p.kind(), "mirror");
        assert!(registry.get("missing-kind").is_none());
    }

    #[test]
    fn default_registry_has_identity_pipeline() {
        let registry = PipelineRegistry::default();
        assert!(!registry.is_empty(), "default registry should have identity");
        let p = registry
            .get(crate::IDENTITY_KIND)
            .expect("identity-tangle present in default registry");
        assert_eq!(p.kind(), crate::IDENTITY_KIND);
    }

    #[test]
    fn mirror_pipeline_returns_inputs_as_outputs() {
        let pipeline = MirrorPipeline;
        let mut inputs: HashMap<String, ChunkInput> = HashMap::new();
        inputs.insert(
            "default".to_string(),
            ChunkInput {
                variants: vec![ChunkVariant {
                    lang: "toml".to_string(),
                    content: "[theme]\nid = \"test\"\n".to_string(),
                }],
            },
        );
        let workspace = PathBuf::from("/tmp/ws");
        let source = workspace.join("doc.md");
        let cfg = serde_json::json!({});
        let empty_chunks: HashMap<String, Vec<crate::chunk::Chunk>> = HashMap::new();
        let empty_order: Vec<String> = Vec::new();
        let ctx = PipelineContext {
            source_path: &source,
            workspace_root: &workspace,
            config: &cfg,
            inputs: &inputs,
            all_chunks: &empty_chunks,
            chunk_order: &empty_order,
        };
        let outs = pipeline.transform(&ctx).expect("transform");
        assert_eq!(outs.len(), 1);
        assert_eq!(outs[0].path, PathBuf::from("out/default.txt"));
        let body = std::str::from_utf8(&outs[0].content).unwrap();
        assert!(body.contains("[theme]"));
        assert!(matches!(
            outs[0].header_comment_style,
            Some(CommentStyle::Line("#"))
        ));
    }

    #[test]
    fn registry_overwrites_on_duplicate_kind() {
        struct OtherMirror;
        impl TanglePipeline for OtherMirror {
            fn kind(&self) -> &str {
                "mirror"
            }
            fn transform(
                &self,
                _ctx: &PipelineContext,
            ) -> Result<Vec<PipelineOutput>, PipelineError> {
                Ok(vec![])
            }
        }
        let mut registry = PipelineRegistry::empty();
        registry.register(MirrorPipeline);
        registry.register(OtherMirror);
        // Still one entry; the second registration overwrote the first.
        assert_eq!(registry.len(), 1);
    }

    // The clobber guard, one test per failure mode it was designed
    // against. `h(..)` stands in for a content hash; the guard never
    // computes one, it only compares them.

    #[test]
    fn first_tangle_writes_when_nothing_is_on_disk() {
        // No sidecar entry, no file. The overwhelmingly common shape of
        // a new output, and the one a guard must never block.
        let p = PathBuf::from("src/new.rs");
        let v = classify_output(None, None, "new");
        assert_eq!(v, OutputProvenance::Absent);
        let warn = guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Refuse)
            .expect("a first tangle must not be refused");
        assert!(warn.is_empty());
    }

    #[test]
    fn document_changed_so_the_output_changes() {
        // The check is disk against what we last wrote, not against
        // what we are about to write. An edited document produces
        // different bytes every time and must still tangle.
        let p = PathBuf::from("src/lib.rs");
        let v = classify_output(Some("old"), Some("old"), "new");
        assert_eq!(v, OutputProvenance::Ours);
        assert!(
            guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Refuse).is_ok()
        );
    }

    #[test]
    fn hand_edited_output_is_caught() {
        // The reported defect: `# HAND EDIT` added to a generated file,
        // re-tangled, gone with no message and exit 0.
        let p = PathBuf::from("src/lib.rs");
        let v = classify_output(Some("ours"), Some("hand-edited"), "new");
        assert_eq!(v, OutputProvenance::Foreign);
        let err = guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Refuse)
            .expect_err("a hand edit must stop the write");
        assert_eq!(err.paths, vec![p]);
        let msg = err.to_string();
        assert!(msg.contains("src/lib.rs"), "{msg}");
        assert!(msg.contains("--force"), "{msg}");
    }

    #[test]
    fn a_write_that_changes_nothing_is_not_a_clobber() {
        // Disk disagrees with the sidecar but agrees with what we are
        // about to write — someone applied our own bytes by hand, or a
        // sidecar went stale. Nothing is destroyed, so nothing is
        // refused; this is what keeps a re-tangle-and-diff gate running.
        let p = PathBuf::from("src/lib.rs");
        let v = classify_output(Some("stale"), Some("new"), "new");
        assert_eq!(v, OutputProvenance::AlreadyCurrent);
        assert!(
            guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Refuse).is_ok()
        );
    }

    #[test]
    fn an_unclaimed_file_warns_rather_than_refusing() {
        // Adopting an existing hand-written file into a document, or a
        // lost sidecar. Indistinguishable from here, and refusing would
        // block a workflow the substrate asks people to perform.
        let p = PathBuf::from("src/legacy.rs");
        let v = classify_output(None, Some("theirs"), "ours");
        assert_eq!(v, OutputProvenance::Unrecorded);
        let warn = guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Refuse)
            .expect("adoption must not be refused");
        assert_eq!(warn, vec![p.as_path()]);
    }

    #[test]
    fn a_deleted_output_regenerates() {
        // `git clean`, a fresh checkout that gitignores the projection,
        // an output the author removed on purpose.
        assert_eq!(
            classify_output(Some("ours"), None, "new"),
            OutputProvenance::Absent
        );
    }

    #[test]
    fn force_overwrites_foreign_content() {
        let p = PathBuf::from("src/lib.rs");
        let v = classify_output(Some("ours"), Some("hand-edited"), "new");
        assert!(
            guard_outputs(Path::new("doc.md"), [(p.as_path(), v)], ClobberPolicy::Force).is_ok()
        );
    }

    #[test]
    fn one_clobber_refuses_the_whole_document() {
        // All-or-nothing: three outputs, one foreign. The refusal names
        // every offender and the caller writes none of them, rather than
        // leaving two thirds of a module on disk.
        let a = PathBuf::from("src/a.rs");
        let b = PathBuf::from("src/b.rs");
        let c = PathBuf::from("src/c.rs");
        let outputs = [
            (a.as_path(), classify_output(Some("x"), Some("x"), "x2")),
            (b.as_path(), classify_output(Some("y"), Some("edited"), "y2")),
            (c.as_path(), classify_output(Some("z"), Some("also-edited"), "z2")),
        ];
        let err = guard_outputs(Path::new("doc.md"), outputs, ClobberPolicy::Refuse)
            .expect_err("a foreign output must stop the document");
        assert_eq!(err.paths, vec![b, c]);
    }

    #[test]
    fn refuse_is_the_default_policy() {
        assert_eq!(ClobberPolicy::default(), ClobberPolicy::Refuse);
    }
}
