// @generated by x0k-tangle (pipeline: identity-tangle) from implementation/tangle/source-refs.md — DO NOT EDIT.
use anyhow::{bail, Result};
use tree_sitter::{Node, Parser, Tree};
use x0k_syntax::Language as FenceLanguage;

#[derive(Debug, Clone)]
pub struct SymbolSpan {
    pub name: String,
    pub body: String,
    pub start_line: usize,
    pub end_line: usize,
    pub byte_start: usize,
    pub byte_end: usize,
}

/// The languages symbol extraction can walk.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SymbolLanguage {
    Rust,
    /// TypeScript, whose grammar also parses plain JavaScript.
    TypeScript,
    /// TSX, which additionally parses JSX.
    Tsx,
    Python,
    Julia,
}

/// The set `for_lang` names when it refuses, spelled as fence tags.
const SUPPORTED_LANGS: &str = "rust, typescript, javascript, tsx, python, julia";

impl SymbolLanguage {
    /// Resolve a chunk's declared fence language, or refuse by name.
    pub fn for_lang(lang: Option<&str>) -> Result<Self> {
        let Some(tag) = lang else {
            bail!("symbol extraction needs a language on the fence (one of {SUPPORTED_LANGS})");
        };
        if is_julia_tag(tag) {
            return Ok(Self::Julia);
        }
        match FenceLanguage::from_str(tag) {
            Some(FenceLanguage::Rust) => Ok(Self::Rust),
            Some(FenceLanguage::Typescript) => Ok(Self::TypeScript),
            Some(FenceLanguage::Tsx) => Ok(Self::Tsx),
            Some(FenceLanguage::Python) => Ok(Self::Python),
            _ => bail!("symbol extraction supports {SUPPORTED_LANGS} (this chunk is `{tag}`)"),
        }
    }

    fn grammar(self) -> tree_sitter::Language {
        match self {
            Self::Rust => tree_sitter_rust::LANGUAGE.into(),
            Self::TypeScript => tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
            Self::Tsx => tree_sitter_typescript::LANGUAGE_TSX.into(),
            Self::Python => tree_sitter_python::LANGUAGE.into(),
            Self::Julia => tree_sitter_julia::LANGUAGE.into(),
        }
    }
}

/// The one place the Julia fence tag is spelled. `x0k-syntax`'s vocabulary
/// has no Julia — nothing highlights it — so the two passes that walk a
/// Julia tree recognise the tag themselves.
pub(crate) fn is_julia_tag(tag: &str) -> bool {
    matches!(tag.to_ascii_lowercase().as_str(), "julia" | "jl")
}

pub fn extract_symbol_in(
    source: &str,
    symbol_path: &str,
    lang: SymbolLanguage,
) -> Result<SymbolSpan> {
    let tree = parse(source, lang)?;
    let query = parse_symbol_query(symbol_path, lang);
    let root = tree.root_node();

    let mut matches = Vec::new();
    match lang {
        SymbolLanguage::Rust => {
            collect_matching_symbols(root, source, &query, 0, None, &mut matches)
        }
        SymbolLanguage::TypeScript | SymbolLanguage::Tsx => {
            collect_matching_ts_symbols(root, source, &query, 0, None, &mut matches)
        }
        SymbolLanguage::Python => {
            collect_matching_py_symbols(root, source, &query, 0, None, &mut matches)
        }
        SymbolLanguage::Julia => {
            collect_matching_jl_symbols(root, source, &query, 0, None, &mut matches)
        }
    }
    pick_match(matches, symbol_path)
}

/// A parsed `symbol=`: the segments to descend, and the trait a Rust
/// `<Type as Trait>::method` path pins the impl block to.
struct SymbolQuery<'p> {
    parts: Vec<&'p str>,
    trait_bound: Option<&'p str>,
}

fn parse_symbol_query(symbol_path: &str, lang: SymbolLanguage) -> SymbolQuery<'_> {
    if lang == SymbolLanguage::Rust {
        if let Some(query) = parse_qualified_path(symbol_path) {
            return query;
        }
    }
    SymbolQuery {
        parts: split_symbol_path(symbol_path, lang),
        trait_bound: None,
    }
}

fn split_symbol_path(symbol_path: &str, lang: SymbolLanguage) -> Vec<&str> {
    match lang {
        SymbolLanguage::Rust => symbol_path.split("::").collect(),
        SymbolLanguage::Julia => split_julia_path(symbol_path),
        _ => symbol_path
            .split(['.', ':'])
            .filter(|part| !part.is_empty())
            .collect(),
    }
}

fn split_julia_path(path: &str) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut depth = 0usize;
    let mut start = 0usize;
    for (i, c) in path.char_indices() {
        match c {
            '(' | '{' | '[' => depth += 1,
            ')' | '}' | ']' => depth = depth.saturating_sub(1),
            '.' if depth == 0 => {
                parts.push(&path[start..i]);
                start = i + c.len_utf8();
            }
            _ => {}
        }
    }
    parts.push(&path[start..]);
    parts.into_iter().filter(|part| !part.is_empty()).collect()
}

/// `<Pairs<'_, R> as fmt::Display>::fmt` — the type, the trait that
/// selects one impl of it, and the path below.
fn parse_qualified_path(path: &str) -> Option<SymbolQuery<'_>> {
    let inner = path.strip_prefix('<')?;
    let close = closing_angle(inner)?;
    let (qualifier, rest) = inner.split_at(close);
    let (ty, bound) = split_at_as(qualifier)?;
    let mut parts = vec![ty];
    parts.extend(rest.strip_prefix(">::")?.split("::"));
    Some(SymbolQuery {
        parts,
        trait_bound: Some(bound),
    })
}

/// The `>` that closes the qualifier, skipping the ones inside it.
fn closing_angle(s: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (i, c) in s.char_indices() {
        match c {
            '<' => depth += 1,
            '>' if depth == 0 => return Some(i),
            '>' => depth -= 1,
            _ => {}
        }
    }
    None
}

fn split_at_as(qualifier: &str) -> Option<(&str, &str)> {
    let bytes = qualifier.as_bytes();
    let mut depth = 0usize;
    for i in 0..bytes.len() {
        match bytes[i] {
            b'<' => depth += 1,
            b'>' => depth = depth.saturating_sub(1),
            b' ' if depth == 0 && qualifier[i..].starts_with(" as ") => {
                return Some((qualifier[..i].trim(), qualifier[i + 4..].trim()));
            }
            _ => {}
        }
    }
    None
}

struct Candidate {
    span: SymbolSpan,
    /// The enclosing impl / class / module, spelled as the source spells it.
    scope: Option<String>,
    /// A `symbol=` naming this candidate and no other, where the language
    /// has such a spelling.
    select: Option<String>,
    kind: MatchKind,
}

#[derive(PartialEq, Eq, Clone, Copy)]
enum MatchKind {
    /// A declared item: `fn`, `struct`, `def`, `struct … end`.
    Item,
    /// The `impl` block a bare type name also names.
    ImplBlock,
}

fn pick_match(mut matches: Vec<Candidate>, symbol_path: &str) -> Result<SymbolSpan> {
    if matches.iter().any(|c| c.kind == MatchKind::Item) {
        matches.retain(|c| c.kind == MatchKind::Item);
    }
    match matches.len() {
        0 => bail!("symbol '{symbol_path}' not found"),
        1 => Ok(matches.remove(0).span),
        _ => bail!("{}", ambiguity_report(&matches, symbol_path)),
    }
}

fn ambiguity_report(matches: &[Candidate], symbol_path: &str) -> String {
    let mut report = format!(
        "symbol '{symbol_path}' is ambiguous — {} definitions match:",
        matches.len()
    );
    for m in matches {
        report.push_str(&format!("\n  line {}", m.span.start_line));
        if let Some(scope) = &m.scope {
            report.push_str(&format!(" in `{scope}`"));
        }
        if let Some(select) = &m.select {
            report.push_str(&format!(" — select it with symbol=\"{select}\""));
        }
    }
    if matches.iter().all(|m| m.select.is_none()) {
        report.push_str("\n  no spelling names one of these alone; reference the enclosing item");
    }
    report
}

fn matched(span: SymbolSpan, enclosing: Option<&Enclosing>, kind: MatchKind) -> Candidate {
    let select = enclosing
        .and_then(|e| e.qualifier.as_deref())
        .map(|qualifier| format!("{qualifier}::{}", span.name));
    Candidate {
        scope: enclosing.and_then(|e| e.header.clone()),
        select,
        span,
        kind,
    }
}

/// What a descent step knows about the scope it entered: how to name it in
/// a report, and how a `symbol=` would pin it.
#[derive(Default, Clone)]
struct Enclosing {
    header: Option<String>,
    qualifier: Option<String>,
}

pub fn list_symbols_in(source: &str, lang: SymbolLanguage) -> Result<Vec<SymbolSpan>> {
    let tree = parse(source, lang)?;
    let root = tree.root_node();
    let mut symbols = Vec::new();
    match lang {
        SymbolLanguage::Rust => collect_all_symbols(root, source, &[], &mut symbols),
        SymbolLanguage::TypeScript | SymbolLanguage::Tsx => {
            collect_all_ts_symbols(root, source, &[], &mut symbols)
        }
        SymbolLanguage::Python => collect_all_py_symbols(root, source, &[], &mut symbols),
        SymbolLanguage::Julia => collect_all_jl_symbols(root, source, &[], &mut symbols),
    }
    Ok(symbols)
}

/// Rust-pinned [`extract_symbol_in`]: for a caller holding source with no
/// declared language to consult. Anything reading a `from=` chunk has the
/// chunk's language and passes it.
pub fn extract_symbol(source: &str, symbol_path: &str) -> Result<SymbolSpan> {
    extract_symbol_in(source, symbol_path, SymbolLanguage::Rust)
}

/// Rust-pinned [`list_symbols_in`], paired with [`extract_symbol`].
pub fn list_symbols(source: &str) -> Result<Vec<SymbolSpan>> {
    list_symbols_in(source, SymbolLanguage::Rust)
}

fn parse(source: &str, lang: SymbolLanguage) -> Result<Tree> {
    let mut parser = Parser::new();
    parser
        .set_language(&lang.grammar())
        .map_err(|e| anyhow::anyhow!("tree-sitter language error: {}", e))?;
    parser
        .parse(source, None)
        .ok_or_else(|| anyhow::anyhow!("tree-sitter parse failed"))
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

fn named_child_text(node: Node, source: &str) -> Option<String> {
    node.child_by_field_name("name")
        .map(|child| node_text(child, source).to_string())
        .or_else(|| {
            node.children(&mut node.walk())
                .find(|child| {
                    child.kind() == "identifier" || child.kind() == "type_identifier"
                })
                .map(|child| node_text(child, source).to_string())
        })
}

fn collapse_ws(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// What precedes an item and belongs to it.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Leading {
    /// Nothing to attach: the item node already contains everything a
    /// reader wrote — a Python `decorated_definition`, a TS `export`.
    None,
    /// `#[derive(…)]` attributes and `///` outer doc comments.
    RustAttrs,
    /// The string literal Julia binds to the definition beneath it.
    JuliaDocstring,
}

fn span_start<'t>(node: Node<'t>, source: &str, leading: Leading) -> Node<'t> {
    let mut start = node;
    while let Some(prev) = start.prev_sibling() {
        if !attaches(prev, start, source, leading) {
            break;
        }
        start = prev;
    }
    start
}

fn attaches(prev: Node, item: Node, source: &str, leading: Leading) -> bool {
    let gap = &source[prev.end_byte()..item.start_byte()];
    let breaks = gap.matches('\n').count() + usize::from(node_text(prev, source).ends_with('\n'));
    if breaks > 1 {
        return false;
    }
    match leading {
        Leading::None => false,
        // `outer` is the grammar's own field for `///` and `/** */`, which
        // is exactly the distinction wanted: `//!` documents the file.
        Leading::RustAttrs => {
            prev.kind() == "attribute_item"
                || (matches!(prev.kind(), "line_comment" | "block_comment")
                    && prev.child_by_field_name("outer").is_some())
        }
        Leading::JuliaDocstring => prev.kind() == "string_literal",
    }
}

fn make_span(name: String, node: Node, source: &str, leading: Leading) -> SymbolSpan {
    let start = span_start(node, source, leading);
    SymbolSpan {
        name,
        body: source[start.start_byte()..node.end_byte()].to_string(),
        start_line: start.start_position().row + 1,
        end_line: node.end_position().row + 1,
        byte_start: start.start_byte(),
        byte_end: node.end_byte(),
    }
}

fn impl_type_name(node: Node, source: &str) -> Option<String> {
    node.child_by_field_name("type")
        .map(|t| node_text(t, source).to_string())
}

fn impl_trait_name(node: Node, source: &str) -> Option<String> {
    node.child_by_field_name("trait")
        .map(|t| node_text(t, source).to_string())
}

/// `Op<R>` → `Op`: the name the author writes in prose.
fn base_type_name(ty: &str) -> &str {
    ty.split('<').next().unwrap_or(ty).trim()
}

fn trait_matches(bound: Option<&str>, actual: Option<&str>) -> bool {
    let Some(bound) = bound else {
        return true;
    };
    let Some(actual) = actual else {
        return false;
    };
    actual == bound || last_segment(actual) == last_segment(bound)
}

fn last_segment(path: &str) -> &str {
    if path.contains('<') {
        return path;
    }
    path.rsplit("::").next().unwrap_or(path)
}

fn impl_header(node: Node, source: &str) -> String {
    let end = node
        .child_by_field_name("body")
        .map_or(node.end_byte(), |body| body.start_byte());
    collapse_ws(&source[node.start_byte()..end])
}

fn collect_matching_symbols(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    enclosing: Option<&Enclosing>,
    matches: &mut Vec<Candidate>,
) {
    if depth >= query.parts.len() {
        return;
    }
    let target = query.parts[depth];
    let is_last = depth == query.parts.len() - 1;

    for child in node.children(&mut node.walk()) {
        match child.kind() {
            "function_item" | "struct_item" | "enum_item" | "type_item" | "const_item"
            | "static_item" | "trait_item" | "macro_definition" => {
                if let Some(name) = named_child_text(child, source) {
                    if name == target && is_last {
                        let span = make_span(name, child, source, Leading::RustAttrs);
                        matches.push(matched(span, enclosing, MatchKind::Item));
                    }
                }
            }
            "impl_item" => collect_matching_impl(child, source, query, depth, matches),
            "mod_item" => collect_matching_mod(child, source, query, depth, matches),
            _ => {}
        }
    }
}

fn collect_matching_impl(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    matches: &mut Vec<Candidate>,
) {
    let Some(ty) = impl_type_name(node, source) else {
        return;
    };
    let target = query.parts[depth];
    if ty != target && base_type_name(&ty) != target {
        return;
    }
    let implemented = impl_trait_name(node, source);
    if !trait_matches(query.trait_bound, implemented.as_deref()) {
        return;
    }
    let enclosing = Enclosing {
        header: Some(impl_header(node, source)),
        qualifier: implemented.map(|t| format!("<{ty} as {t}>")),
    };
    if depth == query.parts.len() - 1 {
        let span = make_span(format!("impl {ty}"), node, source, Leading::RustAttrs);
        matches.push(matched(span, Some(&enclosing), MatchKind::ImplBlock));
    } else if let Some(body) = node.child_by_field_name("body") {
        collect_matching_symbols(body, source, query, depth + 1, Some(&enclosing), matches);
    }
}

fn collect_matching_mod(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    matches: &mut Vec<Candidate>,
) {
    let Some(name) = named_child_text(node, source) else {
        return;
    };
    if name != query.parts[depth] || depth == query.parts.len() - 1 {
        return;
    }
    let enclosing = Enclosing {
        header: Some(format!("mod {name}")),
        qualifier: None,
    };
    for child in node.children(&mut node.walk()) {
        if child.kind() == "declaration_list" {
            collect_matching_symbols(child, source, query, depth + 1, Some(&enclosing), matches);
        }
    }
}

fn collect_all_symbols(
    node: Node,
    source: &str,
    prefix: &[String],
    symbols: &mut Vec<SymbolSpan>,
) {
    for child in node.children(&mut node.walk()) {
        match child.kind() {
            "function_item" | "struct_item" | "enum_item" | "type_item" | "const_item"
            | "static_item" | "trait_item" | "macro_definition" => {
                if let Some(name) = named_child_text(child, source) {
                    let full_name = qualify(prefix, &name);
                    symbols.push(make_span(full_name, child, source, Leading::RustAttrs));
                }
            }
            "impl_item" => {
                if let Some(type_name) = impl_type_name(child, source) {
                    let mut impl_prefix = prefix.to_vec();
                    impl_prefix.push(type_name);
                    if let Some(body) = child.child_by_field_name("body") {
                        collect_all_symbols(body, source, &impl_prefix, symbols);
                    }
                }
            }
            "mod_item" => {
                if let Some(name) = named_child_text(child, source) {
                    let mut new_prefix = prefix.to_vec();
                    new_prefix.push(name);
                    for grandchild in child.children(&mut child.walk()) {
                        if grandchild.kind() == "declaration_list" {
                            collect_all_symbols(grandchild, source, &new_prefix, symbols);
                        }
                    }
                }
            }
            _ => {}
        }
    }
}

fn qualify(prefix: &[String], name: &str) -> String {
    if prefix.is_empty() {
        name.to_string()
    } else {
        format!("{}::{}", prefix.join("::"), name)
    }
}

struct TsItem<'t> {
    name: String,
    /// What a `symbol=` chunk is filled with — the `export` wrapper
    /// included, because the reader wrote it and expects to see it.
    span: Node<'t>,
    /// The scope `Outer.inner` descends into, for a class or namespace.
    body: Option<Node<'t>>,
}

fn ts_item<'t>(node: Node<'t>, source: &str) -> Option<TsItem<'t>> {
    let decl = match node.kind() {
        "export_statement" => node
            .child_by_field_name("declaration")
            .or_else(|| node.named_child(0))?,
        _ => node,
    };
    match decl.kind() {
        "function_declaration" | "generator_function_declaration" | "class_declaration"
        | "abstract_class_declaration" | "interface_declaration" | "type_alias_declaration"
        | "enum_declaration" => Some(TsItem {
            name: named_child_text(decl, source)?,
            span: node,
            body: decl.child_by_field_name("body"),
        }),
        "lexical_declaration" | "variable_declaration" => {
            // The declarator carries the name; the span is the whole
            // statement, so `const` and the `;` come along with it.
            let declarator = decl
                .children(&mut decl.walk())
                .find(|c| c.kind() == "variable_declarator")?;
            Some(TsItem {
                name: node_text(declarator.child_by_field_name("name")?, source).to_string(),
                span: node,
                body: None,
            })
        }
        "method_definition" | "public_field_definition" => Some(TsItem {
            name: node_text(decl.child_by_field_name("name")?, source).to_string(),
            span: node,
            body: None,
        }),
        _ => None,
    }
}

fn collect_matching_ts_symbols(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    enclosing: Option<&Enclosing>,
    matches: &mut Vec<Candidate>,
) {
    if depth >= query.parts.len() {
        return;
    }
    let target = query.parts[depth];
    let is_last = depth == query.parts.len() - 1;

    for child in node.children(&mut node.walk()) {
        let Some(item) = ts_item(child, source) else {
            continue;
        };
        if item.name != target {
            continue;
        }
        if is_last {
            let span = make_span(item.name, item.span, source, Leading::None);
            matches.push(matched(span, enclosing, MatchKind::Item));
        } else if let Some(body) = item.body {
            let scope = Enclosing {
                header: Some(item.name),
                qualifier: None,
            };
            collect_matching_ts_symbols(body, source, query, depth + 1, Some(&scope), matches);
        }
    }
}

fn collect_all_ts_symbols(
    node: Node,
    source: &str,
    prefix: &[String],
    symbols: &mut Vec<SymbolSpan>,
) {
    for child in node.children(&mut node.walk()) {
        let Some(item) = ts_item(child, source) else {
            continue;
        };
        let full_name = qualify(prefix, &item.name);
        symbols.push(make_span(full_name, item.span, source, Leading::None));
        if let Some(body) = item.body {
            let mut nested = prefix.to_vec();
            nested.push(item.name);
            collect_all_ts_symbols(body, source, &nested, symbols);
        }
    }
}

struct PyItem<'t> {
    name: String,
    span: Node<'t>,
    /// The class body a dotted path descends into.
    body: Option<Node<'t>>,
}

fn py_item<'t>(node: Node<'t>, source: &str) -> Option<PyItem<'t>> {
    match node.kind() {
        "decorated_definition" => {
            let inner = py_item(node.child_by_field_name("definition")?, source)?;
            Some(PyItem {
                span: node,
                ..inner
            })
        }
        "class_definition" => Some(PyItem {
            name: node_text(node.child_by_field_name("name")?, source).to_string(),
            span: node,
            body: node.child_by_field_name("body"),
        }),
        "function_definition" => Some(PyItem {
            name: node_text(node.child_by_field_name("name")?, source).to_string(),
            span: node,
            body: None,
        }),
        "expression_statement" => py_binding(node, source),
        _ => None,
    }
}

fn py_binding<'t>(node: Node<'t>, source: &str) -> Option<PyItem<'t>> {
    let assignment = node.named_child(0).filter(|c| c.kind() == "assignment")?;
    let left = assignment.child_by_field_name("left")?;
    (left.kind() == "identifier").then(|| PyItem {
        name: node_text(left, source).to_string(),
        span: node,
        body: None,
    })
}

fn py_span(name: String, node: Node, source: &str) -> SymbolSpan {
    let mut span = make_span(name, node, source, Leading::None);
    let columns = node.start_position().column;
    if columns == 0 {
        return span;
    }
    let mut out = String::new();
    for (i, line) in span.body.split('\n').enumerate() {
        if i > 0 {
            out.push('\n');
            let stripped = line
                .chars()
                .take(columns)
                .take_while(|c| *c == ' ' || *c == '\t')
                .count();
            out.push_str(&line[stripped..]);
        } else {
            out.push_str(line);
        }
    }
    span.body = out;
    span
}

fn collect_matching_py_symbols(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    enclosing: Option<&Enclosing>,
    matches: &mut Vec<Candidate>,
) {
    if depth >= query.parts.len() {
        return;
    }
    let target = query.parts[depth];
    let is_last = depth == query.parts.len() - 1;

    for child in node.children(&mut node.walk()) {
        let Some(item) = py_item(child, source) else {
            continue;
        };
        if item.name != target {
            continue;
        }
        if is_last {
            let span = py_span(item.name, item.span, source);
            matches.push(matched(span, enclosing, MatchKind::Item));
        } else if let Some(body) = item.body {
            let scope = Enclosing {
                header: Some(format!("class {}", item.name)),
                qualifier: None,
            };
            collect_matching_py_symbols(body, source, query, depth + 1, Some(&scope), matches);
        }
    }
}

fn collect_all_py_symbols(
    node: Node,
    source: &str,
    prefix: &[String],
    symbols: &mut Vec<SymbolSpan>,
) {
    for child in node.children(&mut node.walk()) {
        let Some(item) = py_item(child, source) else {
            continue;
        };
        symbols.push(py_span(qualify(prefix, &item.name), item.span, source));
        if let Some(body) = item.body {
            let mut nested = prefix.to_vec();
            nested.push(item.name);
            collect_all_py_symbols(body, source, &nested, symbols);
        }
    }
}

struct JlItem<'t> {
    name: String,
    /// The signature as written — `quadgk(f, a, b)`. Julia's methods share
    /// a name by design; this is how a `symbol=` means one of them.
    selector: Option<String>,
    span: Node<'t>,
    /// A module: Julia's one namespace, and all that `A.b` descends.
    body: Option<Node<'t>>,
}

fn jl_item<'t>(node: Node<'t>, source: &str) -> Option<JlItem<'t>> {
    match node.kind() {
        "macrocall_expression" => {
            let wrapped = node
                .children(&mut node.walk())
                .find(|c| c.kind() == "macro_argument_list")?
                .named_child(0)?;
            let inner = jl_item(wrapped, source)?;
            Some(JlItem { span: node, ..inner })
        }
        "function_definition" | "macro_definition" | "assignment" => {
            jl_signature_item(node, source)
        }
        "struct_definition" | "abstract_definition" | "primitive_definition" => Some(JlItem {
            name: jl_type_name(node, source)?,
            selector: None,
            span: node,
            body: None,
        }),
        "module_definition" => Some(JlItem {
            name: node_text(node.child_by_field_name("name")?, source).to_string(),
            selector: None,
            span: node,
            body: Some(node),
        }),
        "const_statement" => jl_const_item(node, source),
        _ => None,
    }
}

fn jl_signature_item<'t>(node: Node<'t>, source: &str) -> Option<JlItem<'t>> {
    let signature = node
        .children(&mut node.walk())
        .find(|c| c.kind() == "signature")
        .or_else(|| node.named_child(0))?;
    let call = jl_call(signature)?;
    Some(JlItem {
        name: node_text(call.named_child(0)?, source).to_string(),
        selector: Some(collapse_ws(node_text(signature, source))),
        span: node,
        body: None,
    })
}

fn jl_call<'t>(node: Node<'t>) -> Option<Node<'t>> {
    if node.kind() == "call_expression" {
        return Some(node);
    }
    node.named_children(&mut node.walk()).find_map(jl_call)
}

fn jl_type_name(node: Node, source: &str) -> Option<String> {
    let head = node
        .children(&mut node.walk())
        .find(|c| c.kind() == "type_head")?;
    Some(node_text(first_identifier(head)?, source).to_string())
}

fn jl_const_item<'t>(node: Node<'t>, source: &str) -> Option<JlItem<'t>> {
    let assignment = node
        .children(&mut node.walk())
        .find(|c| c.kind() == "assignment")?;
    Some(JlItem {
        name: node_text(first_identifier(assignment.named_child(0)?)?, source).to_string(),
        selector: None,
        span: node,
        body: None,
    })
}

fn first_identifier<'t>(node: Node<'t>) -> Option<Node<'t>> {
    if node.kind() == "identifier" {
        return Some(node);
    }
    node.named_children(&mut node.walk()).find_map(first_identifier)
}

fn jl_select(signature: Option<String>, enclosing: Option<&Enclosing>) -> Option<String> {
    let signature = signature?;
    Some(match enclosing.and_then(|e| e.qualifier.as_deref()) {
        Some(prefix) => format!("{prefix}.{signature}"),
        None => signature,
    })
}

fn jl_module_scope(name: &str, enclosing: Option<&Enclosing>) -> Enclosing {
    let qualifier = match enclosing.and_then(|e| e.qualifier.as_deref()) {
        Some(outer) => format!("{outer}.{name}"),
        None => name.to_string(),
    };
    Enclosing {
        header: Some(format!("module {name}")),
        qualifier: Some(qualifier),
    }
}

fn collect_matching_jl_symbols(
    node: Node,
    source: &str,
    query: &SymbolQuery,
    depth: usize,
    enclosing: Option<&Enclosing>,
    matches: &mut Vec<Candidate>,
) {
    if depth >= query.parts.len() {
        return;
    }
    let target = collapse_ws(query.parts[depth]);
    let dotted = query.parts[depth..].join(".");
    let is_last = depth == query.parts.len() - 1;

    for child in node.children(&mut node.walk()) {
        let Some(item) = jl_item(child, source) else {
            continue;
        };
        let whole = item.name == dotted || item.selector.as_deref() == Some(target.as_str());
        if whole || (item.name == target && is_last) {
            let select = jl_select(item.selector, enclosing);
            let span = make_span(item.name, item.span, source, Leading::JuliaDocstring);
            matches.push(Candidate {
                select,
                ..matched(span, enclosing, MatchKind::Item)
            });
        } else if item.name == target {
            if let Some(body) = item.body {
                let scope = jl_module_scope(&item.name, enclosing);
                collect_matching_jl_symbols(body, source, query, depth + 1, Some(&scope), matches);
            }
        }
    }
}

fn collect_all_jl_symbols(
    node: Node,
    source: &str,
    prefix: &[String],
    symbols: &mut Vec<SymbolSpan>,
) {
    for child in node.children(&mut node.walk()) {
        let Some(item) = jl_item(child, source) else {
            continue;
        };
        symbols.push(make_span(
            qualify(prefix, &item.name),
            item.span,
            source,
            Leading::JuliaDocstring,
        ));
        if let Some(body) = item.body {
            let mut nested = prefix.to_vec();
            nested.push(item.name);
            collect_all_jl_symbols(body, source, &nested, symbols);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
use std::io;

enum DrawCommand {
    Fill(Path),
    Stroke(Path),
}

struct Canvas2DState {
    path: Vec<u8>,
    fill_color: Color,
}

impl Canvas2DState {
    pub fn new() -> Self {
        Self { path: Vec::new(), fill_color: Color::BLACK }
    }

    pub fn arc(&mut self, x: f64, y: f64, radius: f64) {
        // arc implementation
        let sweep = x + y;
    }

    pub fn flush(&self) {
        // flush implementation
    }
}

impl Default for Canvas2DState {
    fn default() -> Self {
        Self::new()
    }
}

fn helper() -> bool {
    true
}

#[cfg(test)]
mod tests {
    fn test_it() {}
}
"#;

    #[test]
    fn extract_top_level_enum() {
        let span = extract_symbol(SAMPLE, "DrawCommand").unwrap();
        assert!(span.body.contains("enum DrawCommand"));
        assert!(span.body.contains("Stroke"));
    }

    #[test]
    fn extract_top_level_struct() {
        let span = extract_symbol(SAMPLE, "Canvas2DState").unwrap();
        assert!(span.body.contains("struct Canvas2DState"));
        assert!(span.body.contains("fill_color"));
    }

    #[test]
    fn extract_method() {
        let span = extract_symbol(SAMPLE, "Canvas2DState::arc").unwrap();
        assert!(span.body.contains("pub fn arc"));
        assert!(span.body.contains("sweep"));
        assert!(!span.body.contains("pub fn flush"));
    }

    #[test]
    fn extract_top_level_fn() {
        let span = extract_symbol(SAMPLE, "helper").unwrap();
        assert!(span.body.contains("fn helper"));
    }

    #[test]
    fn missing_symbol_errors() {
        assert!(extract_symbol(SAMPLE, "nonexistent").is_err());
    }

    #[test]
    fn list_finds_all() {
        let syms = list_symbols(SAMPLE).unwrap();
        let names: Vec<&str> = syms.iter().map(|s| s.name.as_str()).collect();
        assert!(names.contains(&"DrawCommand"));
        assert!(names.contains(&"Canvas2DState"));
        assert!(names.contains(&"Canvas2DState::new"));
        assert!(names.contains(&"Canvas2DState::arc"));
        assert!(names.contains(&"Canvas2DState::flush"));
        assert!(names.contains(&"helper"));
    }

    const PEST_SAMPLE: &str = r#"
    use std::fmt;

    /// Implementation of a `Stack` which maintains popped elements.
    #[derive(Debug)]
    #[repr(C)]
    pub struct Stack<T: Clone> {
        /// All elements in the stack.
        cache: Vec<T>,
    }

    // Not a doc comment, and a blank line away.

    pub struct Plain;

    impl<R: RuleType> fmt::Debug for Pairs<'_, R> {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            write!(f, "debug shape")
        }
    }

    impl<R: RuleType> fmt::Display for Pairs<'_, R> {
        fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
            write!(f, "display shape")
        }
    }

    impl<R: RuleType> Op<R> {
        /// Prefix operator.
        #[inline]
        pub fn prefix(x: u8) -> Self {
            todo!()
        }
    }
    "#;

    #[test]
    fn two_traits_defining_fmt_refuse_to_guess() {
        let err = extract_symbol(PEST_SAMPLE, "Pairs<'_, R>::fmt")
            .unwrap_err()
            .to_string();
        assert!(err.contains("ambiguous"), "got {err}");
        assert!(err.contains("fmt::Debug for Pairs<'_, R>"), "got {err}");
        assert!(err.contains("fmt::Display for Pairs<'_, R>"), "got {err}");
        assert!(
            err.contains("symbol=\"<Pairs<'_, R> as fmt::Display>::fmt\""),
            "got {err}"
        );
    }

    #[test]
    fn a_qualified_path_selects_one_of_two_fmts() {
        let display = extract_symbol(PEST_SAMPLE, "<Pairs<'_, R> as fmt::Display>::fmt").unwrap();
        assert!(display.body.contains("display shape"), "got {:?}", display.body);
        let debug = extract_symbol(PEST_SAMPLE, "<Pairs<'_, R> as fmt::Debug>::fmt").unwrap();
        assert!(debug.body.contains("debug shape"), "got {:?}", debug.body);
    }

    #[test]
    fn a_qualifier_may_drop_the_generics_and_the_trait_path() {
        let span = extract_symbol(PEST_SAMPLE, "<Pairs as Display>::fmt").unwrap();
        assert!(span.body.contains("display shape"), "got {:?}", span.body);
    }

    #[test]
    fn a_generic_impl_is_reachable_by_its_base_name() {
        let bare = extract_symbol(PEST_SAMPLE, "Op::prefix").unwrap();
        let spelled = extract_symbol(PEST_SAMPLE, "Op<R>::prefix").unwrap();
        assert!(bare.body.contains("pub fn prefix"), "got {:?}", bare.body);
        assert_eq!(bare.byte_start, spelled.byte_start);
    }

    #[test]
    fn attributes_and_doc_comments_come_along() {
        let span = extract_symbol(PEST_SAMPLE, "Stack").unwrap();
        assert!(
            span.body.starts_with("/// Implementation of a `Stack`"),
            "got {:?}",
            span.body
        );
        assert!(span.body.contains("#[derive(Debug)]"), "got {:?}", span.body);
        assert!(span.body.contains("#[repr(C)]"), "got {:?}", span.body);
        assert!(span.body.contains("cache: Vec<T>"), "got {:?}", span.body);
    }

    #[test]
    fn a_method_keeps_its_attribute_and_doc() {
        let span = extract_symbol(PEST_SAMPLE, "Op::prefix").unwrap();
        assert!(
            span.body.starts_with("/// Prefix operator."),
            "got {:?}",
            span.body
        );
        assert!(span.body.contains("#[inline]"), "got {:?}", span.body);
    }

    #[test]
    fn a_plain_comment_across_a_blank_line_stays_out() {
        let span = extract_symbol(PEST_SAMPLE, "Plain").unwrap();
        assert_eq!(span.body, "pub struct Plain;", "got {:?}", span.body);
    }

    const TS_SAMPLE: &str = r#"
    export function createHorizonRemap(opts) {
      const scale = opts.scale ?? 1;
      return (u, v) => [u * scale, v * scale];
    }

    export const HORIZON_EPSILON = 1e-6;

    export class RemapPass {
      encode(pass) {
        pass.draw(3);
      }
    }

    export interface RemapOptions {
      scale: number;
    }

    function internalHelper() {
      return 42;
    }
    "#;

    #[test]
    fn extracts_an_exported_js_function_with_its_export() {
        let span =
            extract_symbol_in(TS_SAMPLE, "createHorizonRemap", SymbolLanguage::TypeScript).unwrap();
        assert!(
            span.body.starts_with("export function createHorizonRemap"),
            "got {:?}",
            span.body
        );
        assert!(span.body.contains("opts.scale"));
        assert!(!span.body.contains("internalHelper"));
    }

    #[test]
    fn extracts_an_exported_const_with_its_declaration() {
        let span =
            extract_symbol_in(TS_SAMPLE, "HORIZON_EPSILON", SymbolLanguage::TypeScript).unwrap();
        assert!(
            span.body.starts_with("export const HORIZON_EPSILON = 1e-6"),
            "got {:?}",
            span.body
        );
    }

    #[test]
    fn extracts_a_class_method_by_either_path_spelling() {
        let dotted =
            extract_symbol_in(TS_SAMPLE, "RemapPass.encode", SymbolLanguage::TypeScript).unwrap();
        let colons =
            extract_symbol_in(TS_SAMPLE, "RemapPass::encode", SymbolLanguage::TypeScript).unwrap();
        assert!(dotted.body.starts_with("encode(pass)"), "got {:?}", dotted.body);
        assert_eq!(dotted.byte_start, colons.byte_start);
    }

    #[test]
    fn finds_an_unexported_function_too() {
        let span =
            extract_symbol_in(TS_SAMPLE, "internalHelper", SymbolLanguage::TypeScript).unwrap();
        assert!(span.body.starts_with("function internalHelper"));
    }

    #[test]
    fn lists_every_ts_symbol_including_class_members() {
        let syms = list_symbols_in(TS_SAMPLE, SymbolLanguage::TypeScript).unwrap();
        let names: Vec<&str> = syms.iter().map(|s| s.name.as_str()).collect();
        for expected in [
            "createHorizonRemap",
            "HORIZON_EPSILON",
            "RemapPass",
            "RemapPass::encode",
            "RemapOptions",
            "internalHelper",
        ] {
            assert!(names.contains(&expected), "{expected} missing from {names:?}");
        }
    }

    #[test]
    fn js_and_jsx_fence_tags_resolve_to_a_grammar() {
        assert_eq!(
            SymbolLanguage::for_lang(Some("js")).unwrap(),
            SymbolLanguage::TypeScript
        );
        assert_eq!(
            SymbolLanguage::for_lang(Some("javascript")).unwrap(),
            SymbolLanguage::TypeScript
        );
        assert_eq!(
            SymbolLanguage::for_lang(Some("jsx")).unwrap(),
            SymbolLanguage::Tsx
        );
        assert_eq!(
            SymbolLanguage::for_lang(Some("rs")).unwrap(),
            SymbolLanguage::Rust
        );
    }

    #[test]
    fn an_unsupported_language_names_the_limit_not_the_symbol() {
        let err = SymbolLanguage::for_lang(Some("ruby"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("symbol extraction supports"), "got {err}");
        assert!(err.contains("ruby"), "got {err}");
        assert!(!err.contains("not found"), "got {err}");
    }

    #[test]
    fn a_fence_with_no_language_is_refused() {
        let err = SymbolLanguage::for_lang(None).unwrap_err().to_string();
        assert!(err.contains("needs a language on the fence"), "got {err}");
    }

    #[test]
    fn a_js_symbol_read_through_the_rust_grammar_is_invisible() {
        // The defect this dispatch exists for: the Rust-pinned shorthand
        // finds nothing in JavaScript, and "not found" is why a reader
        // spent an afternoon checking their own export names.
        assert!(extract_symbol(TS_SAMPLE, "createHorizonRemap").is_err());
    }

    const PY_SAMPLE: &str = r#"
    import functools

    VERSION = "1.0"
    MAX_DEPTH: int = 8

    def logp(value, mu):
        return -0.5 * (value - mu) ** 2

    async def fetch(url):
        return await get(url)

    class Sampler:
        """A step method."""

        def __init__(self, n):
            self.n = n

        @property
        def size(self):
            return self.n

        @staticmethod
        @functools.cache
        def build(n):
            return Sampler(n)

        class Inner:
            def deep(self):
                return 1

    @dataclass
    class Config:
        lr: float = 0.1
    "#;

    #[test]
    fn python_fence_tags_resolve_to_the_python_grammar() {
        assert_eq!(
            SymbolLanguage::for_lang(Some("python")).unwrap(),
            SymbolLanguage::Python
        );
        assert_eq!(
            SymbolLanguage::for_lang(Some("py")).unwrap(),
            SymbolLanguage::Python
        );
    }

    #[test]
    fn extracts_a_plain_def() {
        let span = extract_symbol_in(PY_SAMPLE, "logp", SymbolLanguage::Python).unwrap();
        assert!(span.body.starts_with("def logp(value, mu):"), "got {:?}", span.body);
        assert!(span.body.contains("-0.5"));
        assert!(!span.body.contains("async def"));
    }

    #[test]
    fn an_async_def_is_one_definition() {
        let span = extract_symbol_in(PY_SAMPLE, "fetch", SymbolLanguage::Python).unwrap();
        assert!(span.body.starts_with("async def fetch(url):"), "got {:?}", span.body);
    }

    #[test]
    fn extracts_a_python_method_by_either_path_spelling() {
        let dotted = extract_symbol_in(PY_SAMPLE, "Sampler.__init__", SymbolLanguage::Python).unwrap();
        let colons = extract_symbol_in(PY_SAMPLE, "Sampler::__init__", SymbolLanguage::Python).unwrap();
        assert!(dotted.body.starts_with("def __init__(self, n):"), "got {:?}", dotted.body);
        assert_eq!(dotted.byte_start, colons.byte_start);
    }

    #[test]
    fn a_decorated_def_keeps_its_decorator() {
        let span = extract_symbol_in(PY_SAMPLE, "Sampler.size", SymbolLanguage::Python).unwrap();
        assert!(span.body.starts_with("@property"), "got {:?}", span.body);
        assert!(span.body.contains("def size(self):"), "got {:?}", span.body);
    }

    #[test]
    fn a_method_comes_out_dedented_so_it_parses_alone() {
        // Without this a decorated method is an IndentationError: the first
        // decorator flush left, the second at the class's indentation.
        let span = extract_symbol_in(PY_SAMPLE, "Sampler.build", SymbolLanguage::Python).unwrap();
        assert_eq!(
            span.body,
            "@staticmethod\n@functools.cache\ndef build(n):\n    return Sampler(n)",
            "got {:?}",
            span.body
        );
        let method = extract_symbol_in(PY_SAMPLE, "Sampler.size", SymbolLanguage::Python).unwrap();
        assert!(method.body.contains("\n    return self.n"), "got {:?}", method.body);
    }

    #[test]
    fn stacked_decorators_all_come_along() {
        let span = extract_symbol_in(PY_SAMPLE, "Sampler.build", SymbolLanguage::Python).unwrap();
        assert!(span.body.starts_with("@staticmethod"), "got {:?}", span.body);
        assert!(span.body.contains("@functools.cache"), "got {:?}", span.body);
    }

    #[test]
    fn a_decorated_class_keeps_its_decorator() {
        let span = extract_symbol_in(PY_SAMPLE, "Config", SymbolLanguage::Python).unwrap();
        assert!(span.body.starts_with("@dataclass"), "got {:?}", span.body);
        assert!(span.body.contains("lr: float = 0.1"), "got {:?}", span.body);
    }

    #[test]
    fn a_module_level_binding_is_a_symbol() {
        let plain = extract_symbol_in(PY_SAMPLE, "VERSION", SymbolLanguage::Python).unwrap();
        assert_eq!(plain.body, "VERSION = \"1.0\"", "got {:?}", plain.body);
        let annotated = extract_symbol_in(PY_SAMPLE, "MAX_DEPTH", SymbolLanguage::Python).unwrap();
        assert_eq!(annotated.body, "MAX_DEPTH: int = 8", "got {:?}", annotated.body);
    }

    #[test]
    fn lists_every_python_symbol_including_nested_classes() {
        let syms = list_symbols_in(PY_SAMPLE, SymbolLanguage::Python).unwrap();
        let names: Vec<&str> = syms.iter().map(|s| s.name.as_str()).collect();
        for expected in [
            "VERSION",
            "MAX_DEPTH",
            "logp",
            "fetch",
            "Sampler",
            "Sampler::__init__",
            "Sampler::size",
            "Sampler::build",
            "Sampler::Inner",
            "Sampler::Inner::deep",
            "Config",
        ] {
            assert!(names.contains(&expected), "{expected} missing from {names:?}");
        }
    }

    #[test]
    fn a_local_assignment_is_not_a_python_symbol() {
        assert!(extract_symbol_in(PY_SAMPLE, "Sampler.n", SymbolLanguage::Python).is_err());
    }

    const JL_SAMPLE: &str = r#"
    module QuadGK

    const MAXN = 12
    const δ_tol = 1e-8

    """
        gauss(f, a, b)

    Two-point Gauss rule.
    """
    function gauss(f, a, b)
        return (b - a) * f((a + b) / 2)
    end

    δλ(x) = x^2 + 1

    x̄(v) = sum(v) / length(v)

    function quadgk(f, a, b)
        return gauss(f, a, b)
    end

    function quadgk(f, segments)
        return sum(s -> gauss(f, s...), segments)
    end

    struct Segment{T}
        a::T
        b::T
    end

    mutable struct Cache
        hits::Int
    end

    macro checked(ex)
        return esc(ex)
    end

    @inline function fast(x)
        return x
    end

    module Inner
        function deep(x)
            return x
        end
    end

    end
    "#;

    #[test]
    fn julia_fence_tags_resolve_to_the_julia_grammar() {
        assert_eq!(
            SymbolLanguage::for_lang(Some("julia")).unwrap(),
            SymbolLanguage::Julia
        );
        assert_eq!(
            SymbolLanguage::for_lang(Some("jl")).unwrap(),
            SymbolLanguage::Julia
        );
    }

    #[test]
    fn extracts_a_function_block_with_its_docstring() {
        let span = extract_symbol_in(JL_SAMPLE, "QuadGK.gauss", SymbolLanguage::Julia).unwrap();
        assert!(span.body.starts_with("\"\"\""), "got {:?}", span.body);
        assert!(span.body.contains("gauss(f, a, b)"), "got {:?}", span.body);
        assert!(span.body.contains("function gauss(f, a, b)"), "got {:?}", span.body);
        assert!(span.body.trim_end().ends_with("end"), "got {:?}", span.body);
    }

    #[test]
    fn a_unicode_short_form_survives_byte_for_byte() {
        let span = extract_symbol_in(JL_SAMPLE, "QuadGK.δλ", SymbolLanguage::Julia).unwrap();
        assert_eq!(span.name, "δλ");
        assert_eq!(span.body, "δλ(x) = x^2 + 1", "got {:?}", span.body);
        let combining = extract_symbol_in(JL_SAMPLE, "QuadGK.x̄", SymbolLanguage::Julia).unwrap();
        assert_eq!(combining.name, "x̄");
        assert_eq!(combining.body, "x̄(v) = sum(v) / length(v)");
        assert_eq!(&JL_SAMPLE[combining.byte_start..combining.byte_end], combining.body);
    }

    #[test]
    fn a_unicode_const_survives_byte_for_byte() {
        let span = extract_symbol_in(JL_SAMPLE, "QuadGK.δ_tol", SymbolLanguage::Julia).unwrap();
        assert_eq!(span.body, "const δ_tol = 1e-8", "got {:?}", span.body);
    }

    #[test]
    fn two_methods_of_one_function_refuse_to_guess() {
        let err = extract_symbol_in(JL_SAMPLE, "QuadGK.quadgk", SymbolLanguage::Julia)
            .unwrap_err()
            .to_string();
        assert!(err.contains("ambiguous"), "got {err}");
        assert!(err.contains("symbol=\"QuadGK.quadgk(f, a, b)\""), "got {err}");
        assert!(err.contains("symbol=\"QuadGK.quadgk(f, segments)\""), "got {err}");
    }

    #[test]
    fn a_signature_selects_one_method() {
        let span =
            extract_symbol_in(JL_SAMPLE, "QuadGK.quadgk(f, segments)", SymbolLanguage::Julia).unwrap();
        assert!(span.body.contains("segments)"), "got {:?}", span.body);
        assert!(!span.body.contains("(b - a)"), "got {:?}", span.body);
    }

    #[test]
    fn extracts_structs_macros_and_macro_wrapped_definitions() {
        let plain = extract_symbol_in(JL_SAMPLE, "QuadGK.Segment", SymbolLanguage::Julia).unwrap();
        assert!(plain.body.starts_with("struct Segment{T}"), "got {:?}", plain.body);
        let mutable = extract_symbol_in(JL_SAMPLE, "QuadGK.Cache", SymbolLanguage::Julia).unwrap();
        assert!(mutable.body.starts_with("mutable struct Cache"), "got {:?}", mutable.body);
        let mac = extract_symbol_in(JL_SAMPLE, "QuadGK.checked", SymbolLanguage::Julia).unwrap();
        assert!(mac.body.starts_with("macro checked(ex)"), "got {:?}", mac.body);
        let wrapped = extract_symbol_in(JL_SAMPLE, "QuadGK.fast", SymbolLanguage::Julia).unwrap();
        assert!(wrapped.body.starts_with("@inline function fast(x)"), "got {:?}", wrapped.body);
    }

    #[test]
    fn descends_into_a_nested_julia_module() {
        let span = extract_symbol_in(JL_SAMPLE, "QuadGK.Inner.deep", SymbolLanguage::Julia).unwrap();
        assert!(span.body.starts_with("function deep(x)"), "got {:?}", span.body);
    }

    #[test]
    fn lists_every_julia_symbol_under_its_module() {
        let syms = list_symbols_in(JL_SAMPLE, SymbolLanguage::Julia).unwrap();
        let names: Vec<&str> = syms.iter().map(|s| s.name.as_str()).collect();
        for expected in [
            "QuadGK",
            "QuadGK::MAXN",
            "QuadGK::δ_tol",
            "QuadGK::gauss",
            "QuadGK::δλ",
            "QuadGK::x̄",
            "QuadGK::Segment",
            "QuadGK::Cache",
            "QuadGK::checked",
            "QuadGK::fast",
            "QuadGK::Inner",
            "QuadGK::Inner::deep",
        ] {
            assert!(names.contains(&expected), "{expected} missing from {names:?}");
        }
    }
}
