// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/tangle/region-weave.md — DO NOT EDIT.
//! Integration tests for region projection — the `region-weave` and
//! `region-project` chapters of the crate's literate source.
//!
//! These exercise the public surface end-to-end: the pure
//! [`x0k_tangle::weave_region`] + [`x0k_tangle::validate_artifact`] invariants,
//! and the I/O orchestration [`x0k_tangle::project_publication`] against a real
//! temp-dir workspace (publication doc + member decision files on disk → a
//! written multi-page artifact).

use std::fs;
use std::path::PathBuf;

use x0k_tangle::{
    project_publication, validate_artifact, weave_region, ArtifactFile, RegionInput, RegionMember,
};

/// An empty atlas for hand-built `RegionWeaveOutput` fixtures (the validator
/// only inspects HTML pages, not the atlas).
fn empty_atlas() -> x0k_tangle::Atlas {
    x0k_tangle::Atlas {
        nodes: vec![],
        placements: vec![],
        edges: vec![],
        min_year: 0,
        threads: vec![],
        bands: vec![],
        unresolved_years: vec![],
    }
}

/// A minimal folio/v1 design doc body (frontmatter split off by the weaver).
fn design_doc(id: &str, title: &str, body: &str) -> String {
    format!(
        "---\nx0k:\n  format: folio/v1\n  type: design\n  id: {id}\n  status: proposed\n---\n\n# {title}\n\n{body}\n"
    )
}

fn architecture_doc(id: &str, title: &str, body: &str) -> String {
    format!(
        "---\nx0k:\n  format: folio/v1\n  type: architecture\n  id: {id}\n  status: proposed\n---\n\n# {title}\n\n{body}\n"
    )
}

fn member(uri: &str, src: &str, content: &str) -> RegionMember {
    RegionMember {
        uri: uri.to_string(),
        content: content.to_string(),
        source_path: PathBuf::from(src),
    }
}

#[test]
fn artifact_is_self_contained_and_links_resolve() {
    let input = RegionInput {
        entry_point_uri: "x0k:design/author".to_string(),
        members: vec![
            member(
                "x0k:design/author",
                "decisions/design/author.md",
                &design_doc(
                    "x0k:design/author",
                    "Author and Publish",
                    "See [the architecture](x0k:architecture/web-first).",
                ),
            ),
            member(
                "x0k:architecture/web-first",
                "decisions/architecture/web-first.md",
                &architecture_doc(
                    "x0k:architecture/web-first",
                    "Web First",
                    "Back to [the design](x0k:design/author).",
                ),
            ),
        ],
    };

    let out = weave_region(&input).expect("weave region");

    // index.html is the entry and is present.
    assert_eq!(out.entry_rel_path, PathBuf::from("index.html"));
    let names: Vec<String> = out
        .files
        .iter()
        .map(|f| f.rel_path.to_string_lossy().to_string())
        .collect();
    assert!(names.contains(&"index.html".to_string()));
    assert!(names.contains(&"architecture-web-first.html".to_string()));

    // Each HTML page: DOCTYPE, inlined <style>, no external stylesheet link.
    // (atlas.json is a sibling artifact, not an HTML page — skip it.)
    for f in out
        .files
        .iter()
        .filter(|f| f.rel_path.extension().map(|e| e == "html").unwrap_or(false))
    {
        let html = std::str::from_utf8(&f.bytes).unwrap();
        assert!(
            html.starts_with("<!DOCTYPE html>"),
            "{} missing DOCTYPE",
            f.rel_path.display()
        );
        assert!(
            html.contains("<style>"),
            "{} missing inlined <style>",
            f.rel_path.display()
        );
        assert!(
            !(html.contains("<link") && html.contains("stylesheet")),
            "{} pulls an external stylesheet",
            f.rel_path.display()
        );
        // Site nav present on every page.
        assert!(
            html.contains("<nav class=\"region-nav\""),
            "{} missing site nav",
            f.rel_path.display()
        );
    }

    // The full validator passes (entry present; every intra-region href maps to
    // a file in the artifact).
    validate_artifact(&out).expect("artifact validates");
}

#[test]
fn validate_artifact_rejects_dangling_intra_region_link() {
    // Hand-build a bad artifact: index links to a sibling that isn't present.
    let bad = x0k_tangle::RegionWeaveOutput {
        files: vec![ArtifactFile {
            rel_path: PathBuf::from("index.html"),
            bytes: b"<!DOCTYPE html>\n<head><style>x</style></head>\n<body>\n<a href=\"missing.html\">x</a>\n</body>".to_vec(),
        }],
        entry_rel_path: PathBuf::from("index.html"),
        media_refs: vec![],
        unresolved_links: vec![],
        degraded_embeds: vec![],
        atlas: empty_atlas(),
        transclusion_warnings: vec![],
    };
    let err = validate_artifact(&bad).expect_err("dangling link must fail validation");
    assert!(
        err.to_string().contains("missing.html"),
        "unexpected error: {err}"
    );
}

#[test]
fn validate_artifact_rejects_missing_entry() {
    let bad = x0k_tangle::RegionWeaveOutput {
        files: vec![ArtifactFile {
            rel_path: PathBuf::from("other.html"),
            bytes: b"<!DOCTYPE html>\n<style>x</style>\n".to_vec(),
        }],
        entry_rel_path: PathBuf::from("index.html"),
        media_refs: vec![],
        unresolved_links: vec![],
        degraded_embeds: vec![],
        atlas: empty_atlas(),
        transclusion_warnings: vec![],
    };
    let err = validate_artifact(&bad).expect_err("missing entry must fail");
    assert!(err.to_string().contains("index.html"), "got: {err}");
}

#[test]
fn project_publication_writes_navigable_artifact_to_disk() {
    let ws = tempfile::tempdir().unwrap();
    let ws_root = ws.path();

    // Member decision docs.
    let design_dir = ws_root.join("decisions/design");
    let arch_dir = ws_root.join("decisions/architecture");
    let pub_dir = ws_root.join("decisions/publications");
    fs::create_dir_all(&design_dir).unwrap();
    fs::create_dir_all(&arch_dir).unwrap();
    fs::create_dir_all(&pub_dir).unwrap();

    fs::write(
        design_dir.join("author.md"),
        design_doc(
            "x0k:design/author",
            "Author and Publish",
            "See [the architecture](x0k:architecture/web-first) for the substrate.",
        ),
    )
    .unwrap();
    fs::write(
        arch_dir.join("web-first.md"),
        architecture_doc(
            "x0k:architecture/web-first",
            "Web First, Progressively Native",
            "Realizes [the design](x0k:design/author).",
        ),
    )
    .unwrap();

    // The publication doc demarcating the region.
    let publication = "---\n\
        x0k:\n\
        \x20\x20format: folio/v1\n\
        \x20\x20type: publication\n\
        \x20\x20id: x0k:publication/sample-region\n\
        \x20\x20status: proposed\n\
        \x20\x20edges:\n\
        \x20\x20\x20\x20publishes:\n\
        \x20\x20\x20\x20\x20\x20- x0k:design/author\n\
        \x20\x20\x20\x20\x20\x20- x0k:architecture/web-first\n\
        \x20\x20\x20\x20entryPoint:\n\
        \x20\x20\x20\x20\x20\x20- x0k:design/author\n\
        ---\n\n# Sample Region\n\nA demonstration publication.\n";
    let pub_path = pub_dir.join("sample-region.md");
    fs::write(&pub_path, publication).unwrap();

    // Project into an output dir (inside the tempdir; never the repo tree).
    let out_dir = ws_root.join("artifact");
    // no_motifs=true: no motif refs in this sample, and we don't want the test
    // to invoke the cargo-driven motif build.
    let report = project_publication(&pub_path, &out_dir, ws_root, true).expect("project");

    // page_count counts the woven semantic fallback pages (under pages/).
    assert_eq!(report.page_count, 2);
    assert!(
        report.unresolved_links.is_empty(),
        "{:?}",
        report.unresolved_links
    );

    // The render-vello canvas shell is the root index.html (Phase 5).
    let shell = out_dir.join("index.html");
    assert!(shell.is_file(), "canvas shell not written");
    assert_eq!(out_dir.join(&report.entry_rel_path), shell);
    let shell_html = fs::read_to_string(&shell).unwrap();
    assert!(
        shell_html.contains("vello-canvas"),
        "root index isn't the shell"
    );
    assert!(
        shell_html.contains("pages/index.html"),
        "shell missing fallback link"
    );

    // The woven semantic pages are the no-WebGPU fallback under pages/.
    let index = out_dir.join("pages/index.html");
    let arch = out_dir.join("pages/architecture-web-first.html");
    assert!(index.is_file(), "fallback entry not written");
    assert!(arch.is_file(), "member fallback page not written");

    // Links resolve both ways across the woven fallback files (bare filenames,
    // resolved within pages/ at runtime).
    let index_html = fs::read_to_string(&index).unwrap();
    let arch_html = fs::read_to_string(&arch).unwrap();
    assert!(
        index_html.contains("href=\"architecture-web-first.html\""),
        "entry should link to architecture page"
    );
    assert!(
        arch_html.contains("href=\"index.html\""),
        "architecture page should link back to entry"
    );

    // Site nav on both, marking the current page.
    assert!(index_html.contains("<nav class=\"region-nav\""));
    assert!(arch_html.contains("<nav class=\"region-nav\""));
    assert!(index_html.contains("aria-current=\"page\""));

    // Bundled boot assets + region data at the artifact root.
    assert!(out_dir.join("boot.js").is_file(), "boot.js not written");
    assert!(
        out_dir.join("members.json").is_file(),
        "members.json not written"
    );
    assert!(
        out_dir.join("narrative.json").is_file(),
        "narrative.json not written"
    );
    assert!(
        out_dir.join("atlas.json").is_file(),
        "atlas.json not written"
    );
}

#[test]
fn single_member_publication_defaults_entry() {
    let ws = tempfile::tempdir().unwrap();
    let ws_root = ws.path();
    let design_dir = ws_root.join("decisions/design");
    let pub_dir = ws_root.join("decisions/publications");
    fs::create_dir_all(&design_dir).unwrap();
    fs::create_dir_all(&pub_dir).unwrap();
    fs::write(
        design_dir.join("solo.md"),
        design_doc("x0k:design/solo", "Solo", "Just one doc."),
    )
    .unwrap();

    let publication = "---\n\
        x0k:\n\
        \x20\x20format: folio/v1\n\
        \x20\x20type: publication\n\
        \x20\x20id: x0k:publication/solo-pub\n\
        \x20\x20status: proposed\n\
        \x20\x20edges:\n\
        \x20\x20\x20\x20publishes:\n\
        \x20\x20\x20\x20\x20\x20- x0k:design/solo\n\
        ---\n\n# Solo Pub\n";
    let pub_path = pub_dir.join("solo-pub.md");
    fs::write(&pub_path, publication).unwrap();

    let out_dir = ws_root.join("artifact");
    let report = project_publication(&pub_path, &out_dir, ws_root, true).expect("project");
    assert_eq!(report.page_count, 1);
    // Canvas shell at the root; the sole woven page is the fallback entry.
    assert!(out_dir.join("index.html").is_file());
    assert!(out_dir.join("pages/index.html").is_file());
}

#[test]
#[cfg_attr(not(feature = "motifs"), ignore = "wasm bundling requires the motifs feature")]
fn self_booting_artifact_bundles_wasm_data_shell_and_fallback() {
    let ws = tempfile::tempdir().unwrap();
    let ws_root = ws.path();
    let wiki_dir = ws_root.join("knowledge/wiki");
    let pub_dir = ws_root.join("decisions/publications");
    fs::create_dir_all(&wiki_dir).unwrap();
    fs::create_dir_all(&pub_dir).unwrap();

    // A fake prebuilt render-vello wasm bundle at the default location.
    let wasm_src = ws_root.join("ui/0k.computer/wasm/render-vello");
    fs::create_dir_all(&wasm_src).unwrap();
    fs::write(wasm_src.join("x0k_ui_render_vello.js"), b"// fake js\n").unwrap();
    fs::write(
        wasm_src.join("x0k_ui_render_vello_bg.wasm"),
        b"\0asm fake wasm bytes",
    )
    .unwrap();

    // Two wiki members with a frontmatter summary + body (deep-doc portal text).
    for (slug, title) in [("alpha", "Alpha Page"), ("beta", "Beta Page")] {
        fs::write(
            wiki_dir.join(format!("{slug}.md")),
            format!(
                "---\nx0k:\n  format: folio/v1\n  type: wiki\n  id: x0k:wiki/{slug}\n  summary: Summary of {title}\n---\n\n# {title}\n\nReal prose body for {title}.\n"
            ),
        )
        .unwrap();
    }

    let publication = "---\n\
        x0k:\n\
        \x20\x20format: folio/v1\n\
        \x20\x20type: publication\n\
        \x20\x20id: x0k:publication/lineage-mini\n\
        \x20\x20status: proposed\n\
        \x20\x20edges:\n\
        \x20\x20\x20\x20publishes:\n\
        \x20\x20\x20\x20\x20\x20- x0k:wiki/alpha\n\
        \x20\x20\x20\x20\x20\x20- x0k:wiki/beta\n\
        \x20\x20\x20\x20entryPoint:\n\
        \x20\x20\x20\x20\x20\x20- x0k:wiki/alpha\n\
        ---\n\n# Lineage Mini\n";
    let pub_path = pub_dir.join("lineage-mini.md");
    fs::write(&pub_path, publication).unwrap();

    // A narrative sidecar beside the publication doc.
    fs::write(
        pub_dir.join("lineage-mini.narrative.json"),
        br#"{"title":"T","thesis":"Th","stations":[{"id":"s1","ordinal":1,"title":"S1","thread":"x","empower":"e","shadow":"sh","highlight":["x0k:wiki/alpha"],"key_edges":[]}]}"#,
    )
    .unwrap();

    let out_dir = ws_root.join("artifact");
    let report = project_publication(&pub_path, &out_dir, ws_root, true).expect("project");

    // Renderer + narrative bundled.
    assert!(report.wasm_bundled, "render-vello wasm should be bundled");
    assert!(report.wasm_bytes > 0);
    assert!(
        report.narrative_bundled,
        "narrative sidecar should be bundled"
    );

    // Every required artifact file is present.
    for rel in [
        "index.html",
        "boot.js",
        "atlas.json",
        "members.json",
        "narrative.json",
        "wasm/x0k_ui_render_vello.js",
        "wasm/x0k_ui_render_vello_bg.wasm",
        "pages/index.html",
        "pages/wiki-beta.html",
    ] {
        assert!(out_dir.join(rel).is_file(), "missing artifact file: {rel}");
    }

    // The bundled members.json carries real per-member body text.
    let members: serde_json::Value =
        serde_json::from_slice(&fs::read(out_dir.join("members.json")).unwrap()).unwrap();
    assert_eq!(members["members"]["x0k:wiki/alpha"]["title"], "Alpha Page");
    assert!(members["members"]["x0k:wiki/alpha"]["body"]
        .as_str()
        .unwrap()
        .contains("Real prose body"));

    // The canvas shell loads ONLY same-origin relative resources (no http(s)
    // <script>/<link> CDN loads). Prose hyperlinks live in the fallback pages,
    // not the shell.
    let shell = fs::read_to_string(out_dir.join("index.html")).unwrap();
    assert!(shell.contains("vello-canvas"));
    assert!(
        !shell.contains("http://"),
        "shell has an external http resource"
    );
    assert!(
        !shell.contains("https://"),
        "shell has an external https resource"
    );
    assert!(
        shell.contains("./boot.js") || shell.contains("\"boot.js\""),
        "shell should load the local boot script"
    );
}

#[test]
fn spine_transcludes_two_briefs_into_one_woven_page() {
    let design_a = "---\nx0k:\n  format: folio/v1\n  type: design\n  id: x0k:design/alpha\n  status: proposed\n---\n\n# Alpha\n\nlead\n\n## Brief\n\nAlpha's brief paragraph.\n\n## Purpose\n\nAlpha purpose (must NOT be inlined).\n";
    let design_b = "---\nx0k:\n  format: folio/v1\n  type: design\n  id: x0k:design/beta\n  status: proposed\n---\n\n# Beta\n\nlead\n\n## Brief\n\nBeta's brief paragraph.\n\n## Purpose\n\nBeta purpose (must NOT be inlined).\n";
    // Spine: inline fence pulls alpha#brief; frontmatter pulls beta#brief.
    let spine = "---\nx0k:\n  format: folio/v1\n  type: wiki\n  id: x0k:wiki/spine\n  status: stable\n  transcludes:\n    - x0k:design/beta#brief\n---\n\n# Spine\n\nConnective prose before.\n\n```x0k:transclude {ref=\"x0k:design/alpha#brief\"}\n```\n\nConnective prose after.\n";

    let input = RegionInput {
        entry_point_uri: "x0k:wiki/spine".to_string(),
        members: vec![
            RegionMember {
                uri: "x0k:wiki/spine".to_string(),
                content: spine.to_string(),
                source_path: PathBuf::from("knowledge/wiki/spine.md"),
            },
            RegionMember {
                uri: "x0k:design/alpha".to_string(),
                content: design_a.to_string(),
                source_path: PathBuf::from("decisions/design/alpha.md"),
            },
            RegionMember {
                uri: "x0k:design/beta".to_string(),
                content: design_b.to_string(),
                source_path: PathBuf::from("decisions/design/beta.md"),
            },
        ],
    };

    let out = weave_region(&input).unwrap();
    let index = std::str::from_utf8(
        &out.files
            .iter()
            .find(|f| f.rel_path == std::path::Path::new("index.html"))
            .unwrap()
            .bytes,
    )
    .unwrap();

    // Both briefs inlined into the spine's index page.
    assert!(
        index.contains("Alpha's brief paragraph."),
        "inline-fence transclusion of alpha#brief not inlined"
    );
    assert!(
        index.contains("Beta's brief paragraph."),
        "frontmatter transclusion of beta#brief not inlined"
    );
    // The spine's own connective prose surrounds them.
    assert!(index.contains("Connective prose before."));
    assert!(index.contains("Connective prose after."));
    // Section extraction stops at the next heading — purpose NOT pulled in.
    assert!(
        !index.contains("Alpha purpose"),
        "section extraction leaked past the #brief heading"
    );
    assert!(!index.contains("Beta purpose"));
    // No raw transclude fence survived into the woven HTML.
    assert!(!index.contains("x0k:transclude"));
    // Clean resolution — no degraded references.
    assert!(
        out.transclusion_warnings.is_empty(),
        "unexpected transclusion warnings: {:?}",
        out.transclusion_warnings
    );

    validate_artifact(&out).expect("woven spine artifact validates");
}

#[test]
fn edit_through_to_source_is_reflected_when_spine_reresolves() {
    use x0k_folio::transclusion::{replace_section, split_body};

    let source_before = "---\nx0k:\n  format: folio/v1\n  type: design\n  id: x0k:design/source\n  status: proposed\n---\n\n# Source\n\n## Brief\n\noriginal source brief.\n\n## Purpose\n\npurpose stays put.\n";
    let spine = "---\nx0k:\n  format: folio/v1\n  type: wiki\n  id: x0k:wiki/spine\n  status: stable\n---\n\n# Spine\n\nSpine connective prose.\n\n```x0k:transclude {ref=\"x0k:design/source#brief\"}\n```\n";

    let weave = |source_content: &str| {
        let input = RegionInput {
            entry_point_uri: "x0k:wiki/spine".to_string(),
            members: vec![
                RegionMember {
                    uri: "x0k:wiki/spine".to_string(),
                    content: spine.to_string(),
                    source_path: PathBuf::from("knowledge/wiki/spine.md"),
                },
                RegionMember {
                    uri: "x0k:design/source".to_string(),
                    content: source_content.to_string(),
                    source_path: PathBuf::from("decisions/design/source.md"),
                },
            ],
        };
        let out = weave_region(&input).unwrap();
        std::str::from_utf8(
            &out.files
                .iter()
                .find(|f| f.rel_path == std::path::Path::new("index.html"))
                .unwrap()
                .bytes,
        )
        .unwrap()
        .to_string()
    };

    // Before the edit: the spine inlines the original brief.
    let index_before = weave(source_before);
    assert!(index_before.contains("original source brief."));
    assert!(!index_before.contains("EDITED source brief."));

    // Apply the edit-through to the SOURCE body's `#brief` section — the
    // exact transform `DocumentViewer::save_transclusion_edit` performs.
    let (yaml, body) = split_body(source_before);
    let new_body = replace_section(body, "brief", "## Brief\n\nEDITED source brief.\n").unwrap();
    let source_after = format!("---{}\n---\n{new_body}", yaml.unwrap());
    // The source's other section is preserved by the edit.
    assert!(source_after.contains("purpose stays put."));
    assert!(source_after.contains("EDITED source brief."));
    assert!(!source_after.contains("original source brief."));

    // After the edit: re-resolving the spine inlines the EDITED brief; the
    // spine's own connective prose is unchanged (the spine content never
    // mutated — only the source did).
    let index_after = weave(&source_after);
    assert!(
        index_after.contains("EDITED source brief."),
        "spine should re-resolve to the edited source content"
    );
    assert!(!index_after.contains("original source brief."));
    assert!(
        index_after.contains("Spine connective prose."),
        "spine's own prose untouched by the source edit"
    );
    // The edit didn't leak the source's other section into the spine.
    assert!(!index_after.contains("purpose stays put."));
}

#[test]
fn spine_self_transclusion_degrades_to_link_with_warning() {
    let spine = "---\nx0k:\n  format: folio/v1\n  type: wiki\n  id: x0k:wiki/loop\n  status: stable\n---\n\n# Loop\n\n```x0k:transclude {ref=\"x0k:wiki/loop\"}\n```\n";
    let input = RegionInput {
        entry_point_uri: "x0k:wiki/loop".to_string(),
        members: vec![RegionMember {
            uri: "x0k:wiki/loop".to_string(),
            content: spine.to_string(),
            source_path: PathBuf::from("knowledge/wiki/loop.md"),
        }],
    };
    let out = weave_region(&input).unwrap();
    assert!(
        out.transclusion_warnings
            .iter()
            .any(|w| w.contains("Cycle")),
        "expected a cycle warning, got {:?}",
        out.transclusion_warnings
    );
    validate_artifact(&out).expect("artifact still validates after degrade");
}
