// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/tangle/multi-doc-resolve.md — DO NOT EDIT.
use crate::parser::ParsedDocument;
use crate::resolve::{expand_recursive, VisitKey};
use anyhow::Result;
use std::collections::HashMap;
use std::collections::HashSet;

/// A set of parsed documents indexed by their frontmatter `id:` URI.
/// `<<uri::chunk>>` refs resolve the document by URI, then the chunk
/// within it.
pub struct Corpus<'a> {
    docs: HashMap<String, &'a ParsedDocument>,
}

impl<'a> Corpus<'a> {
    /// Index the given documents by their `id:` URI. Documents without
    /// an `id` are skipped — they can never be a cross-doc target.
    pub fn from_docs(docs: impl IntoIterator<Item = &'a ParsedDocument>) -> Self {
        let mut map = HashMap::new();
        for doc in docs {
            if let Some(id) = &doc.id {
                map.insert(id.clone(), doc);
            }
        }
        Corpus { docs: map }
    }

    /// Look up a document by its `id:` URI.
    pub fn doc(&self, uri: &str) -> Option<&'a ParsedDocument> {
        self.docs.get(uri).copied()
    }

    /// Number of indexed documents.
    pub fn len(&self) -> usize {
        self.docs.len()
    }

    pub fn is_empty(&self) -> bool {
        self.docs.is_empty()
    }
}

pub fn expand_chunk_in_corpus(
    corpus: &Corpus,
    start_uri: &str,
    chunk_name: &str,
) -> Result<String> {
    let start = corpus.doc(start_uri).ok_or_else(|| {
        anyhow::anyhow!("starting document '{}' not found in corpus", start_uri)
    })?;
    let mut visited: HashSet<VisitKey> = HashSet::new();
    expand_recursive(Some(corpus), start_uri, start, chunk_name, None, &mut visited)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_document;

    fn doc_a() -> ParsedDocument {
        parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-a
  type: implementation
---
```rust {#greeting}
println!("hello from A");
```
"#,
        )
        .unwrap()
    }

    #[test]
    fn transcludes_chunk_from_another_doc() {
        let a = doc_a();
        let b = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-b
  type: implementation
---
```rust {#main}
fn main() {
    <<x0k:implementation/tangle/doc-a::greeting>>
}
```
"#,
        )
        .unwrap();

        let corpus = Corpus::from_docs([&a, &b]);
        assert_eq!(corpus.len(), 2);
        let out =
            expand_chunk_in_corpus(&corpus, "x0k:implementation/tangle/doc-b", "main").unwrap();
        assert!(out.contains("fn main()"));
        assert!(out.contains("hello from A"));
    }

    #[test]
    fn cross_doc_preserves_indent() {
        let a = doc_a();
        let b = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-b
  type: implementation
---
```rust {#main}
fn main() {
    <<x0k:implementation/tangle/doc-a::greeting>>
}
```
"#,
        )
        .unwrap();

        let corpus = Corpus::from_docs([&a, &b]);
        let out =
            expand_chunk_in_corpus(&corpus, "x0k:implementation/tangle/doc-b", "main").unwrap();
        // The ref line was indented four spaces; the transcluded body
        // line should carry that indent.
        assert!(out.contains("    println!(\"hello from A\");"));
    }

    #[test]
    fn recursive_cross_doc_transclusion() {
        // c -> b -> a, all across document boundaries.
        let a = doc_a();
        let b = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-b
  type: implementation
---
```rust {#wrapper}
{
    <<x0k:implementation/tangle/doc-a::greeting>>
}
```
"#,
        )
        .unwrap();
        let c = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-c
  type: implementation
---
```rust {#main}
fn main()
    <<x0k:implementation/tangle/doc-b::wrapper>>
```
"#,
        )
        .unwrap();

        let corpus = Corpus::from_docs([&a, &b, &c]);
        let out =
            expand_chunk_in_corpus(&corpus, "x0k:implementation/tangle/doc-c", "main").unwrap();
        assert!(out.contains("fn main()"));
        assert!(out.contains("hello from A"));
        // The greeting picked up doc-c's indent (4) plus doc-b's brace
        // block indent (4) = 8 spaces at the deepest call site.
        assert!(out.contains("        println!(\"hello from A\");"), "got:\n{out}");
    }

    #[test]
    fn cross_doc_cycle_errors() {
        // doc-x::a -> doc-y::b -> doc-x::a — a cycle across the boundary.
        let x = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-x
  type: implementation
---
```rust {#a}
<<x0k:implementation/tangle/doc-y::b>>
```
"#,
        )
        .unwrap();
        let y = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-y
  type: implementation
---
```rust {#b}
<<x0k:implementation/tangle/doc-x::a>>
```
"#,
        )
        .unwrap();

        let corpus = Corpus::from_docs([&x, &y]);
        let err =
            expand_chunk_in_corpus(&corpus, "x0k:implementation/tangle/doc-x", "a").unwrap_err();
        assert!(err.to_string().contains("cycle"), "got: {err}");
    }

    #[test]
    fn unknown_target_doc_errors() {
        let b = parse_document(
            r#"---
x0k:
  format: folio/v1
  id: x0k:implementation/tangle/doc-b
  type: implementation
---
```rust {#main}
<<x0k:implementation/tangle/does-not-exist::nope>>
```
"#,
        )
        .unwrap();
        let corpus = Corpus::from_docs([&b]);
        let err =
            expand_chunk_in_corpus(&corpus, "x0k:implementation/tangle/doc-b", "main").unwrap_err();
        assert!(err.to_string().contains("unknown document"), "got: {err}");
    }
}
