// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/tangle/region-project.md — DO NOT EDIT.
//! Region projection I/O layer — the filesystem side of region projection.
//!
//! [`region_weave`](crate::region_weave) is pure: it turns a [`RegionInput`]
//! into in-memory artifact files. This module is the I/O orchestration around
//! it, shared by both the `x0k-tangle weave-region` CLI and the
//! `tangle_weave_region` MCP tool so the two surfaces behave identically:
//!
//! 1. Parse the publication decision doc into a [`RegionInput`]
//!    ([`parse_publication_region`]) — resolving its `publishes:` edge to
//!    member files with the shared envelope parser from `x0k-folio`.
//! 2. Call [`weave_region`].
//! 3. Write each [`ArtifactFile`](crate::ArtifactFile).
//! 4. (Unless `no_motifs`, and only with the `motifs` feature) content-address
//!    + copy the region's surface wasm, vendoring a static `host.js` shim.
//!
//! # The corpus layout invariant
//!
//! Region resolution needs one fact about the corpus this module carries
//! itself: where each document class lives. A member URI
//! `x0k:<class>/<stem>` names the file `<stem>.md` under the class's
//! directory (`decisions/<subtype>/`, topic subdirectories included, or
//! `knowledge/wiki/` for wiki pages). That table is `member_dir` below, and
//! every other tool that resolves member URIs against the corpus must agree
//! with it.

use crate::region_weave::{weave_region, RegionInput, RegionMember};
use anyhow::{anyhow, Context, Result};
use std::path::{Path, PathBuf};

/// Summary of a region-projection run. Mirrors the MCP `tangle_weave_region`
/// result shape so the CLI and MCP surfaces report identically.
#[derive(Debug, Clone)]
pub struct RegionProjectReport {
    /// Absolute (or output-dir-relative) entry page path the reader lands on.
    pub entry_rel_path: PathBuf,
    /// Number of HTML pages written.
    pub page_count: usize,
    /// Deduped union of `x0k:media` refs across members.
    pub media_refs: Vec<String>,
    /// Refs that show their static `.media-label` fallback (not bundled as
    /// canvas wasm).
    pub degraded_embeds: Vec<String>,
    /// Links that pointed outside the region (kept verbatim in the HTML).
    pub unresolved_links: Vec<String>,
    /// Atlas node count (members positioned in the time×thread plane).
    pub atlas_node_count: usize,
    /// Atlas influence-edge count.
    pub atlas_edge_count: usize,
    /// Distinct thread lanes present in the atlas.
    pub atlas_threads: Vec<String>,
    /// Member URIs whose year could not be resolved (flagged, off the plane).
    pub atlas_unresolved_years: Vec<String>,
    /// Whether the render-vello wasm renderer was bundled into `wasm/`. When
    /// false the artifact still serves the semantic fallback pages; the canvas
    /// shell just can't boot (and redirects to the fallback).
    pub wasm_bundled: bool,
    /// Size in bytes of the bundled render-vello `_bg.wasm` (0 if not bundled).
    pub wasm_bytes: u64,
    /// Whether a `narrative.json` trail sidecar was found and bundled (vs. the
    /// empty-station stub).
    pub narrative_bundled: bool,
}

/// Project a publication doc into a self-contained multi-page artifact under
/// `output_dir`. The single I/O entry point shared by the CLI and MCP tool.
pub fn project_publication(
    region_doc: &Path,
    output_dir: &Path,
    workspace: &Path,
    no_motifs: bool,
) -> Result<RegionProjectReport> {
    let content = std::fs::read_to_string(region_doc)
        .with_context(|| format!("reading publication doc {}", region_doc.display()))?;
    // The narrative trail sidecar lives beside the publication doc:
    // `decisions/publications/<stem>.narrative.json` (its canonical, editable,
    // reproducible home). Read it here so the pure presentation layer stays
    // disk-free.
    let narrative = read_narrative_sidecar(region_doc);
    project_publication_content(&content, output_dir, workspace, no_motifs, narrative)
}

/// Read the `<stem>.narrative.json` sidecar next to a publication doc, if any.
fn read_narrative_sidecar(region_doc: &Path) -> Option<Vec<u8>> {
    let stem = region_doc.file_stem()?;
    let mut name = stem.to_os_string();
    name.push(".narrative.json");
    let sidecar = region_doc.with_file_name(name);
    std::fs::read(&sidecar).ok()
}

/// Like [`project_publication`] but takes the publication doc's content
/// directly (the MCP tool already read it / resolved its path). `narrative_json`
/// is the optional scripted-trail sidecar bytes (the path-based entry point
/// reads it from disk; direct callers may pass `None` for the empty stub).
pub fn project_publication_content(
    region_content: &str,
    output_dir: &Path,
    workspace: &Path,
    no_motifs: bool,
    narrative_json: Option<Vec<u8>>,
) -> Result<RegionProjectReport> {
    let input = parse_publication_region(region_content, workspace)?;
    let mut out = weave_region(&input).context("weaving region")?;

    // Wrap the woven semantic substrate into the self-booting presentation:
    // canvas shell at the root, woven pages → `pages/` fallback, bundled
    // `members.json` + `narrative.json`. `atlas.json` stays at the root.
    let narrative_bundled = narrative_json.is_some();
    crate::presentation::apply_publication_shell(&mut out, &input, narrative_json);

    std::fs::create_dir_all(output_dir)
        .with_context(|| format!("creating output dir {}", output_dir.display()))?;
    for f in &out.files {
        let dest = output_dir.join(&f.rel_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, &f.bytes).with_context(|| format!("writing {}", dest.display()))?;
    }

    // Bundle the render-vello wasm so the canvas shell boots offline. The
    // motif/surface subsystem is publish-excludable (the `motifs` feature): the
    // standalone/OSS x0k-tangle builds `--no-default-features`, dropping the
    // x0k-surface-build dep and this HTML-weave-only bundling.
    #[cfg(feature = "motifs")]
    let (wasm_bundled, wasm_bytes) = bundle_render_vello_wasm(workspace, output_dir)?;
    #[cfg(not(feature = "motifs"))]
    let (wasm_bundled, wasm_bytes) = (false, 0u64);

    #[cfg(feature = "motifs")]
    let degraded = {
        let mut degraded = out.degraded_embeds.clone();
        if !no_motifs && !out.media_refs.is_empty() {
            bundle_region_motifs(workspace, output_dir, &out.media_refs, &mut degraded)?;
        }
        degraded
    };
    #[cfg(not(feature = "motifs"))]
    let degraded = {
        let _ = (&no_motifs, &workspace);
        out.degraded_embeds.clone()
    };

    // Count the woven semantic fallback pages (under `pages/`), not the shell.
    let page_count = out
        .files
        .iter()
        .filter(|f| {
            f.rel_path.extension().map(|e| e == "html").unwrap_or(false)
                && f.rel_path.starts_with(crate::presentation::FALLBACK_DIR)
        })
        .count();
    Ok(RegionProjectReport {
        entry_rel_path: out.entry_rel_path,
        page_count,
        media_refs: out.media_refs,
        degraded_embeds: degraded,
        unresolved_links: out.unresolved_links,
        atlas_node_count: out.atlas.nodes.len(),
        atlas_edge_count: out.atlas.edges.len(),
        atlas_threads: out.atlas.threads.clone(),
        atlas_unresolved_years: out.atlas.unresolved_years.clone(),
        wasm_bundled,
        wasm_bytes,
        narrative_bundled,
    })
}

/// Names of the two render-vello wasm-pack outputs the boot shell imports
/// (`boot.js` does `import('./wasm/x0k_ui_render_vello.js')`, which resolves the
/// `_bg.wasm` sibling).
#[cfg(feature = "motifs")]
const RENDER_VELLO_JS: &str = "x0k_ui_render_vello.js";
#[cfg(feature = "motifs")]
const RENDER_VELLO_WASM: &str = "x0k_ui_render_vello_bg.wasm";

/// Copy the prebuilt render-vello wasm-pack bundle into the artifact's `wasm/`
/// so the canvas shell boots offline. The bundle is located via
/// `X0K_RENDER_VELLO_WASM_DIR` (release+wasm-opt build output), falling back to
/// the monorepo web UI's dev-build location
/// `<workspace>/ui/0k.computer/wasm/render-vello`.
///
/// The wasm is a prebuilt binary, not derivable data, so the projection copies
/// it rather than invoking the (multi-minute) wasm-pack build inline. Build it
/// once with:
/// `wasm-pack build ui/render-vello --target web --release --out-dir <dir>`.
///
/// Returns `(bundled, bytes)`. If the bundle is absent the artifact still ships
/// the semantic fallback; the shell detects the missing renderer and redirects.
#[cfg(feature = "motifs")]
fn bundle_render_vello_wasm(workspace: &Path, output_dir: &Path) -> Result<(bool, u64)> {
    let dir = std::env::var_os("X0K_RENDER_VELLO_WASM_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| workspace.join("ui/0k.computer/wasm/render-vello"));
    let js = dir.join(RENDER_VELLO_JS);
    let wasm = dir.join(RENDER_VELLO_WASM);
    if !js.is_file() || !wasm.is_file() {
        return Ok((false, 0));
    }
    let wasm_dir = output_dir.join("wasm");
    std::fs::create_dir_all(&wasm_dir)?;
    std::fs::copy(&js, wasm_dir.join(RENDER_VELLO_JS))
        .with_context(|| format!("copying {}", js.display()))?;
    let wasm_dest = wasm_dir.join(RENDER_VELLO_WASM);
    let bytes =
        std::fs::copy(&wasm, &wasm_dest).with_context(|| format!("copying {}", wasm.display()))?;
    // Brotli-precompress the render-vello host wasm too — it's the largest
    // single artifact and loads on every publication page. Served via
    // `ServeDir::precompressed_br` exactly like the motif `.br` siblings.
    x0k_surface_build::ensure_brotli(&wasm_dest)
        .with_context(|| format!("brotli-precompressing {}", wasm_dest.display()))?;
    Ok((true, bytes))
}

/// Resolve a publication doc into a [`RegionInput`]: read its `publishes:`
/// edge with the shared envelope parser and map each member URI to its
/// file. Member sources are read here (the pure weaver takes pre-read
/// content).
pub fn parse_publication_region(content: &str, workspace: &Path) -> Result<RegionInput> {
    use x0k_folio::colophon::{parse_envelope, DocType};

    let (env, _body) =
        parse_envelope(content).map_err(|e| anyhow!("not a folio/v1 document: {e:?}"))?;
    if env.doc_type != DocType::Publication {
        return Err(anyhow!(
            "document is not a publication (type is `{}`)",
            env.doc_type.as_str()
        ));
    }

    let member_uris: Vec<String> = env.edges.get("publishes").cloned().unwrap_or_default();
    if member_uris.is_empty() {
        return Err(anyhow!("publication has an empty `publishes` membership"));
    }

    let entry_point_uri = env
        .edges
        .get("entryPoint")
        .or_else(|| env.edges.get("entry_point"))
        .and_then(|v| v.first().cloned())
        .or_else(|| {
            if member_uris.len() == 1 {
                member_uris.first().cloned()
            } else {
                None
            }
        })
        .ok_or_else(|| {
            anyhow!(
                "publication has no `entryPoint` and {} members; entry point is ambiguous",
                member_uris.len()
            )
        })?;

    let members = member_uris
        .iter()
        .map(|uri| {
            let src = member_doc_path(uri, workspace);
            let content = std::fs::read_to_string(&src).unwrap_or_default();
            let rel = src.strip_prefix(workspace).unwrap_or(&src).to_path_buf();
            RegionMember {
                uri: uri.clone(),
                content,
                source_path: rel,
            }
        })
        .collect::<Vec<_>>();

    Ok(RegionInput {
        members,
        entry_point_uri,
    })
}

/// The decision file backing one member URI.
///
/// A decision's id carries no topic (`x0k:architecture/identity`) but the
/// files are organized into topic subdirectories, so the stem is searched for
/// under the subtype root before falling back to the flat join — the flat
/// path is what a missing member reports, so a dangling member still names a
/// path.
fn member_doc_path(uri: &str, workspace: &Path) -> PathBuf {
    let rest = uri.strip_prefix("x0k:").unwrap_or(uri);
    let (class, identifier) = match rest.split_once('/') {
        Some((c, i)) => (c, i),
        None => ("", rest),
    };
    let dir = workspace.join(member_dir(class));
    let file_name = format!("{identifier}.md");
    let flat = dir.join(&file_name);
    if flat.is_file() {
        return flat;
    }
    walkdir::WalkDir::new(&dir)
        .max_depth(DECISION_TOPIC_DEPTH)
        .into_iter()
        .filter_map(|e| e.ok())
        .map(|e| e.into_path())
        .find(|p| p.is_file() && p.file_name().and_then(|s| s.to_str()) == Some(file_name.as_str()))
        .unwrap_or(flat)
}

/// Walk depth for a decision subtype root: the directory, its topic
/// subdirectories, and one level of headroom.
const DECISION_TOPIC_DEPTH: usize = 3;

/// Map an entity-URI class to the corpus directory its documents live in —
/// the layout invariant from the module doc. Every tool that resolves
/// member URIs against the corpus must agree with this table.
fn member_dir(class: &str) -> PathBuf {
    // Wiki pages live under `knowledge/wiki/`, not `decisions/`. Return the
    // full repo-relative dir directly.
    if class == "wiki" {
        return Path::new("knowledge").join("wiki");
    }
    // Authored manuscripts live top-level under `manuscripts/`, not `decisions/`.
    if class == "manuscript" {
        return PathBuf::from("manuscripts");
    }
    let leaf = match class {
        "design" => "design",
        "architecture" => "architecture",
        "commitment" => "commitments",
        "bundle" => "bundles",
        "publication" => "publications",
        other => other,
    };
    Path::new("decisions").join(leaf)
}

/// Content-address the region's surfaces and copy each resolved `.wasm` into the
/// artifact under `wasm/x0k_surface_<name>.wasm`, vendoring a static `host.js`
/// shim. Refs resolving to no buildable surface keep their static label and stay
/// in `degraded`.
#[cfg(feature = "motifs")]
fn bundle_region_motifs(
    workspace: &Path,
    output_dir: &Path,
    media_refs: &[String],
    degraded: &mut Vec<String>,
) -> Result<()> {
    let region_refs: std::collections::BTreeSet<&str> =
        media_refs.iter().map(|s| s.as_str()).collect();

    let embedded = x0k_surface_build::embed_scan(workspace).context("scanning surface embeds")?;
    let mut uri_to_surface: std::collections::BTreeMap<&str, &x0k_surface_build::SurfaceRef> =
        std::collections::BTreeMap::new();
    for em in &embedded {
        if !region_refs.contains(em.doc_uri.as_str()) {
            continue;
        }
        if let Some(m) = &em.surface {
            uri_to_surface.insert(em.doc_uri.as_str(), m);
        }
    }
    if uri_to_surface.is_empty() {
        return Ok(());
    }

    let report = x0k_surface_build::publish::publish(workspace, true)
        .context("content-addressing surfaces")?;
    let by_crate: std::collections::BTreeMap<&str, &x0k_surface_build::publish::PublishedSurface> =
        report
            .published
            .iter()
            .map(|p| (p.crate_name.as_str(), p))
            .collect();

    let wasm_dir = output_dir.join("wasm");
    std::fs::create_dir_all(&wasm_dir)?;
    let mut bundled_any = false;
    // `data-media-ref` URI → bundled wasm filename, consumed by `host.js`.
    let mut manifest: std::collections::BTreeMap<String, String> =
        std::collections::BTreeMap::new();

    for (uri, surface) in &uri_to_surface {
        if let Some(published) = by_crate.get(surface.crate_name.as_str()) {
            let file = format!("{}.wasm", surface.wasm_name);
            let dest = wasm_dir.join(&file);
            std::fs::copy(&published.cache_path, &dest).with_context(|| {
                format!(
                    "copying {} → {}",
                    published.cache_path.display(),
                    dest.display()
                )
            })?;
            // Copy the brotli sibling alongside so the prod static serve
            // (`ServeDir::precompressed_br`) can offer `Content-Encoding: br`.
            if let Some(br_src) = &published.br_cache_path {
                let br_dest = wasm_dir.join(format!("{file}.br"));
                std::fs::copy(br_src, &br_dest).with_context(|| {
                    format!("copying {} → {}", br_src.display(), br_dest.display())
                })?;
            }
            degraded.retain(|d| d != uri);
            manifest.insert((*uri).to_string(), file);
            bundled_any = true;
        }
    }

    if bundled_any {
        std::fs::write(wasm_dir.join("host.js"), HOST_JS_SHIM).context("writing host.js loader")?;
        let manifest_json =
            serde_json::to_vec_pretty(&manifest).context("serializing motifs.json")?;
        std::fs::write(wasm_dir.join("motifs.json"), manifest_json)
            .context("writing motifs.json manifest")?;
    }
    Ok(())
}

/// Vendored static motif host loader. This is the real mount, not a stub that
/// tags embeds with a static fallback: it instantiates each
/// embedded motif's GPU-free `.wasm`, drives the v2 message ABI
/// (`surface_create`/`surface_send_event`/`surface_frame`/...), and renders the
/// emitted paint-IR through the bundled render-vello vello/WebGPU host onto a
/// per-embed canvas. It is a vanilla-JS ES-module port of the monorepo web
/// UI's motif loader (`ui/0k.computer/src/motif-loader.ts::loadMotif`), so a
/// published motif runs byte-identically to the live app.
///
/// All asset URLs resolve relative to this module (`import.meta.url`), so the
/// loader works regardless of which page-depth includes it (the fallback pages
/// live under `pages/`, so they reference `../wasm/host.js`). A `motifs.json`
/// manifest (written beside this file) maps each `data-media-ref` to its bundled
/// wasm filename. Progressive enhancement: an embed whose ref is not in the
/// manifest — or any embed when WebGPU is unavailable — keeps its static
/// `.media-label` fallback.
#[cfg(feature = "motifs")]
const HOST_JS_SHIM: &str = r#"// Static publication motif host — instantiates each embedded motif's wasm,
// drives the v2 message ABI, and renders its paint-IR through render-vello's
// vello/WebGPU host onto a per-embed canvas. Vanilla-JS port of the live app's
// motif-loader. Progressive enhancement: embeds with no bundled wasm (or when
// WebGPU is absent) keep their static label.
const BASE = import.meta.url;
const u = (p) => new URL(p, BASE).href;
let seq = 0;
let hostPromise = null;
let maxStyleInjected = false;

async function loadHost() {
  if (!hostPromise) {
    hostPromise = (async () => {
      const mod = await import(u('./x0k_ui_render_vello.js'));
      await mod.default();
      window.__c0k_motif_host = mod;
      return mod;
    })();
  }
  return hostPromise;
}

function stubImports(module) {
  const imports = {};
  for (const desc of WebAssembly.Module.imports(module)) {
    const m = (imports[desc.module] ??= {});
    if (desc.kind === 'function') m[desc.name] = () => 0;
    else if (desc.kind === 'memory') m[desc.name] = new WebAssembly.Memory({ initial: 1 });
    else if (desc.kind === 'table') m[desc.name] = new WebAssembly.Table({ initial: 1, element: 'anyfunc' });
    else if (desc.kind === 'global') m[desc.name] = new WebAssembly.Global({ value: 'i32', mutable: true }, 0);
  }
  return imports;
}

async function instantiateMotif(wasmUrl, w, h) {
  const resp = await fetch(wasmUrl);
  if (!resp.ok) throw new Error('fetch motif wasm ' + resp.status + ' ' + wasmUrl);
  const bytes = await resp.arrayBuffer();
  const module = await WebAssembly.compile(bytes);
  const instance = await WebAssembly.instantiate(module, stubImports(module));
  const motif = instance.exports;
  const handle = motif.surface_create(w, h);
  return { motif, handle };
}

// The render-vello motif host has NO device-pixel-ratio transform: it replays
// the guest's logical-coordinate paint-IR straight into a device-pixel render
// texture (`canvas.width`×`canvas.height`). So the guest must be sized — and
// fed pointer coordinates — in DEVICE pixels for its paint to FILL the canvas
// backing store; otherwise the paint covers only `1/dpr` of the box, leaving
// black gutters on the right and bottom. We therefore drive the guest at
// `cssBox × dpr` and scale pointer coords by `dpr` to match.
const DPR = () => Math.min(window.devicePixelRatio || 1, 2);

// One mounted motif embed: a canvas filling its container, the GPU-free guest,
// the render-vello host handle, and a resize path the ResizeObserver + the
// maximize affordance both reuse.
async function mount(el, ref, file) {
  let host;
  try { host = await loadHost(); }
  catch (e) { console.warn('[motif] host init failed (no WebGPU?):', e); return; }

  const dpr = DPR();
  const label = el.querySelector('.media-label');
  if (label) label.style.display = 'none';
  el.classList.add('media-live');

  // A positioned wrapper so the canvas, the maximize button, and (when
  // maximized) the close button stack predictably.
  const stage = document.createElement('div');
  stage.className = 'motif-stage';
  const canvas = document.createElement('canvas');
  canvas.id = 'motif-canvas-' + (seq++);
  canvas.className = 'motif-canvas';
  canvas.style.width = '100%';
  canvas.style.height = '100%';
  canvas.style.display = 'block';
  stage.appendChild(canvas);
  el.appendChild(stage);

  // Backing-store dims = the canvas CSS box × dpr (device pixels). Done BEFORE
  // host init: `motif_init` reads `canvas.width`/`canvas.height` to size its
  // surface.
  const cssW = () => Math.max(1, Math.round(canvas.clientWidth || el.clientWidth || 640));
  const cssH = () => Math.max(1, Math.round(canvas.clientHeight || 320));
  let devW = Math.round(cssW() * dpr);
  let devH = Math.round(cssH() * dpr);
  canvas.width = devW;
  canvas.height = devH;

  let renderHandle;
  try { renderHandle = await host.motif_init(canvas.id); }
  catch (e) {
    console.warn('[motif] motif_init failed:', e);
    if (label) label.style.display = '';
    stage.remove();
    return;
  }

  // Guest is sized in DEVICE pixels (see DPR note above) so its paint fills the
  // backing store.
  let { motif, handle } = await instantiateMotif(u('./' + file), devW, devH);

  function sendBytes(ev) {
    if (!ev || ev.length === 0) return;
    const ptr = motif.surface_alloc(ev.length);
    new Uint8Array(motif.memory.buffer, ptr, ev.length).set(ev);
    motif.surface_send_event(handle, ptr, ev.length);
    motif.surface_free(ptr, ev.length);
  }

  // The shared resize path: recompute the device backing store from the current
  // CSS box, reconfigure the host surface, and tell the guest its new logical
  // (= device, here) extent. Reused by the ResizeObserver and maximize toggle.
  function applySize() {
    const d = DPR();
    const nw = Math.max(1, Math.round(cssW() * d));
    const nh = Math.max(1, Math.round(cssH() * d));
    if (nw === devW && nh === devH) return;
    devW = nw; devH = nh;
    canvas.width = devW;
    canvas.height = devH;
    try { host.motif_resize(renderHandle, devW, devH); } catch (e) { /* pre-init */ }
    sendBytes(host.motif_encode_resize(devW, devH));
  }

  const localXY = (e) => {
    const r = canvas.getBoundingClientRect();
    // CSS px → device px so coords land in the guest's device-px space.
    const sx = r.width ? canvas.width / r.width : 1;
    const sy = r.height ? canvas.height / r.height : 1;
    return [(e.clientX - r.left) * sx, (e.clientY - r.top) * sy];
  };
  canvas.addEventListener('mousedown', (e) => { const [x, y] = localXY(e); sendBytes(host.motif_encode_pointer(0, x, y, e.button, e.shiftKey, e.ctrlKey, e.altKey, e.metaKey)); });
  canvas.addEventListener('mouseup', (e) => { const [x, y] = localXY(e); sendBytes(host.motif_encode_pointer(1, x, y, e.button, e.shiftKey, e.ctrlKey, e.altKey, e.metaKey)); });
  canvas.addEventListener('mousemove', (e) => { const [x, y] = localXY(e); sendBytes(host.motif_encode_pointer(2, x, y, -1, e.shiftKey, e.ctrlKey, e.altKey, e.metaKey)); });
  canvas.addEventListener('wheel', (e) => { e.preventDefault(); const [x, y] = localXY(e); sendBytes(host.motif_encode_wheel(e.deltaX, e.deltaY, x, y, e.shiftKey, e.ctrlKey, e.altKey, e.metaKey)); }, { passive: false });

  // Reflow whenever the container box changes (column resize, fullscreen
  // enter/exit, font load). ResizeObserver fires once on observe, so the box
  // is sized correctly on first layout even if `clientWidth` was 0 at mount.
  const ro = new ResizeObserver(() => applySize());
  ro.observe(canvas);

  // ── Maximize affordance ────────────────────────────────────────────────
  // A small ⤢ button overlaid top-right; click moves the stage into a
  // fullscreen overlay (the motif resizes to fill it via applySize). ESC, the
  // close button, or a click on the backdrop restores it in place.
  injectMaxStyle();
  let maximized = false;
  let overlay = null;
  const maxBtn = document.createElement('button');
  maxBtn.type = 'button';
  maxBtn.className = 'motif-max-btn';
  maxBtn.title = 'Maximize';
  maxBtn.setAttribute('aria-label', 'Maximize visualization');
  maxBtn.textContent = '⤢'; // ⤢
  stage.appendChild(maxBtn);

  function enterMax() {
    if (maximized) return;
    maximized = true;
    overlay = document.createElement('div');
    overlay.className = 'motif-overlay';
    const closeBtn = document.createElement('button');
    closeBtn.type = 'button';
    closeBtn.className = 'motif-close-btn';
    closeBtn.title = 'Close (Esc)';
    closeBtn.setAttribute('aria-label', 'Close maximized visualization');
    closeBtn.textContent = '×'; // ×
    overlay.appendChild(stage);
    overlay.appendChild(closeBtn);
    document.body.appendChild(overlay);
    maxBtn.textContent = '⤡'; // ⤡ (restore)
    maxBtn.title = 'Restore';
    closeBtn.addEventListener('click', exitMax);
    overlay.addEventListener('mousedown', (e) => { if (e.target === overlay) exitMax(); });
    document.addEventListener('keydown', onKey);
    // Two rAFs so the overlay has laid out before we measure the new box.
    requestAnimationFrame(() => requestAnimationFrame(applySize));
  }
  function exitMax() {
    if (!maximized) return;
    maximized = false;
    document.removeEventListener('keydown', onKey);
    el.appendChild(stage); // back to its in-prose home
    if (overlay) { overlay.remove(); overlay = null; }
    maxBtn.textContent = '⤢';
    maxBtn.title = 'Maximize';
    requestAnimationFrame(() => requestAnimationFrame(applySize));
  }
  function onKey(e) { if (e.key === 'Escape') exitMax(); }
  maxBtn.addEventListener('click', (e) => { e.stopPropagation(); maximized ? exitMax() : enterMax(); });

  let last = performance.now();
  function frame(now) {
    const dt = now - last; last = now;
    sendBytes(host.motif_encode_tick(dt));
    const packed = motif.surface_frame(handle);
    if (packed !== 0n) {
      const ptr = Number(packed >> 32n);
      const len = Number(packed & 0xffffffffn);
      const fb = new Uint8Array(motif.memory.buffer, ptr, len).slice();
      motif.surface_free(ptr, len);
      try { host.motif_render_frame(renderHandle, fb); }
      catch (err) { console.warn('[motif] render_frame:', err); }
    }
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);

  // Expose mounted motifs so a headless validator can read pixels back
  // (offscreen GPU readback bypasses the swapchain present cap) and confirm the
  // embed went live + filled its box.
  (window.__c0k_motifs ??= []).push({
    ref, file, canvas, renderHandle,
    get deviceSize() { return [canvas.width, canvas.height]; },
    get maximized() { return maximized; },
    maximize: enterMax,
    restore: exitMax,
    captureFrame: (w, h) => host.motif_capture_frame(renderHandle, w, h),
  });
  window.dispatchEvent(new CustomEvent('x0k:motif-ready', { detail: { ref } }));
}

// Scoped CSS for the embed stage, the maximize button, and the fullscreen
// overlay. Injected once, on first mount, so the static artifact needs no
// extra stylesheet. The embed box gets a real height (the weaver's
// `.media-embed` only set `min-height`), and the canvas fills it.
function injectMaxStyle() {
  if (maxStyleInjected) return;
  maxStyleInjected = true;
  const css = `
.media-embed.media-live { padding: 0; display: block; min-height: 0; overflow: hidden; border-style: solid; }
.motif-stage { position: relative; width: 100%; height: clamp(280px, 42vh, 460px); background: #101016; }
.motif-canvas { touch-action: none; }
.motif-max-btn {
  position: absolute; top: 8px; right: 8px; z-index: 2;
  width: 30px; height: 30px; padding: 0; line-height: 28px; text-align: center;
  font-size: 16px; cursor: pointer; border-radius: 6px;
  color: #e8e8ef; background: rgba(22,22,30,0.62);
  border: 1px solid rgba(220,220,235,0.28); backdrop-filter: blur(2px);
  transition: background 0.12s, opacity 0.12s; opacity: 0.55;
}
.motif-stage:hover .motif-max-btn { opacity: 1; }
.motif-max-btn:hover { background: rgba(40,40,54,0.9); }
.motif-overlay {
  position: fixed; inset: 0; z-index: 1000; display: flex;
  align-items: center; justify-content: center;
  background: rgba(10,10,14,0.82); backdrop-filter: blur(3px); padding: 3vmin;
}
.motif-overlay .motif-stage {
  width: 94vw; height: 88vh; max-width: 1600px;
  box-shadow: 0 24px 80px rgba(0,0,0,0.5); border-radius: 8px; overflow: hidden;
}
.motif-close-btn {
  position: fixed; top: 18px; right: 22px; z-index: 1001;
  width: 38px; height: 38px; padding: 0; line-height: 34px; text-align: center;
  font-size: 22px; cursor: pointer; border-radius: 8px;
  color: #f2f2f6; background: rgba(30,30,40,0.7);
  border: 1px solid rgba(220,220,235,0.32);
}
.motif-close-btn:hover { background: rgba(54,54,70,0.95); }
`;
  const tag = document.createElement('style');
  tag.setAttribute('data-x0k-surface-host', '');
  tag.textContent = css;
  document.head.appendChild(tag);
}

(async function () {
  let manifest = {};
  try {
    const r = await fetch(u('./motifs.json'));
    if (r.ok) manifest = await r.json();
  } catch (e) { /* no manifest → every embed stays static */ }
  document.querySelectorAll('.media-embed[data-media-ref]').forEach((el) => {
    const ref = el.getAttribute('data-media-ref');
    const file = manifest[ref];
    el.setAttribute('data-static-fallback', file ? 'false' : 'true');
    if (file) void mount(el, ref, file);
  });
})();
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn member_dir_maps_wiki_to_knowledge_wiki() {
        // Wiki members live under knowledge/wiki, not decisions/ — the layout
        // invariant the module doc states.
        assert_eq!(member_dir("wiki"), Path::new("knowledge").join("wiki"));
        assert_eq!(member_dir("design"), Path::new("decisions").join("design"));
        assert_eq!(
            member_dir("architecture"),
            Path::new("decisions").join("architecture")
        );
    }

    #[test]
    fn member_doc_path_for_wiki_uri() {
        let ws = Path::new("/repo");
        let p = member_doc_path("x0k:wiki/hypercard", ws);
        assert_eq!(p, Path::new("/repo/knowledge/wiki/hypercard.md"));
    }
}
