// @generated by x0k-tangle (pipeline: identity-tangle) from knowledge/implementation/tangle/source-refs.md — DO NOT EDIT.
use anyhow::{bail, Result};
use tree_sitter::{Node, Parser};

#[derive(Debug, Clone)]
pub struct SymbolSpan {
    pub name: String,
    pub body: String,
    pub start_line: usize,
    pub end_line: usize,
    pub byte_start: usize,
    pub byte_end: usize,
}

pub fn extract_symbol(source: &str, symbol_path: &str) -> Result<SymbolSpan> {
    let mut parser = Parser::new();
    let lang = tree_sitter_rust::LANGUAGE;
    parser
        .set_language(&lang.into())
        .map_err(|e| anyhow::anyhow!("tree-sitter language error: {}", e))?;

    let tree = parser
        .parse(source, None)
        .ok_or_else(|| anyhow::anyhow!("tree-sitter parse failed"))?;

    let parts: Vec<&str> = symbol_path.split("::").collect();

    let mut matches = Vec::new();
    collect_matching_symbols(tree.root_node(), source, &parts, 0, &mut matches);

    match matches.len() {
        0 => bail!("symbol '{}' not found", symbol_path),
        1 => Ok(matches.into_iter().next().unwrap()),
        _ => {
            // Prefer exact depth match
            if let Some(m) = matches.iter().find(|m| {
                m.name == symbol_path || m.name == *parts.last().unwrap_or(&"")
            }) {
                Ok(m.clone())
            } else {
                Ok(matches.into_iter().next().unwrap())
            }
        }
    }
}

pub fn list_symbols(source: &str) -> Result<Vec<SymbolSpan>> {
    let mut parser = Parser::new();
    let lang = tree_sitter_rust::LANGUAGE;
    parser
        .set_language(&lang.into())
        .map_err(|e| anyhow::anyhow!("tree-sitter language error: {}", e))?;

    let tree = parser
        .parse(source, None)
        .ok_or_else(|| anyhow::anyhow!("tree-sitter parse failed"))?;

    let mut symbols = Vec::new();
    collect_all_symbols(tree.root_node(), source, &[], &mut symbols);
    Ok(symbols)
}

fn node_text<'a>(node: Node, source: &'a str) -> &'a str {
    &source[node.byte_range()]
}

fn named_child_text(node: Node, source: &str) -> Option<String> {
    node.child_by_field_name("name")
        .map(|child| node_text(child, source).to_string())
        .or_else(|| {
            node.children(&mut node.walk())
                .find(|child| {
                    child.kind() == "identifier" || child.kind() == "type_identifier"
                })
                .map(|child| node_text(child, source).to_string())
        })
}

fn impl_type_name(node: Node, source: &str) -> Option<String> {
    // For `impl Foo { ... }`, extract "Foo"
    // For `impl Trait for Foo { ... }`, extract "Foo"
    node.child_by_field_name("type")
        .map(|t| node_text(t, source).to_string())
}

fn make_span(name: String, node: Node, source: &str) -> SymbolSpan {
    SymbolSpan {
        name,
        body: node_text(node, source).to_string(),
        start_line: node.start_position().row + 1,
        end_line: node.end_position().row + 1,
        byte_start: node.start_byte(),
        byte_end: node.end_byte(),
    }
}

fn collect_matching_symbols(
    node: Node,
    source: &str,
    parts: &[&str],
    depth: usize,
    matches: &mut Vec<SymbolSpan>,
) {
    if depth >= parts.len() {
        return;
    }

    let target = parts[depth];
    let is_last = depth == parts.len() - 1;

    for child in node.children(&mut node.walk()) {
        match child.kind() {
            "function_item" | "struct_item" | "enum_item" | "type_item"
            | "const_item" | "static_item" | "trait_item" | "macro_definition" => {
                if let Some(name) = named_child_text(child, source) {
                    if name == target && is_last {
                        matches.push(make_span(name, child, source));
                    }
                }
            }
            "impl_item" => {
                if let Some(type_name) = impl_type_name(child, source) {
                    if type_name == target && !is_last {
                        // Descend into impl to find methods
                        if let Some(body) = child.child_by_field_name("body") {
                            collect_matching_symbols(
                                body, source, parts, depth + 1, matches,
                            );
                        }
                    }
                    if type_name == target && is_last {
                        matches.push(make_span(
                            format!("impl {}", type_name),
                            child,
                            source,
                        ));
                    }
                }
            }
            // Recurse into module bodies
            "mod_item" => {
                if let Some(name) = named_child_text(child, source) {
                    if name == target && !is_last {
                        for grandchild in child.children(&mut child.walk()) {
                            if grandchild.kind() == "declaration_list" {
                                collect_matching_symbols(
                                    grandchild, source, parts, depth + 1, matches,
                                );
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }

    // Also try matching at current depth without consuming a part
    // (for top-level items when depth == 0 and parts.len() == 1)
    if depth == 0 && parts.len() == 1 {
        // Already handled above
    }
}

fn collect_all_symbols(
    node: Node,
    source: &str,
    prefix: &[String],
    symbols: &mut Vec<SymbolSpan>,
) {
    for child in node.children(&mut node.walk()) {
        match child.kind() {
            "function_item" | "struct_item" | "enum_item" | "type_item"
            | "const_item" | "static_item" | "trait_item" | "macro_definition" => {
                if let Some(name) = named_child_text(child, source) {
                    let full_name = if prefix.is_empty() {
                        name
                    } else {
                        format!("{}::{}", prefix.join("::"), name)
                    };
                    symbols.push(make_span(full_name, child, source));
                }
            }
            "impl_item" => {
                if let Some(type_name) = impl_type_name(child, source) {
                    let impl_prefix = if prefix.is_empty() {
                        vec![type_name.clone()]
                    } else {
                        let mut p = prefix.to_vec();
                        p.push(type_name.clone());
                        p
                    };
                    if let Some(body) = child.child_by_field_name("body") {
                        collect_all_symbols(body, source, &impl_prefix, symbols);
                    }
                }
            }
            "mod_item" => {
                if let Some(name) = named_child_text(child, source) {
                    let mut new_prefix = prefix.to_vec();
                    new_prefix.push(name);
                    for grandchild in child.children(&mut child.walk()) {
                        if grandchild.kind() == "declaration_list" {
                            collect_all_symbols(grandchild, source, &new_prefix, symbols);
                        }
                    }
                }
            }
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
use std::io;

enum DrawCommand {
    Fill(Path),
    Stroke(Path),
}

struct Canvas2DState {
    path: Vec<u8>,
    fill_color: Color,
}

impl Canvas2DState {
    pub fn new() -> Self {
        Self { path: Vec::new(), fill_color: Color::BLACK }
    }

    pub fn arc(&mut self, x: f64, y: f64, radius: f64) {
        // arc implementation
        let sweep = x + y;
    }

    pub fn flush(&self) {
        // flush implementation
    }
}

impl Default for Canvas2DState {
    fn default() -> Self {
        Self::new()
    }
}

fn helper() -> bool {
    true
}

#[cfg(test)]
mod tests {
    fn test_it() {}
}
"#;

    #[test]
    fn extract_top_level_enum() {
        let span = extract_symbol(SAMPLE, "DrawCommand").unwrap();
        assert!(span.body.contains("enum DrawCommand"));
        assert!(span.body.contains("Stroke"));
    }

    #[test]
    fn extract_top_level_struct() {
        let span = extract_symbol(SAMPLE, "Canvas2DState").unwrap();
        assert!(span.body.contains("struct Canvas2DState"));
        assert!(span.body.contains("fill_color"));
    }

    #[test]
    fn extract_method() {
        let span = extract_symbol(SAMPLE, "Canvas2DState::arc").unwrap();
        assert!(span.body.contains("pub fn arc"));
        assert!(span.body.contains("sweep"));
        assert!(!span.body.contains("pub fn flush"));
    }

    #[test]
    fn extract_top_level_fn() {
        let span = extract_symbol(SAMPLE, "helper").unwrap();
        assert!(span.body.contains("fn helper"));
    }

    #[test]
    fn missing_symbol_errors() {
        assert!(extract_symbol(SAMPLE, "nonexistent").is_err());
    }

    #[test]
    fn list_finds_all() {
        let syms = list_symbols(SAMPLE).unwrap();
        let names: Vec<&str> = syms.iter().map(|s| s.name.as_str()).collect();
        assert!(names.contains(&"DrawCommand"));
        assert!(names.contains(&"Canvas2DState"));
        assert!(names.contains(&"Canvas2DState::new"));
        assert!(names.contains(&"Canvas2DState::arc"));
        assert!(names.contains(&"Canvas2DState::flush"));
        assert!(names.contains(&"helper"));
    }
}
